helios: helios::rendering::RenderQueue Class Reference
helios::rendering::RenderQueue Class Reference export
module helios.rendering.RenderQueue
Manages a collection of `RenderCommand` objects for a single rendering pass.
Public Member Functions
~RenderQueue ()=default
RenderQueue (const RenderQueue &)=delete
Delete copy constructor.
RenderQueue & operator= (const RenderQueue &)=delete
Delete copy assignment operator.
RenderQueue (RenderQueue &&) noexcept=delete
Delete move constructor.
RenderQueue & operator= (RenderQueue &&) noexcept=delete
Delete move assignment operator.
RenderQueue ()=default
Constructs a new empty RenderQueue.
void add (std::unique_ptr< const helios::rendering::RenderCommand > renderCommand)
Adds a `RenderCommand` to this `RenderQueue`. Ownership of the `RenderCommand` is transferred to this `RenderQueue`.
const std::vector< std::unique_ptr< const helios::rendering::RenderCommand > > & renderCommands () const noexcept
Returns a const ref to the internal vector of `RenderCommand`.
void clear ()
Clears all `RenderCommand` objects from the queue.
size_t count () const noexcept
Returns the number of `RenderCommand`s this queue contains.
Protected Attributes
std::vector< std::unique_ptr< const helios::rendering::RenderCommand > > renderCommands_
Stores the unique ptrs to the RenderCommand objects of this queue.
Static Protected Attributes
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Shared logger instance for all RenderQueue objects.
Detailed Description
Manages a collection of `RenderCommand` objects for a single rendering pass.
`RenderQueue` acts as a container for all render commands, represented by a `RenderCommand`. A `RenderQueue` holds unique ownership of the render commands.
An instance of `RenderQueue` can be cleared after being processed in a `RenderPass` for reuse in subsequent render passes.
The class is designed to be non-copyable.
Definition at line 33 of file RenderQueue.ixx.
Constructor & Destructor Documentation
~RenderQueue()
helios::rendering::RenderQueue::~RenderQueue () export default
RenderQueue() [1/3]
helios::rendering::RenderQueue::RenderQueue (const RenderQueue &) export delete
Delete copy constructor.
References RenderQueue().
Referenced by operator=(), operator=(), RenderQueue(), RenderQueue(), and RenderQueue().
RenderQueue() [2/3]
helios::rendering::RenderQueue::RenderQueue (RenderQueue &&) export delete noexcept
Delete move constructor.
References RenderQueue().
RenderQueue() [3/3]
helios::rendering::RenderQueue::RenderQueue () export default
Constructs a new empty RenderQueue.
References RenderQueue().
Member Function Documentation
add()
void helios::rendering::RenderQueue::add (std::unique_ptr< const helios::rendering::RenderCommand > renderCommand) export
Adds a `RenderCommand` to this `RenderQueue`. Ownership of the `RenderCommand` is transferred to this `RenderQueue`.
Parameters
renderCommand A unique_ptr to the RenderCommand. This instance takes ownership of the RenderCommand.
Todo
prevent adding renderables while rendering
References add().
Referenced by add().
clear()
void helios::rendering::RenderQueue::clear () export
Clears all `RenderCommand` objects from the queue.
This prepares this queue to be reused in a new rendering pass.
References clear().
Referenced by clear().
count()
size_t helios::rendering::RenderQueue::count () const nodiscard export noexcept
Returns the number of `RenderCommand`s this queue contains.
Returns
The number of RenderCommands in this queue.
References count().
Referenced by count().
operator=() [1/2]
RenderQueue & helios::rendering::RenderQueue::operator= (const RenderQueue &) export delete
Delete copy assignment operator.
References RenderQueue().
operator=() [2/2]
RenderQueue & helios::rendering::RenderQueue::operator= (RenderQueue &&) export delete noexcept
Delete move assignment operator.
References RenderQueue().
renderCommands()
const std::vector< std::unique_ptr< const helios::rendering::RenderCommand > > & helios::rendering::RenderQueue::renderCommands () const nodiscard export noexcept
Returns a const ref to the internal vector of `RenderCommand`.
Returns
A const ref to the list of `RenderCommand`s of this queue.
References renderCommands().
Referenced by renderCommands().
The documentation for this class was generated from the following file:
include/helios/rendering/RenderQueue.ixx