helios: helios::util::log::LogSink Interface Reference
helios::util::log::LogSink Interface Reference abstract export
module helios.util.log.LogSink
Abstract sink interface for log message output.
Public Member Functions
virtual ~LogSink ()=default
virtual SinkTypeId typeId () const noexcept=0
Returns the unique type identifier for this sink.
virtual void write (LogLevel level, const std::string &scope, const std::string &message)=0
Writes a log message to this sink.
virtual void flush ()
Flushes any buffered output (optional).
Detailed Description
Abstract sink interface for log message output.
LogSink defines the contract for log output destinations. Implementations can write to console, files, ImGui widgets, network sockets, or any other target. Multiple sinks can be attached to a Logger for simultaneous output to different destinations.
Each sink must provide a unique type identifier via `typeId()`. This allows the LogManager to selectively enable or disable sinks at runtime without requiring a central registry of all possible sink types.
Definition at line 54 of file LogSink.ixx.
Constructor & Destructor Documentation
~LogSink()
virtual helios::util::log::LogSink::~LogSink () export virtual default
Member Function Documentation
flush()
virtual void helios::util::log::LogSink::flush () inline export virtual
Flushes any buffered output (optional).
Default implementation does nothing. Override for sinks that buffer.
Implemented in helios::util::log::ConsoleSink.
Definition at line 83 of file LogSink.ixx.
References flush().
Referenced by flush().
typeId()
virtual SinkTypeId helios::util::log::LogSink::typeId () const nodiscard export pure virtual noexcept
Returns the unique type identifier for this sink.
Each sink implementation should define a static constexpr identifier and return it here. Used by LogManager to match sinks for enable/disable.
Returns
A string identifier unique to this sink type (e.g., "console", "file").
Implemented in helios::ext::imgui::ImGuiLogSink, and helios::util::log::ConsoleSink.
write()
virtual void helios::util::log::LogSink::write (LogLevel level, const std::string & scope, const std::string & message) export pure virtual
Writes a log message to this sink.
Parameters
level The severity level of the message.
scope The source scope/module name.
message The log message text.
Implemented in helios::ext::imgui::ImGuiLogSink, and helios::util::log::ConsoleSink.
References write().
Referenced by write().
The documentation for this interface was generated from the following file:
include/helios/util/log/LogSink.ixx