helios: helios::input::gamepad::GamepadSettings Class Reference
helios::input::gamepad::GamepadSettings Class Reference export
module helios.input.gamepad.GamepadSettings
Configuration class for gamepad input normalization and axis behavior.
Public Member Functions
~GamepadSettings ()=default
Default destructor.
GamepadSettings ()=default
Default constructor with zero deadzone and no axis inversion.
GamepadSettings & setLeftStickDeadzone (float deadzone) noexcept
Sets the deadzone threshold for the left analog stick.
GamepadSettings & setRightStickDeadzone (float deadzone) noexcept
Sets the deadzone threshold for the right analog stick.
GamepadSettings & setInvertLeftX (bool invert) noexcept
Sets whether the left stick's X-axis should be inverted.
GamepadSettings & setInvertLeftY (bool invert) noexcept
Sets whether the left stick's Y-axis should be inverted.
GamepadSettings & setInvertRightX (bool invert) noexcept
Sets whether the right stick's X-axis should be inverted.
GamepadSettings & setInvertRightY (bool invert) noexcept
Sets whether the right stick's Y-axis should be inverted.
float leftStickDeadzone () const noexcept
Returns the configured deadzone for the left stick.
float rightStickDeadzone () const noexcept
Returns the configured deadzone for the right stick.
bool invertLeftX () const noexcept
Returns whether the left stick's X-axis is inverted.
bool invertLeftY () const noexcept
Returns whether the left stick's Y-axis is inverted.
bool invertRightX () const noexcept
Returns whether the right stick's X-axis is inverted.
bool invertRightY () const noexcept
Returns whether the right stick's Y-axis is inverted.
Detailed Description
Configuration class for gamepad input normalization and axis behavior.
This class encapsulates all settings that affect how raw gamepad input is processed before being consumed by the application. It provides fluent setter methods for convenient method chaining during configuration.
**Configurable options:**
**Deadzone values:** Per-stick thresholds for filtering out hardware drift.
**Axis inversion:** Individual control over X/Y axis inversion for both sticks.
Deadzone values are clamped to the range [0.0, 0.9] to ensure that at least 10% of the stick's range remains usable.
Example usage: ```cpp GamepadSettings settings; settings.setLeftStickDeadzone(0.15f) .setRightStickDeadzone(0.1f) .setInvertLeftY(true); ```
See also
DeadzoneStrategy for how deadzone values are applied during normalization.
Definition at line 37 of file GamepadSettings.ixx.
Constructor & Destructor Documentation
~GamepadSettings()
helios::input::gamepad::GamepadSettings::~GamepadSettings () export default
Default destructor.
GamepadSettings()
helios::input::gamepad::GamepadSettings::GamepadSettings () export default
Default constructor with zero deadzone and no axis inversion.
Referenced by setInvertLeftX(), setInvertLeftY(), setInvertRightX(), setInvertRightY(), setLeftStickDeadzone(), and setRightStickDeadzone().
Member Function Documentation
invertLeftX()
bool helios::input::gamepad::GamepadSettings::invertLeftX () const inline nodiscard export noexcept
Returns whether the left stick's X-axis is inverted.
Returns
True if inverted, false otherwise.
Definition at line 178 of file GamepadSettings.ixx.
invertLeftY()
bool helios::input::gamepad::GamepadSettings::invertLeftY () const inline nodiscard export noexcept
Returns whether the left stick's Y-axis is inverted.
Returns
True if inverted, false otherwise.
Definition at line 187 of file GamepadSettings.ixx.
invertRightX()
bool helios::input::gamepad::GamepadSettings::invertRightX () const inline nodiscard export noexcept
Returns whether the right stick's X-axis is inverted.
Returns
True if inverted, false otherwise.
Definition at line 196 of file GamepadSettings.ixx.
invertRightY()
bool helios::input::gamepad::GamepadSettings::invertRightY () const inline nodiscard export noexcept
Returns whether the right stick's Y-axis is inverted.
Returns
True if inverted, false otherwise.
Definition at line 205 of file GamepadSettings.ixx.
leftStickDeadzone()
float helios::input::gamepad::GamepadSettings::leftStickDeadzone () const inline nodiscard export noexcept
Returns the configured deadzone for the left stick.
Returns
The deadzone threshold in the range [0.0, 0.9].
Definition at line 160 of file GamepadSettings.ixx.
rightStickDeadzone()
float helios::input::gamepad::GamepadSettings::rightStickDeadzone () const inline nodiscard export noexcept
Returns the configured deadzone for the right stick.
Returns
The deadzone threshold in the range [0.0, 0.9].
Definition at line 169 of file GamepadSettings.ixx.
setInvertLeftX()
GamepadSettings & helios::input::gamepad::GamepadSettings::setInvertLeftX (bool invert) inline export noexcept
Sets whether the left stick's X-axis should be inverted.
Parameters
invert True to invert, false for normal behavior.
Returns
Reference to this object for method chaining.
Definition at line 114 of file GamepadSettings.ixx.
References GamepadSettings().
setInvertLeftY()
GamepadSettings & helios::input::gamepad::GamepadSettings::setInvertLeftY (bool invert) inline export noexcept
Sets whether the left stick's Y-axis should be inverted.
Parameters
invert True to invert, false for normal behavior.
Returns
Reference to this object for method chaining.
Definition at line 126 of file GamepadSettings.ixx.
References GamepadSettings().
setInvertRightX()
GamepadSettings & helios::input::gamepad::GamepadSettings::setInvertRightX (bool invert) inline export noexcept
Sets whether the right stick's X-axis should be inverted.
Parameters
invert True to invert, false for normal behavior.
Returns
Reference to this object for method chaining.
Definition at line 138 of file GamepadSettings.ixx.
References GamepadSettings().
setInvertRightY()
GamepadSettings & helios::input::gamepad::GamepadSettings::setInvertRightY (bool invert) inline export noexcept
Sets whether the right stick's Y-axis should be inverted.
Parameters
invert True to invert, false for normal behavior.
Returns
Reference to this object for method chaining.
Definition at line 150 of file GamepadSettings.ixx.
References GamepadSettings().
setLeftStickDeadzone()
GamepadSettings & helios::input::gamepad::GamepadSettings::setLeftStickDeadzone (float deadzone) inline export noexcept
Sets the deadzone threshold for the left analog stick.
Parameters
deadzone The deadzone value, clamped to [0.0, 0.9].
Returns
Reference to this object for method chaining.
Definition at line 88 of file GamepadSettings.ixx.
References GamepadSettings().
setRightStickDeadzone()
GamepadSettings & helios::input::gamepad::GamepadSettings::setRightStickDeadzone (float deadzone) inline export noexcept
Sets the deadzone threshold for the right analog stick.
Parameters
deadzone The deadzone value, clamped to [0.0, 0.9].
Returns
Reference to this object for method chaining.
Definition at line 101 of file GamepadSettings.ixx.
References GamepadSettings().
The documentation for this class was generated from the following file:
include/helios/input/gamepad/GamepadSettings.ixx