helios: helios::rendering::Renderable Class Reference
helios::rendering::Renderable Class Reference final export
module helios.rendering.Renderable
Representative of a configurable Renderable that references an immutable RenderPrototype and instance specific material property overrides.
Public Member Functions
Renderable ()=delete
Deleted default constructor.
Renderable (const Renderable &)=delete
Deleted copy constructor.
Renderable & operator= (const Renderable &)=delete
Deleted copy assignment operator.
Renderable (Renderable &&) noexcept=default
Defaulted move constructor.
Renderable & operator= (Renderable &&) noexcept=default
Defaulted move assignment operator.
Renderable (std::shared_ptr< const helios::rendering::RenderPrototype > renderPrototype, const std::optional< helios::rendering::model::config::MaterialPropertiesOverride > &materialOverride=std::nullopt)
Creates a new Renderable instance.
std::shared_ptr< const helios::rendering::RenderPrototype > renderPrototype () const noexcept
Returns a shared pointer to the RenderPrototype used by this Renderable.
const std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & materialOverride () const noexcept
Returns a const reference to the optional instance-specific MaterialPropertiesOverride.
std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & materialOverride () noexcept
Returns a non-const reference to the optional instance-specific MaterialPropertiesOverride.
bool hasMaterialOverride () const noexcept
Returns true if this Renderable was configured with a MaterialPropertiesOverride.
void writeUniformValues (helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept
Writes uniform values into the given map.
Protected Attributes
std::shared_ptr< const helios::rendering::RenderPrototype > renderPrototype_ = nullptr
Shared pointer to the immutable RenderPrototype definition.
std::optional< helios::rendering::model::config::MaterialPropertiesOverride > materialOverride_
The MaterialPropertiesOverride owned by this class. This will be std::nullopt if not available.
Static Protected Attributes
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Shared logger instance for all Renderable objects.
Detailed Description
Representative of a configurable Renderable that references an immutable RenderPrototype and instance specific material property overrides.
A Renderable aggregates a reference to an immutable RenderPrototype (the shared asset definition) with optional instance-specific material property overrides. This separation enables efficient batching of shared RenderPrototypes while allowing individual visual adjustments per Renderable instance.
The Renderable's interface is API-agnostic, enabling efficient batching and per-instance customization, while abstracting the underlying API-specific rendering resources bundled within the RenderPrototype.
Renderables are designed to be movable (e.g., in render queues) but not copyable to ensure unique instance identity in processing.
Definition at line 38 of file Renderable.ixx.
Constructor & Destructor Documentation
Renderable() [1/4]
helios::rendering::Renderable::Renderable () export delete
Deleted default constructor.
Referenced by operator=(), operator=(), Renderable(), Renderable(), and Renderable().
Renderable() [2/4]
helios::rendering::Renderable::Renderable (const Renderable &) export delete
Deleted copy constructor.
References Renderable().
Renderable() [3/4]
helios::rendering::Renderable::Renderable (Renderable &&) export default noexcept
Defaulted move constructor.
References Renderable().
Renderable() [4/4]
helios::rendering::Renderable::Renderable (std::shared_ptr< const helios::rendering::RenderPrototype > renderPrototype, const std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & materialOverride = std::nullopt) explicit export
Creates a new Renderable instance.
Parameters
renderPrototype A shared pointer to the immutable RenderPrototype definition. Must not be nullptr.
materialOverride An optional set of instance-specific material property overrides. If std::nullopt, the Renderable uses only the default properties from the RenderPrototype's Material.
Exceptions
std::invalid_argument if `renderPrototype` is a nullptr.
References materialOverride(), Renderable(), and renderPrototype().
Member Function Documentation
hasMaterialOverride()
bool helios::rendering::Renderable::hasMaterialOverride () const nodiscard export noexcept
Returns true if this Renderable was configured with a MaterialPropertiesOverride.
Returns
True if this Renderable was configured with a MaterialPropertiesOverride instance, otherwise false.
References hasMaterialOverride().
Referenced by hasMaterialOverride().
materialOverride() [1/2]
const std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & helios::rendering::Renderable::materialOverride () const nodiscard export noexcept
Returns a const reference to the optional instance-specific MaterialPropertiesOverride.
This allows read-only access to the overrides. Use `.has_value()` to check for existence and `.value()` or `->` to safely access the override data.
Returns
A const reference to the std::optional<MaterialPropertiesOverride>.
References materialOverride().
Referenced by materialOverride(), materialOverride(), and Renderable().
materialOverride() [2/2]
std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & helios::rendering::Renderable::materialOverride () nodiscard export noexcept
Returns a non-const reference to the optional instance-specific MaterialPropertiesOverride.
This allows modification of the overrides. If the optional currently has no value, it can be assigned to or `.emplace()` can be used to create a new MaterialPropertiesOverride.
Returns
A non-const reference to the std::optional<MaterialPropertiesOverride>.
References materialOverride().
operator=() [1/2]
Renderable & helios::rendering::Renderable::operator= (const Renderable &) export delete
Deleted copy assignment operator.
References Renderable().
operator=() [2/2]
Renderable & helios::rendering::Renderable::operator= (Renderable &&) export default noexcept
Defaulted move assignment operator.
References Renderable().
renderPrototype()
std::shared_ptr< const helios::rendering::RenderPrototype > helios::rendering::Renderable::renderPrototype () const nodiscard export noexcept
Returns a shared pointer to the RenderPrototype used by this Renderable.
Returns
A shared pointer to the RenderPrototype.
References renderPrototype().
Referenced by Renderable(), and renderPrototype().
writeUniformValues()
void helios::rendering::Renderable::writeUniformValues (helios::rendering::shader::UniformValueMap & uniformValueMap) const export noexcept
Writes uniform values into the given map.
This method first applies the default uniform values from the base Material definition and then overlays any specific overrides provided by this instance's MaterialPropertiesOverride.
Parameters
uniformValueMap Target map receiving the uniform values.
References writeUniformValues().
Referenced by writeUniformValues().
The documentation for this class was generated from the following file:
include/helios/rendering/Renderable.ixx