helios: helios::engine::game::components::physics::TransformComponent Class Reference
helios::engine::game::components::physics::TransformComponent Class Reference export
module helios.engine.game.components.physics.TransformComponent
Component that holds transformation data (position, rotation, scale).
Public Member Functions
bool isDirty () const noexcept
Checks if the transform is dirty.
void clearDirty () noexcept
Clears the dirty flag.
helios::math::mat4f localTransform () const noexcept
Returns the local transformation matrix.
TransformComponent & setLocalScale (const helios::math::vec3f &scale) noexcept
Sets the local scale.
TransformComponent & setLocalRotation (const helios::math::mat4f &rotation) noexcept
Sets the local rotation matrix.
TransformComponent & setLocalTranslation (const helios::math::vec3f &translation) noexcept
Sets the local translation (position).
TransformComponent & translateLocalBy (const helios::math::vec3f &translation) noexcept
Translates the component locally by a delta vector.
helios::math::vec3f localTranslation () const noexcept
Returns the local translation vector.
helios::math::mat4f localRotation () const noexcept
Returns the local rotation matrix.
helios::math::vec3f localScaling () const noexcept
Returns the local scaling vector.
void setWorldTransform (const helios::math::mat4f &m) noexcept
Sets the world transform matrix directly.
const helios::math::mat4f & worldTransform () noexcept
Returns the current world transform matrix.
helios::math::vec3f worldTranslation () noexcept
Extracts the world translation from the world transform.
Public Member Functions inherited from helios::engine::game::Component
virtual ~Component ()=default
Component ()=default
virtual void onAttach (GameObject *gameObject) noexcept
Called when the component is attached to a GameObject.
GameObject * gameObject () const noexcept
Returns the owning GameObject.
Additional Inherited Members
Protected Attributes inherited from helios::engine::game::Component
GameObject * gameObject_ = nullptr
Non-owning pointer to the owning GameObject.
Detailed Description
Component that holds transformation data (position, rotation, scale).
The TransformComponent manages the spatial state of a GameObject. It stores the local transform (relative to parent) and the computed world transform. Changes to local properties mark the component as dirty, signaling systems to recompute the world transform.
Definition at line 23 of file TransformComponent.ixx.
Member Function Documentation
clearDirty()
void helios::engine::game::components::physics::TransformComponent::clearDirty () inline export noexcept
Clears the dirty flag.
Definition at line 56 of file TransformComponent.ixx.
Referenced by helios::engine::game::systems::post::TransformClearSystem::update().
isDirty()
bool helios::engine::game::components::physics::TransformComponent::isDirty () const inline nodiscard export noexcept
Checks if the transform is dirty.
Returns
True if the transform has changed, false otherwise.
Definition at line 49 of file TransformComponent.ixx.
Referenced by helios::engine::game::systems::scene::SceneSyncSystem::update().
localRotation()
helios::math::mat4f helios::engine::game::components::physics::TransformComponent::localRotation () const inline nodiscard export noexcept
Returns the local rotation matrix.
Returns
The rotation relative to the parent.
Definition at line 135 of file TransformComponent.ixx.
localScaling()
helios::math::vec3f helios::engine::game::components::physics::TransformComponent::localScaling () const inline nodiscard export noexcept
Returns the local scaling vector.
Returns
The scale relative to the parent.
Definition at line 145 of file TransformComponent.ixx.
localTransform()
helios::math::mat4f helios::engine::game::components::physics::TransformComponent::localTransform () const inline nodiscard export noexcept
Returns the local transformation matrix.
Returns
The 4x4 matrix representing local translation, rotation, and scale.
Definition at line 65 of file TransformComponent.ixx.
localTranslation()
helios::math::vec3f helios::engine::game::components::physics::TransformComponent::localTranslation () const inline nodiscard export noexcept
Returns the local translation vector.
Returns
The position relative to the parent.
Definition at line 125 of file TransformComponent.ixx.
setLocalRotation()
TransformComponent & helios::engine::game::components::physics::TransformComponent::setLocalRotation (const helios::math::mat4f & rotation) inline export noexcept
Sets the local rotation matrix.
Parameters
rotation The new rotation matrix.
Returns
Reference to this component for chaining.
Definition at line 89 of file TransformComponent.ixx.
setLocalScale()
TransformComponent & helios::engine::game::components::physics::TransformComponent::setLocalScale (const helios::math::vec3f & scale) inline export noexcept
Sets the local scale.
Parameters
scale The new scale vector.
Returns
Reference to this component for chaining.
Definition at line 76 of file TransformComponent.ixx.
setLocalTranslation()
TransformComponent & helios::engine::game::components::physics::TransformComponent::setLocalTranslation (const helios::math::vec3f & translation) inline export noexcept
Sets the local translation (position).
Parameters
translation The new position vector.
Returns
Reference to this component for chaining.
Definition at line 102 of file TransformComponent.ixx.
setWorldTransform()
void helios::engine::game::components::physics::TransformComponent::setWorldTransform (const helios::math::mat4f & m) inline export noexcept
Sets the world transform matrix directly.
Parameters
m The new world transform matrix.
Definition at line 154 of file TransformComponent.ixx.
Referenced by helios::engine::game::systems::scene::SceneSyncSystem::update().
translateLocalBy()
TransformComponent & helios::engine::game::components::physics::TransformComponent::translateLocalBy (const helios::math::vec3f & translation) inline export noexcept
Translates the component locally by a delta vector.
Parameters
translation The vector to add to the current position.
Returns
Reference to this component for chaining.
Definition at line 114 of file TransformComponent.ixx.
worldTransform()
const helios::math::mat4f & helios::engine::game::components::physics::TransformComponent::worldTransform () inline export noexcept
Returns the current world transform matrix.
Returns
Const reference to the world transform.
Definition at line 164 of file TransformComponent.ixx.
worldTranslation()
helios::math::vec3f helios::engine::game::components::physics::TransformComponent::worldTranslation () inline export noexcept
Extracts the world translation from the world transform.
Returns
The global position vector.
Definition at line 173 of file TransformComponent.ixx.
The documentation for this class was generated from the following file:
include/helios/engine/game/components/physics/TransformComponent.ixx