helios: helios::ext::glfw::app::GLFWApplication Class Reference
helios::ext::glfw::app::GLFWApplication Class Reference export
module helios.ext.glfw.app.GLFWApplication
An Application implementation for glfw-based environments.
Public Member Functions
GLFWApplication (std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice, std::unique_ptr< helios::input::InputManager > inputManager, std::unique_ptr< helios::event::EventManager > eventManager)
Constructs a new `GLFWApplication` instance.
void init () override
Initializes the application.
helios::ext::glfw::window::GLFWWindow & createWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const helios::ext::glfw::window::GLFWWindowConfig &cfg)
Creates a new GLFWWindow and add it to this Application's windows collection. The Application takes ownership of the window.
helios::ext::glfw::window::GLFWWindow & createWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const helios::window::WindowConfig &cfg) override
Creates the container for the native window and performs all necessary steps to properly initialize it.
void setCurrent (helios::window::Window &win) override
Sets the current window for this application.
helios::window::Window * current () const noexcept override
Returns the currently focused window, or nullptr if none exists or no window is being treated as current.
Public Member Functions inherited from helios::app::Application
virtual ~Application ()=default
Application (std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice, std::unique_ptr< helios::input::InputManager > inputManager, std::unique_ptr< helios::event::EventManager > eventManager)
Creates a new application instance.
void addController (std::unique_ptr< helios::app::controller::Controller > controller) noexcept
Registers a new controller with this application.
bool hasWindow (const helios::window::Window &win) const noexcept
Returns true if the specified window is owned by this application, otherwise false.
helios::input::InputManager & inputManager () const
Returns the input manager owned by this application.
helios::rendering::RenderingDevice & renderingDevice () const
Returns the rendering device owned by this application.
helios::event::EventManager & eventManager () const
Returns the event manager owned by this application.
Additional Inherited Members
Protected Attributes inherited from helios::app::Application
bool initialized_ = false
Flag indicating whether the application has been initialized.
std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice_
The rendering device owned by this application.
std::unique_ptr< input::InputManager > inputManager_
The input manager owned by this application.
std::unique_ptr< event::EventManager > eventManager_
The event manager owned by this application.
std::list< std::unique_ptr< helios::window::Window > > windowList_
A list containing all windows managed by this application.
std::vector< std::unique_ptr< helios::app::controller::Controller > > controllers_
Collection of controllers registered with this application.
Static Protected Attributes inherited from helios::app::Application
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Shared logger instance for all Application objects.
Detailed Description
An Application implementation for glfw-based environments.
This application owns a `GLFWRAIIGuard`.
Definition at line 32 of file GLFWApplication.ixx.
Constructor & Destructor Documentation
GLFWApplication()
helios::ext::glfw::app::GLFWApplication::GLFWApplication (std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice, std::unique_ptr< helios::input::InputManager > inputManager, std::unique_ptr< helios::event::EventManager > eventManager) explicit export
Constructs a new `GLFWApplication` instance.
Parameters
renderingDevice Unique rendering device owned by the application.
inputManager Unique input manager instance.
eventManager Unique event manager instance.
References helios::app::Application::eventManager(), helios::app::Application::inputManager(), and helios::app::Application::renderingDevice().
Member Function Documentation
createWindow() [1/2]
helios::ext::glfw::window::GLFWWindow & helios::ext::glfw::app::GLFWApplication::createWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const helios::ext::glfw::window::GLFWWindowConfig & cfg) export
Creates a new GLFWWindow and add it to this Application's windows collection. The Application takes ownership of the window.
Delegates to Window::show() for showing the window and initializes the associated rendering device if necessary, e.g. for glfw an additional `glfwMakeContextCurrent()` is called so the rendering device can be safely initialized, then immediately passes a `nullptr` to the `glfwMakeContextCurrent()` to force calling APIs to explicitly call setCurrent() on the constructed window. The render target size is synced to the current framebuffer dimensions reported by `glfwGetFramebufferSize()`.
Returns
Reference to the created window instance.
See also
https://www.glfw.org/docs/latest/group__window.html#ga0e2637a4161afb283f5300c7f94785c9
Returns
A ref to the window created.
createWindow() [2/2]
helios::ext::glfw::window::GLFWWindow & helios::ext::glfw::app::GLFWApplication::createWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const helios::window::WindowConfig & cfg) override export virtual
Creates the container for the native window and performs all necessary steps to properly initialize it.
Parameters
renderTarget Render target that wraps the framebuffer used by the window.
cfg Window configuration defining properties such as title, dimensions, and hints.
Returns
Reference to the created window instance.
Exceptions
std::invalid_argument If the configuration was invalid.
Implements helios::app::Application.
current()
helios::window::Window * helios::ext::glfw::app::GLFWApplication::current () const nodiscard override export virtual noexcept
Returns the currently focused window, or nullptr if none exists or no window is being treated as current.
Returns
Pointer to the current window, or nullptr if none is active.
Implements helios::app::Application.
init()
void helios::ext::glfw::app::GLFWApplication::init () override export virtual
Initializes the application.
Performs any bootstrapping necessary for this application and provides an idiomatic entry point for APIs using this application. This method ensures that all controllers are initialized and subscribe to this application's event manager dispatcher.
Exceptions
std::runtime_error If the application was already initialized.
Reimplemented from helios::app::Application.
setCurrent()
void helios::ext::glfw::app::GLFWApplication::setCurrent (helios::window::Window & win) override export virtual
Sets the current window for this application.
Ensures `glfwMakeContextCurrent()` is called to bind the correct context for subsequent glfw operations and re-registers the framebuffer size callback on the targeted window.
Parameters
win Reference to the window that becomes the current context owner.
Exceptions
std::invalid_argument If `win` is not a `GLFWWindow` or not owned by this application.
Implements helios::app::Application.
The documentation for this class was generated from the following file:
include/ext/glfw/app/GLFWApplication.ixx