helios: helios::rendering::model::Mesh Class Reference
helios::rendering::model::Mesh Class Reference abstract export
module helios.rendering.model.Mesh
Representative of a renderable 3D mesh.
Public Member Functions
virtual ~Mesh ()=default
Mesh (std::shared_ptr< const std::vector< Vertex > > vertices, std::shared_ptr< const std::vector< unsigned int > > indices, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig)
Creates a new Mesh instance.
Mesh (const helios::rendering::asset::shape::Shape &shape, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig)
Creates a new Mesh instance from the specified Shape.
unsigned int indexCount () const noexcept
Returns the index count of this Mesh.
const std::vector< Vertex > & vertices () const noexcept
Returns a const reference to the underlying vertices. The returned data is guaranteed to be a valid reference to existing data.
const std::vector< unsigned int > & indices () const noexcept
Returns a const reference to the underlying indices. The returned data is guaranteed to be a valid reference to existing data.
const helios::rendering::model::config::MeshConfig & meshConfig () const noexcept
Returns a const reference to MeshConfig used with this Mesh. The returned MeshConfig is guaranteed to be a valid reference to existing data.
const helios::math::aabbf & aabb () const noexcept
Retrieves the axis-aligned bounding box (AABB) of the mesh.
Protected Member Functions
Mesh ()=default
virtual void init ()=0
Initializes the Mesh by setting up vertex attributes and buffers with the underlying GL API. This method should be called _once_ by the derived class before using this Mesh in a rendering pass.
Protected Attributes
bool needsUpdate_ = true
Flag indicating whether the mesh requires updates to its computed data.
helios::math::aabbf aabb_ {}
Represents the axis-aligned bounding box (AABB) for the mesh.
std::shared_ptr< const std::vector< Vertex > > vertices_ = nullptr
Shared pointer to the raw, immutable vertices.
std::shared_ptr< const std::vector< unsigned int > > indices_ = nullptr
Shared pointer to the raw, immutable indices.
std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig_
Shared pointer to the MeshConfig used with this Mesh.
Static Protected Attributes
static const helios::util::log::Logger & logger_
Shared logger instance for all Mesh objects.
Detailed Description
Representative of a renderable 3D mesh.
A Mesh instance contains vertex data and indices provided by geometric shapes. Meshes contain references to immutable, shared vertex data and indices. Concrete implementations will handle resource management.
See also
[Gre19, 631]
Definition at line 35 of file Mesh.ixx.
Constructor & Destructor Documentation
Mesh() [1/3]
helios::rendering::model::Mesh::Mesh () export protected default
~Mesh()
virtual helios::rendering::model::Mesh::~Mesh () export virtual default
Mesh() [2/3]
helios::rendering::model::Mesh::Mesh (std::shared_ptr< const std::vector< Vertex > > vertices, std::shared_ptr< const std::vector< unsigned int > > indices, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig) explicit export
Creates a new Mesh instance.
Parameters
vertices A shared_ptr to a vector of Vertex.
indices A shared_ptr to a vector of indices.
meshConfig A shared_ptr to the MeshConfig used with this Mesh.
Exceptions
std::invalid_argument if either "vertices", "indices" or meshConfig is a null shared_ptr
References indices(), meshConfig(), and vertices().
Mesh() [3/3]
helios::rendering::model::Mesh::Mesh (const helios::rendering::asset::shape::Shape & shape, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig) explicit export
Creates a new Mesh instance from the specified Shape.
Parameters
shape A const reference to the Shape.
meshConfig A shared_ptr to the MeshConfig used with this Mesh.
Exceptions
std::invalid_argument if meshConfig is a null shared_ptr, or if the shape contained null data.
References meshConfig().
Member Function Documentation
aabb()
const helios::math::aabbf & helios::rendering::model::Mesh::aabb () const nodiscard export noexcept
Retrieves the axis-aligned bounding box (AABB) of the mesh.
The method calculates and returns the AABB of the mesh, which encloses the mesh's vertices. If the mesh requires an update to its bounding box, this method recomputes the bounds based on the vertex positions and caches the result for future calls. The returned AABB represents the minimal rectangle in 3D space that contains all the vertices of the mesh.
Returns
Reference to the computed axis-aligned bounding box.
References aabb().
Referenced by aabb().
indexCount()
unsigned int helios::rendering::model::Mesh::indexCount () const nodiscard export noexcept
Returns the index count of this Mesh.
Returns
The number of indices handled by this Mesh.
indices()
const std::vector< unsigned int > & helios::rendering::model::Mesh::indices () const nodiscard export noexcept
Returns a const reference to the underlying indices. The returned data is guaranteed to be a valid reference to existing data.
Returns
A const ref to the vector of indices.
References indices().
Referenced by indices(), Mesh(), and helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh().
init()
virtual void helios::rendering::model::Mesh::init () export protected pure virtual
Initializes the Mesh by setting up vertex attributes and buffers with the underlying GL API. This method should be called _once_ by the derived class before using this Mesh in a rendering pass.
Todo
std::shared_ptr<const std::vector<Texture>> textures_;
Exceptions
std::runtime_error if the Mesh could not be initialized.
Implemented in helios::ext::opengl::rendering::model::OpenGLMesh.
meshConfig()
const helios::rendering::model::config::MeshConfig & helios::rendering::model::Mesh::meshConfig () const nodiscard export noexcept
Returns a const reference to MeshConfig used with this Mesh. The returned MeshConfig is guaranteed to be a valid reference to existing data.
Returns
The MeshConfig used with this Mesh.
References meshConfig().
Referenced by Mesh(), Mesh(), meshConfig(), helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh(), and helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh().
vertices()
const std::vector< Vertex > & helios::rendering::model::Mesh::vertices () const nodiscard export noexcept
Returns a const reference to the underlying vertices. The returned data is guaranteed to be a valid reference to existing data.
Returns
A const ref to the vector of Vertex.
References vertices().
Referenced by Mesh(), helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh(), and vertices().
The documentation for this class was generated from the following file:
include/helios/rendering/model/Mesh.ixx