helios: helios::window::Window Class Reference
helios::window::Window Class Reference abstract export
module helios.window.Window
Abstract base class representing a generic window.
Public Member Functions
virtual ~Window ()=default
Window (const Window &)=delete
Window & operator= (const Window &)=delete
Window (Window &&) noexcept=default
Window & operator= (Window &&) noexcept=default
Window (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const WindowConfig &cfg)
Constructs a new Window based on the provided configuration.
virtual bool shouldClose () const =0
Checks if the window has received a close request.
virtual void setShouldClose (bool close)=0
Sets the close flag of this window.
const util::Guid & guid () const noexcept
Returns the unique guid for this window instance.
virtual bool show () noexcept=0
Shows the underlying native window.
virtual void swapBuffers () const noexcept=0
Instructs the rendering system to swap the front and back buffers.
virtual void pollEvents () const noexcept=0
Poll this window for native window events.
int width () const noexcept
Returns the current width of this window.
int height () const noexcept
Returns the current height of this window.
helios::rendering::RenderTarget & renderTarget () const noexcept
Returns the RenderTarget associated with this Window.
std::shared_ptr< helios::rendering::Viewport > addViewport (std::shared_ptr< helios::rendering::Viewport > viewport) const
Adds the viewport to the underlying RenderTarget of this Window.
virtual bool operator== (const Window &win) const noexcept
Compares two window instances for equality.
Protected Attributes
int width_
The current width of the window.
int height_
The current height of the window.
std::string title_
The title of the window.
int aspectRatioNumer_ = 0
Aspect ratio numerator.
int aspectRatioDenom_ = 0
Aspect ratio denominator.
std::unique_ptr< helios::rendering::RenderTarget > renderTarget_
The default render target for this Window. The default RenderTarget represents the default framebuffer, e.g. the "0" FBO in OpenGL.
Static Protected Attributes
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
The logger used with this Window instance.
Detailed Description
Abstract base class representing a generic window.
This class provides a common interface for window management without depending on the underlying native window implementation.
A Window can be uniquely identified via its Guid.
Definition at line 31 of file Window.ixx.
Constructor & Destructor Documentation
~Window()
virtual helios::window::Window::~Window () export virtual default
Window() [1/3]
helios::window::Window::Window (const Window &) export delete
References Window().
Referenced by operator=(), operator=(), operator==(), Window(), Window(), and Window().
Window() [2/3]
helios::window::Window::Window (Window &&) export default noexcept
References Window().
Window() [3/3]
helios::window::Window::Window (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const WindowConfig & cfg) explicit export
Constructs a new Window based on the provided configuration.
Initializes basic properties such as width, height and the viewport of the window.
Parameters
renderTarget
cfg A const ref to the window configuration used for this instance.
Exceptions
std::invalid_argument if renderTarget is a nullptr
References renderTarget(), and Window().
Member Function Documentation
addViewport()
std::shared_ptr< helios::rendering::Viewport > helios::window::Window::addViewport (std::shared_ptr< helios::rendering::Viewport > viewport) const export
Adds the viewport to the underlying RenderTarget of this Window.
Parameters
viewport The Viewport instance to add to the RenderTarget owned by this Window.
Returns
The Viewport added to the Window's RenderTarget as a shared pointer.
References addViewport().
Referenced by addViewport().
guid()
const util::Guid & helios::window::Window::guid () const nodiscard export noexcept
Returns the unique guid for this window instance.
Returns
A const reference to the Guid of this window.
References guid().
Referenced by guid().
height()
int helios::window::Window::height () const nodiscard export noexcept
Returns the current height of this window.
Returns
The current height of this window.
References height().
Referenced by height().
operator=() [1/2]
Window & helios::window::Window::operator= (const Window &) export delete
References Window().
operator=() [2/2]
Window & helios::window::Window::operator= (Window &&) export default noexcept
References Window().
operator==()
virtual bool helios::window::Window::operator== (const Window & win) const export virtual noexcept
Compares two window instances for equality.
Two windows are considered equal if their GUIDs are equal.
Parameters
win The window to compare with this window.
Returns
true if both windows are equal, otherwise false.
References Window().
pollEvents()
virtual void helios::window::Window::pollEvents () const export pure virtual noexcept
Poll this window for native window events.
This method processes pending events from the native window system. Implementing APIs should call this method at regular intervals, e.g. once per frame.
Implemented in helios::ext::glfw::window::GLFWWindow.
References pollEvents().
Referenced by pollEvents().
renderTarget()
helios::rendering::RenderTarget & helios::window::Window::renderTarget () const nodiscard export noexcept
Returns the RenderTarget associated with this Window.
Returns
A reference to the RenderTarget of this window.
References renderTarget().
Referenced by helios::ext::glfw::window::GLFWWindow::GLFWWindow(), renderTarget(), and Window().
setShouldClose()
virtual void helios::window::Window::setShouldClose (bool close) export pure virtual
Sets the close flag of this window.
Parameters
close True to indicate this window should be closed, false otherwise.
See also
shouldClose()
Implemented in helios::ext::glfw::window::GLFWWindow.
References setShouldClose().
Referenced by setShouldClose().
shouldClose()
virtual bool helios::window::Window::shouldClose () const nodiscard export pure virtual
Checks if the window has received a close request.
Implementing APIs should consider this flag at regular intervals (e.g. each frame) to determine whether this window should be closed.
Returns
true if the window should be closed, otherwise false.
See also
setShouldClose()
Implemented in helios::ext::glfw::window::GLFWWindow.
References shouldClose().
Referenced by shouldClose().
show()
virtual bool helios::window::Window::show () export pure virtual noexcept
Shows the underlying native window.
Derived classes must implement the platform-specific logic to show this window.
Returns
true if showing the window succeeded, otherwise false.
Implemented in helios::ext::glfw::window::GLFWWindow.
References show().
Referenced by show().
swapBuffers()
virtual void helios::window::Window::swapBuffers () const export pure virtual noexcept
Instructs the rendering system to swap the front and back buffers.
Makes the back buffer's content visible on the screen. Derived classes must implement the platform-specific buffer mechanism.
Implemented in helios::ext::glfw::window::GLFWWindow.
References swapBuffers().
Referenced by swapBuffers().
width()
int helios::window::Window::width () const nodiscard export noexcept
Returns the current width of this window.
Returns
The current width of this window.
References width().
Referenced by width().
The documentation for this class was generated from the following file:
include/helios/window/Window.ixx