helios: helios::scene::Camera Class Reference
helios::scene::Camera Class Reference export
module helios.scene.Camera
Represents a camera for perspective or orthographic projection, deriving from SceneNode to allow for spatial positioning and transformation within the scene graph.
Public Member Functions
Camera ()
Constructor for this class. Initializes projectionMatrix and viewMatrix with the identity matrix.
SceneNode * addChild (std::unique_ptr< SceneNode > sceneNode) override
This method will do nothing but return `nullptr`, indicating that a `Camera` must not have child nodes.
const helios::math::mat4f & projectionMatrix () const noexcept
Returns a constant ref to this camera's current projection matrix. Typically set to the perspective / orthographic projection.
const helios::math::mat4f & viewMatrix () const noexcept
Returns a constant ref to this camera's view matrix. Automatically computed as the inverse of the camera's world transform.
Public Member Functions inherited from helios::scene::SceneNode
virtual ~SceneNode ()=default
SceneNode (const SceneNode &)=delete
Delete copy constructor. A SceneNode is not copyable.
SceneNode & operator= (const SceneNode &)=delete
Delete copy assignment constructor. A SceneNode ist not indtended to be copied.
SceneNode () noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
SceneNode (const Transform &transform) noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable, const Transform &transform) noexcept
Constructs a new SceneNode representing a renderable object.
SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable) noexcept
Constructs a new SceneNode representing a renderable object.
const helios::util::Guid & guid () const noexcept
Returns the globally unique identifier for this SceneNode.
const std::vector< std::unique_ptr< SceneNode > > & children () const noexcept
Returns a const ref to the list of this node's children.
std::shared_ptr< const helios::rendering::Renderable > renderable () const noexcept
Returns a shared pointer to the Renderable of this SceneNode.
SceneNode & scale (const helios::math::vec3f &scale) noexcept
Applies a scaling transformation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
SceneNode & rotate (const helios::math::mat4f &rotation) noexcept
Applies rotation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
SceneNode & translate (const helios::math::vec3f &translation) noexcept
Applies translation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
const Transform & localTransform () const noexcept
Returns this SceneNode's localTransform.
SceneNode * parent () const noexcept
Returns a pointer to this node's parent node.
bool setWorldTransform (const helios::math::mat4f &wf, helios::scene::SceneGraphKey sceneGraphKey) noexcept
Sets the world transform for this SceneNode. Does nothing if the current SceneNode's world transform is considered equal to the specified world transform.
const helios::math::mat4f & worldTransform () noexcept
Computes and returns the world transform for this SceneNode. Will request the current world transform from the parent node to calculate this SceneNode's world transform. For efficiency, this method should cache the result and only trigger a recompute if this SceneNode is dirty (`needsUpdate_ == true`).
const helios::math::mat4f & cachedWorldTransform () const noexcept
Returns the current worldTransform matrix of this SceneNode **without triggering any recomputation**. This method is efficient for access when the world transform is known to be up-to-date.
bool needsUpdate () const noexcept
Checks whether this SceneNode needs to be updated, e.g. because the local transformation changed.
Protected Attributes
helios::math::mat4f projectionMatrix_
The projection matrix of this Camera.
helios::math::mat4f viewMatrix_
The view matrix of this Camera.
Protected Attributes inherited from helios::scene::SceneNode
bool needsUpdate_ = true
Boolean flag to represent the dirty-state of this node. Should be set to false if the current `worldTransform_` for this node was computed, otherwise true, e.g. if the node's local transform has been changed.
std::shared_ptr< const helios::rendering::Renderable > renderable_
A shared pointer to the Renderable this node represents in the SceneGraph. May be nullptr if this node does not represent a renderable object.
SceneNode * parent_ = nullptr
The parent node of **this** node. This will be nullptr for any root node. Implementing APIs must take care of properly assigning parent nodes when adding child nodes.
std::vector< std::unique_ptr< SceneNode > > children_
A list of unique pointers to this node's children. Ensures ownership of the child nodes withing the graph hierarchy.
math::mat4f worldTransform_ = math::mat4f::identity()
The 4x4 worldTransform-Matrix of this node. This matrix is initially set to the identity matrix. Implementing APIs MUST make sure to recompute the worldTransform before each rendering pass.
Transform localTransform_
A local transformation representing affine transformation information for this SceneNode. Encapsulates rotation, scaling and translation.
Additional Inherited Members
Protected Member Functions inherited from helios::scene::SceneNode
void setParent (SceneNode *parentNode)
Sets the parent of this SceneNode. Internally used once a child was added to this SceneNode.
Detailed Description
Represents a camera for perspective or orthographic projection, deriving from SceneNode to allow for spatial positioning and transformation within the scene graph.
The camera provides the view and projection matrix, whereas the view matrix is computed as the inverse of the camera's world transform.
A Camera behaves just like a (non-renderable) SceneNode, except for the fact that it does not accept child nodes.
An instance of `Camera` is added as a direct descendant of the scene's root node for free transform. It can be a child of a model hierarchy to inherit the corresponding positioning in the world.
Todo
implement class. Make sure localTransforms mark this class as dirty, for proper recalculating projection-/viewMatrix if needed.
check whether nodes should further be divided into Parent- and LeafNodes. Cameras would be LeafNodes then, not allowing to have child nodes.
Definition at line 34 of file Camera.ixx.
Constructor & Destructor Documentation
Camera()
helios::scene::Camera::Camera () export
Constructor for this class. Initializes projectionMatrix and viewMatrix with the identity matrix.
Member Function Documentation
addChild()
SceneNode * helios::scene::Camera::addChild (std::unique_ptr< SceneNode > sceneNode) nodiscard override export virtual
This method will do nothing but return `nullptr`, indicating that a `Camera` must not have child nodes.
Parameters
sceneNode The attempted child node to add (ignored).
Returns
This implementation returns `nullptr`.
See also
https://stackoverflow.com/questions/24609872/delete-virtual-function-from-a-derived-class
Reimplemented from helios::scene::SceneNode.
References helios::scene::SceneNode::SceneNode().
projectionMatrix()
const helios::math::mat4f & helios::scene::Camera::projectionMatrix () const nodiscard export noexcept
Returns a constant ref to this camera's current projection matrix. Typically set to the perspective / orthographic projection.
Returns
A const ref to this `Camera`'s projection matrix.
viewMatrix()
const helios::math::mat4f & helios::scene::Camera::viewMatrix () const nodiscard export noexcept
Returns a constant ref to this camera's view matrix. Automatically computed as the inverse of the camera's world transform.
Returns
A const ref to this `Camera`'s view matrix.
References viewMatrix().
Referenced by viewMatrix().
The documentation for this class was generated from the following file:
include/helios/scene/Camera.ixx