helios: helios::engine::game::components::physics::Move2DComponent Class Reference
helios::engine::game::components::physics::Move2DComponent Class Reference export
module helios.engine.game.components.physics.Move2DComponent
Component for 2D physics-based movement with rotation.
Public Member Functions
void move (helios::math::vec2f direction, float throttle)
Sets the movement direction and throttle.
void setCurrentRotationSpeed (float speed) noexcept
Sets the current rotation speed.
void setVelocity (helios::math::vec3f velocity) noexcept
Sets the current velocity vector.
float currentRotationSpeed () const noexcept
Returns the current rotation speed.
float rotationAngleDelta () const noexcept
Returns the angular distance to the target rotation.
float currentMovementSpeed () const noexcept
Returns the current movement speed.
float currentRotationAngle () const noexcept
Returns the current rotation angle.
float targetRotationAngle () const noexcept
Returns the target rotation angle.
void setCurrentRotationAngle (float angle) noexcept
Sets the current rotation angle.
void setRotationAngleDelta (float delta) noexcept
Sets the angular distance to the target rotation.
void setCurrentMovementSpeed (float speed) noexcept
Sets the current movement speed.
bool isInputActive () const noexcept
Checks if input is currently active.
const helios::math::vec2f & steeringInput () const noexcept
Returns the current steering input direction.
float throttle () const noexcept
Returns the current throttle value (0.0 to 1.0).
const helios::math::vec3f & velocity () const noexcept
Returns the current velocity vector.
float speedRatio () const noexcept
Returns the current speed as a ratio of maximum speed.
float rotationSpeed () const noexcept
Returns the maximum rotation speed in degrees per second.
float movementSpeedThreshold () const noexcept
Returns the minimum movement speed threshold.
float rotationSpeedThreshold () const noexcept
Returns the minimum rotation speed threshold.
float movementAcceleration () const noexcept
Returns the movement acceleration in units per second squared.
float movementSpeed () const noexcept
Returns the maximum movement speed in units per second.
float rotationDampening () const noexcept
Returns the rotation dampening factor.
float movementDampening () const noexcept
Returns the movement dampening factor.
void setRotationSpeed (float value) noexcept
Sets the maximum rotation speed in degrees per second.
void setMovementSpeedThreshold (float value) noexcept
Sets the minimum movement speed threshold.
void setRotationSpeedThreshold (float value) noexcept
Sets the minimum rotation speed threshold.
void setMovementAcceleration (float value) noexcept
Sets the movement acceleration in units per second squared.
void setMovementSpeed (float value) noexcept
Sets the maximum movement speed in units per second.
void setRotationDampening (float value) noexcept
Sets the rotation dampening factor.
void setMovementDampening (float value) noexcept
Sets the movement dampening factor.
void resetToDefaults () noexcept
Resets all physics parameters to their default values.
Public Member Functions inherited from helios::engine::game::Component
virtual ~Component ()=default
Component ()=default
virtual void onAttach (GameObject *gameObject) noexcept
Called when the component is attached to a GameObject.
GameObject * gameObject () const noexcept
Returns the owning GameObject.
Protected Attributes
float rotationSpeed_ = DEFAULT_ROTATION_SPEED
Maximum rotation speed in degrees per second.
float movementSpeedThreshold_ = DEFAULT_MOVEMENT_SPEED_THRESHOLD
Minimum movement speed before the ship stops completely.
float rotationSpeedThreshold_ = DEFAULT_ROTATION_SPEED_THRESHOLD
Minimum rotation speed before rotation stops completely.
float movementAcceleration_ = DEFAULT_MOVEMENT_ACCELERATION
Movement acceleration in units per second squared.
float movementSpeed_ = DEFAULT_MOVEMENT_SPEED
Base movement speed in units per second.
float rotationDampening_ = DEFAULT_ROTATION_DAMPENING
Exponential decay factor for rotation when input stops.
float movementDampening_ = DEFAULT_MOVEMENT_DAMPENING
Exponential decay factor for movement when input stops.
float baseRotationSpeedMultiplier_ = DEFAULT_BASE_ROTATION_SPEED_MULTIPLIER
Base rotation speed multiplier.
float currentMovementSpeed_ = 0.0f
Current movement speed after applying input and dampening.
float currentRotationAngle_ = 0
Current rotation angle in degrees.
float targetRotationAngle_ = 0
Target rotation angle derived from input direction.
float rotationAngleDelta_ = 0
Shortest angular distance to target rotation.
float currentRotationSpeed_ = 0.0f
Current rotation speed after applying input and dampening.
bool isInputActive_ = true
Indicates whether input is currently being received.
float throttle_ = 0.0f
Current throttle value from input (0.0 to 1.0).
helios::math::vec2f steeringInput_
Current steering input as 2D direction vector.
helios::math::vec3f velocity_
Current velocity vector in world space.
Protected Attributes inherited from helios::engine::game::Component
GameObject * gameObject_ = nullptr
Non-owning pointer to the owning GameObject.
Static Protected Attributes
static constexpr float DEFAULT_ROTATION_SPEED = 560.0f
Default maximum rotation speed in degrees per second.
static constexpr float DEFAULT_MOVEMENT_SPEED_THRESHOLD = 0.1f
Default minimum movement speed before the ship stops completely.
static constexpr float DEFAULT_ROTATION_SPEED_THRESHOLD = 0.1f
Default minimum rotation speed before rotation stops completely.
static constexpr float DEFAULT_MOVEMENT_ACCELERATION = 30.0f
Default movement acceleration in units per second squared.
static constexpr float DEFAULT_MOVEMENT_SPEED = 30.0f
Default base movement speed in units per second.
static constexpr float DEFAULT_ROTATION_DAMPENING = 0.0001f
Default exponential decay factor for rotation when input stops.
static constexpr float DEFAULT_MOVEMENT_DAMPENING = 0.1f
Default exponential decay factor for movement when input stops.
static constexpr float DEFAULT_BASE_ROTATION_SPEED_MULTIPLIER = 16.0f
Default base rotation speed multiplier.
Detailed Description
Component for 2D physics-based movement with rotation.
Stores configuration and runtime state for 2D physics-based movement. This component is used by the movement system to apply smooth acceleration, deceleration, and rotation to the entity.
The component receives input via move() which sets target direction and throttle. The actual physics simulation (integration of velocity, application of dampening) is performed by the Movement2DSystem.
Definition at line 38 of file Move2DComponent.ixx.
Member Function Documentation
currentMovementSpeed()
float helios::engine::game::components::physics::Move2DComponent::currentMovementSpeed () const inline nodiscard export noexcept
Returns the current movement speed.
Returns
The current movement speed.
Definition at line 261 of file Move2DComponent.ixx.
References currentMovementSpeed_.
currentRotationAngle()
float helios::engine::game::components::physics::Move2DComponent::currentRotationAngle () const inline nodiscard export noexcept
Returns the current rotation angle.
Returns
The current rotation angle in degrees.
Definition at line 270 of file Move2DComponent.ixx.
References currentRotationAngle_.
currentRotationSpeed()
float helios::engine::game::components::physics::Move2DComponent::currentRotationSpeed () const inline nodiscard export noexcept
Returns the current rotation speed.
Returns
The current rotation speed.
Definition at line 243 of file Move2DComponent.ixx.
References currentRotationSpeed_.
isInputActive()
bool helios::engine::game::components::physics::Move2DComponent::isInputActive () const inline nodiscard export noexcept
Checks if input is currently active.
Returns
True if input is active, false otherwise.
Definition at line 315 of file Move2DComponent.ixx.
References isInputActive_.
move()
void helios::engine::game::components::physics::Move2DComponent::move (helios::math::vec2f direction, float throttle) inline export
Sets the movement direction and throttle.
Updates the target rotation angle based on the input direction and calculates the shortest angular distance to the target.
Parameters
direction Normalized 2D direction vector from analog stick.
throttle Magnitude of the stick input (0.0 to 1.0).
Definition at line 193 of file Move2DComponent.ixx.
References currentMovementSpeed_, currentRotationAngle_, currentRotationSpeed_, helios::math::degrees(), helios::math::EPSILON_LENGTH, isInputActive_, helios::math::vec2< T >::length(), movementSpeed_, rotationAngleDelta_, rotationSpeed_, steeringInput_, targetRotationAngle_, throttle(), and throttle_.
movementAcceleration()
float helios::engine::game::components::physics::Move2DComponent::movementAcceleration () const inline nodiscard export noexcept
Returns the movement acceleration in units per second squared.
Returns
Movement acceleration value.
Definition at line 389 of file Move2DComponent.ixx.
References movementAcceleration_.
movementDampening()
float helios::engine::game::components::physics::Move2DComponent::movementDampening () const inline nodiscard export noexcept
Returns the movement dampening factor.
Returns
Exponential decay factor for movement.
Definition at line 410 of file Move2DComponent.ixx.
References movementDampening_.
movementSpeed()
float helios::engine::game::components::physics::Move2DComponent::movementSpeed () const inline nodiscard export noexcept
Returns the maximum movement speed in units per second.
Returns
Maximum movement speed value.
Definition at line 396 of file Move2DComponent.ixx.
References movementSpeed_.
movementSpeedThreshold()
float helios::engine::game::components::physics::Move2DComponent::movementSpeedThreshold () const inline nodiscard export noexcept
Returns the minimum movement speed threshold.
Returns
Movement speed threshold below which movement stops.
Definition at line 375 of file Move2DComponent.ixx.
References movementSpeedThreshold_.
resetToDefaults()
void helios::engine::game::components::physics::Move2DComponent::resetToDefaults () inline export noexcept
Resets all physics parameters to their default values.
Definition at line 473 of file Move2DComponent.ixx.
References DEFAULT_MOVEMENT_ACCELERATION, DEFAULT_MOVEMENT_DAMPENING, DEFAULT_MOVEMENT_SPEED, DEFAULT_MOVEMENT_SPEED_THRESHOLD, DEFAULT_ROTATION_DAMPENING, DEFAULT_ROTATION_SPEED, DEFAULT_ROTATION_SPEED_THRESHOLD, movementAcceleration_, movementDampening_, movementSpeed_, movementSpeedThreshold_, rotationDampening_, rotationSpeed_, and rotationSpeedThreshold_.
rotationAngleDelta()
float helios::engine::game::components::physics::Move2DComponent::rotationAngleDelta () const inline nodiscard export noexcept
Returns the angular distance to the target rotation.
Returns
The angle delta in degrees.
Definition at line 252 of file Move2DComponent.ixx.
References rotationAngleDelta_.
rotationDampening()
float helios::engine::game::components::physics::Move2DComponent::rotationDampening () const inline nodiscard export noexcept
Returns the rotation dampening factor.
Returns
Exponential decay factor for rotation.
Definition at line 403 of file Move2DComponent.ixx.
References rotationDampening_.
rotationSpeed()
float helios::engine::game::components::physics::Move2DComponent::rotationSpeed () const inline nodiscard export noexcept
Returns the maximum rotation speed in degrees per second.
Returns
Maximum rotation speed value.
Definition at line 368 of file Move2DComponent.ixx.
References rotationSpeed_.
rotationSpeedThreshold()
float helios::engine::game::components::physics::Move2DComponent::rotationSpeedThreshold () const inline nodiscard export noexcept
Returns the minimum rotation speed threshold.
Returns
Rotation speed threshold below which rotation stops.
Definition at line 382 of file Move2DComponent.ixx.
References rotationSpeedThreshold_.
setCurrentMovementSpeed()
void helios::engine::game::components::physics::Move2DComponent::setCurrentMovementSpeed (float speed) inline export noexcept
Sets the current movement speed.
Parameters
speed The new movement speed.
Definition at line 306 of file Move2DComponent.ixx.
References currentMovementSpeed_.
setCurrentRotationAngle()
void helios::engine::game::components::physics::Move2DComponent::setCurrentRotationAngle (float angle) inline export noexcept
Sets the current rotation angle.
Parameters
angle The new rotation angle in degrees.
Definition at line 288 of file Move2DComponent.ixx.
References currentRotationAngle_.
setCurrentRotationSpeed()
void helios::engine::game::components::physics::Move2DComponent::setCurrentRotationSpeed (float speed) inline export noexcept
Sets the current rotation speed.
Parameters
speed The new rotation speed.
Definition at line 224 of file Move2DComponent.ixx.
References currentRotationSpeed_.
setMovementAcceleration()
void helios::engine::game::components::physics::Move2DComponent::setMovementAcceleration (float value) inline export noexcept
Sets the movement acceleration in units per second squared.
Parameters
value New acceleration value.
Definition at line 443 of file Move2DComponent.ixx.
References movementAcceleration_.
setMovementDampening()
void helios::engine::game::components::physics::Move2DComponent::setMovementDampening (float value) inline export noexcept
Sets the movement dampening factor.
Parameters
value New dampening factor (exponential decay).
Definition at line 464 of file Move2DComponent.ixx.
References movementDampening_.
setMovementSpeed()
void helios::engine::game::components::physics::Move2DComponent::setMovementSpeed (float value) inline export noexcept
Sets the maximum movement speed in units per second.
Parameters
value New maximum speed value.
Definition at line 450 of file Move2DComponent.ixx.
References movementSpeed_.
setMovementSpeedThreshold()
void helios::engine::game::components::physics::Move2DComponent::setMovementSpeedThreshold (float value) inline export noexcept
Sets the minimum movement speed threshold.
Parameters
value New threshold value.
Definition at line 429 of file Move2DComponent.ixx.
References movementSpeedThreshold_.
setRotationAngleDelta()
void helios::engine::game::components::physics::Move2DComponent::setRotationAngleDelta (float delta) inline export noexcept
Sets the angular distance to the target rotation.
Parameters
delta The new angle delta in degrees.
Definition at line 297 of file Move2DComponent.ixx.
References rotationAngleDelta_.
setRotationDampening()
void helios::engine::game::components::physics::Move2DComponent::setRotationDampening (float value) inline export noexcept
Sets the rotation dampening factor.
Parameters
value New dampening factor (exponential decay).
Definition at line 457 of file Move2DComponent.ixx.
References rotationDampening_.
setRotationSpeed()
void helios::engine::game::components::physics::Move2DComponent::setRotationSpeed (float value) inline export noexcept
Sets the maximum rotation speed in degrees per second.
Parameters
value New rotation speed value.
Definition at line 422 of file Move2DComponent.ixx.
References rotationSpeed_.
setRotationSpeedThreshold()
void helios::engine::game::components::physics::Move2DComponent::setRotationSpeedThreshold (float value) inline export noexcept
Sets the minimum rotation speed threshold.
Parameters
value New threshold value.
Definition at line 436 of file Move2DComponent.ixx.
References rotationSpeedThreshold_.
setVelocity()
void helios::engine::game::components::physics::Move2DComponent::setVelocity (helios::math::vec3f velocity) inline export noexcept
Sets the current velocity vector.
Parameters
velocity The new velocity vector.
Definition at line 233 of file Move2DComponent.ixx.
References velocity(), and velocity_.
speedRatio()
float helios::engine::game::components::physics::Move2DComponent::speedRatio () const inline nodiscard export noexcept
Returns the current speed as a ratio of maximum speed.
Returns
A value between 0.0 (stationary) and 1.0 (maximum speed).
Definition at line 351 of file Move2DComponent.ixx.
References helios::math::EPSILON_LENGTH, movementSpeed_, and velocity_.
steeringInput()
const helios::math::vec2f & helios::engine::game::components::physics::Move2DComponent::steeringInput () const inline nodiscard export noexcept
Returns the current steering input direction.
Returns
Const reference to the 2D steering input vector.
Definition at line 324 of file Move2DComponent.ixx.
References steeringInput_.
targetRotationAngle()
float helios::engine::game::components::physics::Move2DComponent::targetRotationAngle () const inline nodiscard export noexcept
Returns the target rotation angle.
Returns
The target rotation angle in degrees.
Definition at line 279 of file Move2DComponent.ixx.
References targetRotationAngle_.
throttle()
float helios::engine::game::components::physics::Move2DComponent::throttle () const inline nodiscard export noexcept
Returns the current throttle value (0.0 to 1.0).
Returns
Current throttle magnitude from input.
Definition at line 333 of file Move2DComponent.ixx.
References throttle_.
Referenced by move().
velocity()
const helios::math::vec3f & helios::engine::game::components::physics::Move2DComponent::velocity () const inline nodiscard export noexcept
Returns the current velocity vector.
Returns
Const reference to the 3D velocity vector in world space.
Definition at line 342 of file Move2DComponent.ixx.
References velocity_.
Referenced by setVelocity().
The documentation for this class was generated from the following file:
include/helios/engine/game/components/physics/Move2DComponent.ixx