helios: helios::util::log::Logger Class Reference
helios::util::log::Logger Class Reference export
module helios.util.log.Logger
Logger implementation with configurable output sinks.
Public Member Functions
Logger (std::string scope)
Creates a new Logger, tagged with a specific scope.
void enable (bool enable) noexcept
Enables or disables log output for this Logger instance.
void addSink (std::shared_ptr< LogSink > sink)
Adds an output sink to this logger.
void clearSinks () noexcept
Removes all sinks from this logger.
size_t sinkCount () const noexcept
Returns the number of attached sinks.
void warn (const std::string &msg) const noexcept
Writes a warning message if logging is enabled.
void debug (const std::string &msg) const noexcept
Writes a debug message if logging is enabled.
void info (const std::string &msg) const noexcept
Writes an info message if logging is enabled.
void error (const std::string &msg) const noexcept
Writes an error message if logging is enabled.
Detailed Description
Logger implementation with configurable output sinks.
This logger supports multiple output destinations through LogSink instances. By default, it writes to stdout, but sinks can be added or replaced to redirect output to ImGui widgets, files, or other destinations.
```cpp // Add ImGui sink while keeping console output logger.addSink(imguiSink);
// Replace all sinks (ImGui only) logger.clearSinks(); logger.addSink(imguiSink); ```
Definition at line 34 of file Logger.ixx.
Constructor & Destructor Documentation
Logger()
helios::util::log::Logger::Logger (std::string scope) explicit export
Creates a new Logger, tagged with a specific scope.
Parameters
scope The textual scope used as a prefix in log output (e.g. "helios::rendering").
Member Function Documentation
addSink()
void helios::util::log::Logger::addSink (std::shared_ptr< LogSink > sink) export
Adds an output sink to this logger.
Parameters
sink Shared pointer to the sink to add.
clearSinks()
void helios::util::log::Logger::clearSinks () export noexcept
Removes all sinks from this logger.
debug()
void helios::util::log::Logger::debug (const std::string & msg) const export noexcept
Writes a debug message if logging is enabled.
Parameters
msg The message to write.
References debug().
Referenced by debug().
enable()
void helios::util::log::Logger::enable (bool enable) export noexcept
Enables or disables log output for this Logger instance.
Parameters
enable true to enable output, false to disable it.
References enable().
Referenced by enable().
error()
void helios::util::log::Logger::error (const std::string & msg) const export noexcept
Writes an error message if logging is enabled.
Parameters
msg The message to write.
References error().
Referenced by error().
info()
void helios::util::log::Logger::info (const std::string & msg) const export noexcept
Writes an info message if logging is enabled.
Parameters
msg The message to write.
References info().
Referenced by info().
sinkCount()
size_t helios::util::log::Logger::sinkCount () const nodiscard export noexcept
Returns the number of attached sinks.
Returns
The number of sinks currently attached to this logger.
References sinkCount().
Referenced by sinkCount().
warn()
void helios::util::log::Logger::warn (const std::string & msg) const export noexcept
Writes a warning message if logging is enabled.
Parameters
msg The message to write.
References warn().
Referenced by warn().
The documentation for this class was generated from the following file:
include/helios/util/log/Logger.ixx