helios: helios::ext::glfw::window::GLFWWindow Class Reference
helios::ext::glfw::window::GLFWWindow Class Reference export
module helios.ext.glfw.window.GLFWWindow
An OpenGL focused window implementation using GLFW.
Public Member Functions
GLFWWindow (const GLFWWindow &)=delete
Do not copy instances of GLFWWindow.
GLFWWindow & operator= (const GLFWWindow &)=delete
~GLFWWindow () override
Destructor. Delegates to destroy().
GLFWWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const GLFWWindowConfig &cfg)
Constructs a new GLFWWindow based in the provided configuration. The underlying native window is not created until show() is called.
bool show () noexcept override
Creates and displays the underlying native `GlFWwindow`.
void swapBuffers () const noexcept override
Swaps the front and back buffers of the window.
void pollEvents () const noexcept override
Processes all events in the underlying Window's EventQueue.
void setShouldClose (bool close) override
Sets the close flag of this window.
bool shouldClose () const override
Checks if the window has received a close request.
GLFWframebuffersizefun frameBufferSizeCallback () const noexcept
Returns the framebuffer resize callback function.
void setFrameBufferSizeCallback (GLFWframebuffersizefun framebufferSizeCallback) noexcept
Sets the callback function for framebuffer resize events.
GLFWwindow * nativeHandle () const noexcept
Returns the raw native GLFWwindow handle.
void destroy () const
Removed the underlying native handle of the GLFWwindow.
void setWindowUserPointer (std::unique_ptr< GLFWWindowUserPointer > windowUserPointer) noexcept
Sets the user-defined pointer for his GLFWWindow.
const GLFWWindowUserPointer & windowUserPointer () const noexcept
Returns a const reference to the `GLFWWindowUserPointer` managed by this class.
Public Member Functions inherited from helios::window::Window
virtual ~Window ()=default
Window (const Window &)=delete
Window & operator= (const Window &)=delete
Window (Window &&) noexcept=default
Window & operator= (Window &&) noexcept=default
Window (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const WindowConfig &cfg)
Constructs a new Window based on the provided configuration.
const util::Guid & guid () const noexcept
Returns the unique guid for this window instance.
int width () const noexcept
Returns the current width of this window.
int height () const noexcept
Returns the current height of this window.
helios::rendering::RenderTarget & renderTarget () const noexcept
Returns the RenderTarget associated with this Window.
std::shared_ptr< helios::rendering::Viewport > addViewport (std::shared_ptr< helios::rendering::Viewport > viewport) const
Adds the viewport to the underlying RenderTarget of this Window.
virtual bool operator== (const Window &win) const noexcept
Compares two window instances for equality.
Additional Inherited Members
Protected Attributes inherited from helios::window::Window
int width_
The current width of the window.
int height_
The current height of the window.
std::string title_
The title of the window.
int aspectRatioNumer_ = 0
Aspect ratio numerator.
int aspectRatioDenom_ = 0
Aspect ratio denominator.
std::unique_ptr< helios::rendering::RenderTarget > renderTarget_
The default render target for this Window. The default RenderTarget represents the default framebuffer, e.g. the "0" FBO in OpenGL.
Static Protected Attributes inherited from helios::window::Window
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
The logger used with this Window instance.
Detailed Description
An OpenGL focused window implementation using GLFW.
This class manages a `GLFWwindow` handle, providing methods for creation, display, event polling and resource cleanup.
Todo
add glfwSetWindowRefreshCallback
Definition at line 29 of file GLFWWindow.ixx.
Constructor & Destructor Documentation
GLFWWindow() [1/2]
helios::ext::glfw::window::GLFWWindow::GLFWWindow (const GLFWWindow &) export delete
Do not copy instances of GLFWWindow.
References GLFWWindow().
Referenced by GLFWWindow(), and operator=().
~GLFWWindow()
helios::ext::glfw::window::GLFWWindow::~GLFWWindow () override export
Destructor. Delegates to destroy().
GLFWWindow() [2/2]
helios::ext::glfw::window::GLFWWindow::GLFWWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const GLFWWindowConfig & cfg) explicit export
Constructs a new GLFWWindow based in the provided configuration. The underlying native window is not created until show() is called.
Parameters
cfg A const ref to this window's configuration-
References helios::window::Window::renderTarget().
Member Function Documentation
destroy()
void helios::ext::glfw::window::GLFWWindow::destroy () const export
Removed the underlying native handle of the GLFWwindow.
See also
https://www.glfw.org/docs/latest/group__window.html#gacdf43e51376051d2c091662e9fe3d7b2
References destroy().
Referenced by destroy().
frameBufferSizeCallback()
GLFWframebuffersizefun helios::ext::glfw::window::GLFWWindow::frameBufferSizeCallback () const nodiscard export noexcept
Returns the framebuffer resize callback function.
Returns
the `GLFWframebuffersizefun` currently registered with this Window.
References frameBufferSizeCallback().
Referenced by frameBufferSizeCallback().
nativeHandle()
GLFWwindow * helios::ext::glfw::window::GLFWWindow::nativeHandle () const nodiscard export noexcept
Returns the raw native GLFWwindow handle.
This method should only be used in GLFW-related API parts, where underlying glfw-functions require the native window handle.
Returns
The `GLFWwindow*` handle, or a `nullptr` if not available.
References nativeHandle().
Referenced by nativeHandle().
operator=()
GLFWWindow & helios::ext::glfw::window::GLFWWindow::operator= (const GLFWWindow &) export delete
References GLFWWindow().
pollEvents()
void helios::ext::glfw::window::GLFWWindow::pollEvents () const override export virtual noexcept
Processes all events in the underlying Window's EventQueue.
This method should be called regularly in the main loop.
See also
https://www.glfw.org/docs/latest/group__window.html#ga37bd57223967b4211d60ca1a0bf3c832
Implements helios::window::Window.
References pollEvents().
Referenced by pollEvents().
setFrameBufferSizeCallback()
void helios::ext::glfw::window::GLFWWindow::setFrameBufferSizeCallback (GLFWframebuffersizefun framebufferSizeCallback) export noexcept
Sets the callback function for framebuffer resize events.
Implementing APIs should consider this method as "package protected": It's purpose is to register a function that delegates the native event into the Application's EventQueue.
Parameters
framebufferSizeCallback The `GLFWframebuffersizefun` to set.
References setFrameBufferSizeCallback().
Referenced by setFrameBufferSizeCallback().
setShouldClose()
void helios::ext::glfw::window::GLFWWindow::setShouldClose (bool close) override export virtual
Sets the close flag of this window.
Parameters
close True to indicate this window should be closed, false otherwise.
See also
shouldClose()
https://www.glfw.org/docs/latest/group__window.html#ga49c449dde2a6f87d996f4daaa09d6708
Implements helios::window::Window.
References setShouldClose().
Referenced by setShouldClose().
setWindowUserPointer()
void helios::ext::glfw::window::GLFWWindow::setWindowUserPointer (std::unique_ptr< GLFWWindowUserPointer > windowUserPointer) export noexcept
Sets the user-defined pointer for his GLFWWindow.
This transfers ownership of the `GLFWWindowUserPointer`-object to this Window and additionally associates its raw pointer with this Window's native handle.
Parameters
windowUserPointer A unique_ptr to the `GLFWWindowUserPointer` object. Ownership is transferred to this Window-instance.
Returns
References setWindowUserPointer(), and windowUserPointer().
Referenced by setWindowUserPointer().
shouldClose()
bool helios::ext::glfw::window::GLFWWindow::shouldClose () const nodiscard override export virtual
Checks if the window has received a close request.
Implementing APIs should consider this flag at regular intervals (e.g. each frame) to determine whether this window should be closed.
Returns
true if the window should be closed, otherwise false.
See also
setShouldClose()
https://www.glfw.org/docs/latest/group__window.html#ga24e02fbfefbb81fc45320989f8140ab5
Implements helios::window::Window.
References shouldClose().
Referenced by shouldClose().
show()
bool helios::ext::glfw::window::GLFWWindow::show () override export virtual noexcept
Creates and displays the underlying native `GlFWwindow`.
This method initializes the native window. It does not set the current context, which is actually done by GLFWApplication::setCurrent().
See also
https://www.glfw.org/docs/latest/group__window.html#ga3555a418df92ad53f917597fe2f64aeb
Implements helios::window::Window.
swapBuffers()
void helios::ext::glfw::window::GLFWWindow::swapBuffers () const override export virtual noexcept
Swaps the front and back buffers of the window.
See also
https://www.glfw.org/docs/latest/group__window.html#ga15a5a1ee5b3c2ca6b15ca209a12efd14
Implements helios::window::Window.
References swapBuffers().
Referenced by swapBuffers().
windowUserPointer()
const GLFWWindowUserPointer & helios::ext::glfw::window::GLFWWindow::windowUserPointer () const nodiscard export noexcept
Returns a const reference to the `GLFWWindowUserPointer` managed by this class.
Returns
A const reference to this object's `GLFWWindowUserPointer`.
References windowUserPointer().
Referenced by setWindowUserPointer(), and windowUserPointer().
The documentation for this class was generated from the following file:
include/ext/glfw/window/GLFWWindow.ixx