helios: helios::engine::game::System Class Reference
helios::engine::game::System Class Reference abstract export
module helios.engine.game.System
Abstract base class for game systems.
Public Member Functions
virtual ~System ()=default
Virtual destructor for proper cleanup of derived systems.
virtual void onAdd (helios::engine::game::GameWorld *gameWorld) noexcept
Called when the system is added to a GameWorld.
void update (helios::engine::game::UpdateContext &updateContext) noexcept override=0
Updates the system each frame.
Public Member Functions inherited from helios::engine::game::Updatable
virtual ~Updatable ()=default
Updatable ()=default
Protected Attributes
helios::engine::game::GameWorld * gameWorld_ = nullptr
Pointer to the GameWorld this system belongs to.
Detailed Description
Abstract base class for game systems.
Systems are global game logic processors that operate on the GameWorld rather than individual GameObjects, ideal for cross-cutting concerns like physics simulation, collision detection, or object pooling.
Systems are added to a GameWorld and receive update calls each frame. The `onAdd()` callback provides access to the GameWorld for initialization.
Example usage: ```cpp class PhysicsSystem : public System { public: void update(UpdateContext& ctx) noexcept override { // Apply physics to all rigid bodies } };
gameWorld.addSystem(std::make_unique<PhysicsSystem>()); ```
Definition at line 38 of file System.ixx.
Constructor & Destructor Documentation
~System()
virtual helios::engine::game::System::~System () export virtual default
Virtual destructor for proper cleanup of derived systems.
Member Function Documentation
onAdd()
virtual void helios::engine::game::System::onAdd (helios::engine::game::GameWorld * gameWorld) inline export virtual noexcept
Called when the system is added to a GameWorld.
Override this method to perform initialization that requires access to the GameWorld (e.g., querying the scene graph, registering event handlers).
Parameters
gameWorld The GameWorld this system is being added to.
Reimplemented in helios::engine::game::systems::gameplay::ProjectilePoolSystem, helios::engine::game::systems::physics::Move2DSystem, and helios::engine::game::systems::physics::ScaleSystem.
Definition at line 66 of file System.ixx.
References gameWorld_.
Referenced by helios::engine::game::systems::gameplay::ProjectilePoolSystem::onAdd(), helios::engine::game::systems::physics::Move2DSystem::onAdd(), and helios::engine::game::systems::physics::ScaleSystem::onAdd().
update()
void helios::engine::game::System::update (helios::engine::game::UpdateContext & updateContext) override export pure virtual noexcept
Updates the system each frame.
Parameters
updateContext The update context containing frame timing information.
Implements helios::engine::game::Updatable.
Implemented in helios::engine::game::systems::gameplay::ProjectilePoolSystem, helios::engine::game::systems::physics::BoundsUpdateSystem, helios::engine::game::systems::physics::LevelBoundsBehaviorSystem, helios::engine::game::systems::physics::Move2DSystem, helios::engine::game::systems::physics::ScaleSystem, helios::engine::game::systems::post::ScaleClearSystem, helios::engine::game::systems::post::TransformClearSystem, and helios::engine::game::systems::scene::SceneSyncSystem.
The documentation for this class was generated from the following file:
include/helios/engine/game/System.ixx