helios: helios::engine::game::systems::gameplay::ProjectilePoolSystem Class Reference
helios::engine::game::systems::gameplay::ProjectilePoolSystem Class Reference export
module helios.engine.game.systems.gameplay.ProjectilePoolSystem
Object pool system for efficient projectile spawning and lifecycle management.
Classes
struct ProjectileObject
Internal representation of an active projectile.
Public Member Functions
ProjectilePoolSystem (std::shared_ptr< helios::rendering::Renderable > projectileRenderable, unsigned int poolSize)
Constructs a ProjectilePoolSystem with a shared renderable and pool size.
void onAdd (helios::engine::game::GameWorld *gameWorld) noexcept override
Called when the system is added to a GameWorld.
bool prepareProjectiles ()
void spawn (helios::math::vec3f position, helios::math::vec3f muzzleVelocity, helios::math::vec3f aimDir, helios::math::vec3f sourceVelocity) noexcept
Spawns a projectile from the pool at the given position with muzzleVelocity.
void despawn (unsigned int idx)
Despawns the projectile at the specified index.
void update (helios::engine::game::UpdateContext &updateContext) noexcept override
Updates all active projectiles each frame.
Public Member Functions inherited from helios::engine::game::System
virtual ~System ()=default
Virtual destructor for proper cleanup of derived systems.
Public Member Functions inherited from helios::engine::game::Updatable
virtual ~Updatable ()=default
Updatable ()=default
Protected Attributes
std::vector< std::unique_ptr< ProjectileObject > > activeProjectiles_
Collection of currently active projectiles in the scene.
std::vector< std::unique_ptr< ProjectileObject > > pool_
Pool of inactive projectiles available for spawning.
std::shared_ptr< helios::rendering::Renderable > projectileRenderable_
Shared renderable used for all projectile instances.
helios::math::aabbf projectileAABB_ {}
The aabb of the projectile, cached.
float intensity_ = 0.0f
Current frequency factor (0.0 to 1.0) for fire rate control.
helios::engine::game::components::gameplay::Aim2DComponent * aimComponent_ = nullptr
Optional reference to an aim component for direction.
helios::engine::game::components::scene::SceneNodeComponent * sceneNodeComponent_ = nullptr
Optional reference to a scene node component for spawn position.
helios::scene::SceneNode * rootNode_ = nullptr
Root node of the scene graph where projectiles are attached.
unsigned int poolSize_ = 0
Maximum number of projectiles in the pool.
std::shared_ptr< helios::rendering::RenderPrototype > projectilePrototype_ = nullptr
Prototype for creating projectile render instances.
bool projectilesInitialized_ = false
float sourceVelocityInheritFactor_ = 0.5f
Protected Attributes inherited from helios::engine::game::System
helios::engine::game::GameWorld * gameWorld_ = nullptr
Pointer to the GameWorld this system belongs to.
Detailed Description
Object pool system for efficient projectile spawning and lifecycle management.
This system pre-allocates a fixed number of projectile objects to avoid runtime allocations during gameplay. Projectiles are spawned from the pool and returned when they are no longer active. Each projectile is represented as a `SceneNode` attached to the scene graph root.
The pool pattern ensures consistent performance in scenarios with high projectile throughput (e.g., twin-stick shooters, projectile-hell games).
Note
To further reduce the number of draw calls, instancing should be considered.
Example usage: ```cpp auto projectileRenderable = createProjectileRenderable(); auto pool = std::make_unique<ProjectilePoolSystem>(projectileRenderable, 100); gameWorld.addSystem(std::move(pool));
// During gameplay pool->spawn(playerPosition, aimDirection * projectileSpeed); ```
Definition at line 61 of file ProjectilePoolSystem.ixx.
Constructor & Destructor Documentation
ProjectilePoolSystem()
helios::engine::game::systems::gameplay::ProjectilePoolSystem::ProjectilePoolSystem (std::shared_ptr< helios::rendering::Renderable > projectileRenderable, unsigned int poolSize) inline explicit export
Constructs a ProjectilePoolSystem with a shared renderable and pool size.
Parameters
projectileRenderable The renderable to use for all projectile instances.
poolSize Maximum number of projectiles to pre-allocate.
arenaBox The aabb in which the projectiles can spawn.
Definition at line 146 of file ProjectilePoolSystem.ixx.
References activeProjectiles_, pool_, poolSize_, and projectileRenderable_.
Member Function Documentation
despawn()
void helios::engine::game::systems::gameplay::ProjectilePoolSystem::despawn (unsigned int idx) inline export
Despawns the projectile at the specified index.
Moves the projectile from the active list to the inactive pool and deactivates its SceneNode so it is no longer rendered.
Parameters
idx Index of the projectile in the activeProjectiles_ vector.
Definition at line 275 of file ProjectilePoolSystem.ixx.
References activeProjectiles_, and pool_.
Referenced by update().
onAdd()
void helios::engine::game::systems::gameplay::ProjectilePoolSystem::onAdd (helios::engine::game::GameWorld * gameWorld) inline override export virtual noexcept
Called when the system is added to a GameWorld.
Initializes the scene root reference and creates SceneNodes for all pooled projectiles, attaching them to the scene graph.
Parameters
gameWorld The GameWorld this system is added to.
Reimplemented from helios::engine::game::System.
Definition at line 172 of file ProjectilePoolSystem.ixx.
References helios::engine::game::System::gameWorld_, helios::engine::game::System::onAdd(), and prepareProjectiles().
prepareProjectiles()
bool helios::engine::game::systems::gameplay::ProjectilePoolSystem::prepareProjectiles () inline nodiscard export
Definition at line 182 of file ProjectilePoolSystem.ixx.
References helios::scene::SceneNode::aabb(), helios::engine::game::System::gameWorld_, pool_, projectileAABB_, projectileRenderable_, projectilesInitialized_, and rootNode_.
Referenced by onAdd(), and spawn().
spawn()
void helios::engine::game::systems::gameplay::ProjectilePoolSystem::spawn (helios::math::vec3f position, helios::math::vec3f muzzleVelocity, helios::math::vec3f aimDir, helios::math::vec3f sourceVelocity) inline export noexcept
Spawns a projectile from the pool at the given position with muzzleVelocity.
If the pool is empty, the spawn request is silently ignored. The projectile is moved from the inactive pool to the active projectiles list.
Parameters
position World-space spawn position.
muzzleVelocity Initial muzzleVelocity vector for the projectile.
aimDir The normalized aim direction vector.
sourceVelocity The velocity of the emitting object.
Todo
the ProjectilePoolSystem assumes to shoot in 2d, projected on the xy plane. This has to be configured later on.
we simply create a rotation matrix that rotates about the z-axis: cos A -sin A 0 0 sin A cos A 0 0 0 0 1 0 0 0 0 1
Since aimDir is normalized, we benefit from cos A = aimDir[0], sin A = aimDir[1].
Definition at line 218 of file ProjectilePoolSystem.ixx.
References activeProjectiles_, pool_, prepareProjectiles(), and sourceVelocityInheritFactor_.
Referenced by helios::engine::game::components::gameplay::ShootComponent::update().
update()
void helios::engine::game::systems::gameplay::ProjectilePoolSystem::update (helios::engine::game::UpdateContext & updateContext) inline override export virtual noexcept
Updates all active projectiles each frame.
Moves each active projectile according to its muzzleVelocity scaled by delta time.
Note
update uses the cached projectileAABB_ to check whether the projectile should despawn.
Parameters
updateContext The update context containing frame timing information.
Implements helios::engine::game::System.
Definition at line 294 of file ProjectilePoolSystem.ixx.
References activeProjectiles_, despawn(), helios::engine::game::System::gameWorld_, and projectileAABB_.
The documentation for this class was generated from the following file:
include/helios/engine/game/systems/gameplay/ProjectilePoolSystem.ixx