helios: helios::scene::CameraSceneNode Class Reference
helios::scene::CameraSceneNode Class Reference export
module helios.scene.CameraSceneNode
Represents an adapter for cameras, allowing spatial positioning and transformation within the scene graph.
Public Member Functions
CameraSceneNode (std::unique_ptr< helios::scene::Camera > camera)
Constructs a CameraSceneNode that takes ownership of the given camera.
SceneNode * addNode (std::unique_ptr< SceneNode > sceneNode) override
Prevents adding child nodes to a camera scene node.
const helios::scene::Camera & camera () const noexcept
Gets the camera associated with this scene node.
helios::scene::Camera & camera () noexcept
Gets the camera associated with this scene node.
void lookAt (helios::math::vec3f target, helios::math::vec3f up)
Orients this camera node to look at a target position in world space.
void lookAtLocal (helios::math::vec3f targetLocal, helios::math::vec3f upLocal)
Orients this camera node to look at a target position in local space.
void onWorldTransformUpdate () noexcept override
Callback invoked when the world transform of this node changes.
Public Member Functions inherited from helios::scene::SceneNode
virtual ~SceneNode ()=default
SceneNode (const SceneNode &)=delete
Delete copy constructor. A SceneNode is not copyable.
SceneNode & operator= (const SceneNode &)=delete
Delete copy assignment operator.
SceneNode () noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
SceneNode (const Transform &transform) noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable, const Transform &transform) noexcept
Constructs a new SceneNode representing a renderable object.
SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable) noexcept
Constructs a new SceneNode representing a renderable object.
const helios::util::Guid & guid () const noexcept
Returns the globally unique identifier for this SceneNode.
const std::vector< std::unique_ptr< SceneNode > > & children () const noexcept
Returns a const ref to the list of this node's children.
std::shared_ptr< const helios::rendering::Renderable > renderable () const noexcept
Returns a shared pointer to the Renderable of this SceneNode.
bool hasRenderable () const noexcept
Returns true if this SceneNode was configured with a Renderable.
std::shared_ptr< helios::rendering::Renderable > renderable () noexcept
Returns a shared pointer to the non-const Renderable of this SceneNode.
SceneNode & setScale (const helios::math::vec3f &scale) noexcept
Applies a scaling transformation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
SceneNode & setRotation (const helios::math::mat4f &rotation) noexcept
Applies rotation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
SceneNode & setTranslation (const helios::math::vec3f &translation) noexcept
Applies translation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
const Transform & localTransform () const noexcept
Returns this SceneNode's localTransform.
Transform & localTransform () noexcept
Returns this SceneNode's localTransform.
SceneNode * parent () const noexcept
Returns a pointer to this node's parent node.
bool applyWorldTransform (const helios::math::mat4f &wf, helios::scene::SceneGraphKey sceneGraphKey) noexcept
Sets the world transform for this SceneNode.
const helios::math::mat4f & worldTransform () noexcept
Computes and returns the world transform for this SceneNode. Will request the current world transform from the parent node to calculate this SceneNode's world transform. For efficiency, this method should cache the result and only trigger a recompute if this SceneNode is dirty (`needsUpdate_ == true`).
const helios::math::mat4f & cachedWorldTransform () const noexcept
Returns the current worldTransform matrix of this SceneNode **without triggering any recomputation**. This method is efficient for access when the world transform is known to be up-to-date.
bool needsUpdate () const noexcept
Checks whether this SceneNode needs to be updated.
helios::math::aabbf aabb () noexcept
Returns the axis-aligned bounding box for this SceneNode in world coordinates.
void update () noexcept
Updates the world transform and axis-aligned bounding box of this SceneNode.
helios::math::mat4f inheritWorldTransform (const helios::math::mat4f &parentWorldTransform) noexcept
Filters a parent world transform based on the node's inheritance flags.
void setInheritance (const helios::math::TransformType inherit) noexcept
Sets which transform components this node inherits from its parent.
helios::math::TransformType inheritance () const noexcept
Returns the current transform inheritance flags for this node.
bool isActive () const noexcept
Returns whether this SceneNode and its child nodes should be considered for rendering.
void setActive (bool active) noexcept
Sets the active state of this SceneNode.
Protected Attributes
std::unique_ptr< helios::scene::Camera > camera_
Unique pointer to the camera instance owned by this scene node.
Protected Attributes inherited from helios::scene::SceneNode
bool needsUpdate_ = true
Boolean flag to represent the dirty-state of this node. Should be set to false if the current `worldTransform_` for this node was computed, otherwise true, e.g. if the node's local transform has been changed.
std::shared_ptr< helios::rendering::Renderable > renderable_
A shared pointer to the Renderable this node represents in the SceneGraph. May be nullptr if this node does not represent a renderable object.
SceneNode * parent_ = nullptr
The parent node of **this** node. This will be nullptr for any root node. Implementing APIs must take care of properly assigning parent nodes when adding child nodes.
std::vector< std::unique_ptr< SceneNode > > children_
A list of unique pointers to this node's children. Ensures ownership of the child nodes withing the graph hierarchy.
math::mat4f worldTransform_ = math::mat4f::identity()
The 4x4 worldTransform-Matrix of this node. This matrix is initially set to the identity matrix. Implementing APIs MUST make sure to recompute the worldTransform before each rendering pass.
Transform localTransform_
A local transformation representing affine transformation information for this SceneNode. Encapsulates rotation, scaling and translation.
bool isActive_ = true
Boolean flag indicating whether this SceneNode should be considered for rendering.
helios::math::aabbf aabb_ {}
The axis-aligned-bounding-box for this SceneNode in world-coordinates.
helios::math::TransformType inheritance_ = helios::math::TransformType::All
Flags controlling which transform components are inherited from the parent node.
Additional Inherited Members
Protected Member Functions inherited from helios::scene::SceneNode
void setParent (SceneNode *parentNode)
Sets the parent of this SceneNode. Internally used once a child was added to this SceneNode.
Detailed Description
Represents an adapter for cameras, allowing spatial positioning and transformation within the scene graph.
A CameraSceneNode behaves just like a (non-renderable) SceneNode, except that it does not accept child nodes.
An instance of `CameraSceneNode` can be added as a direct descendant of the scene's root node for free transform, or it can be a child of a model hierarchy to inherit the corresponding positioning in the world.
Definition at line 27 of file CameraSceneNode.ixx.
Constructor & Destructor Documentation
CameraSceneNode()
helios::scene::CameraSceneNode::CameraSceneNode (std::unique_ptr< helios::scene::Camera > camera) explicit export
Constructs a CameraSceneNode that takes ownership of the given camera.
The CameraSceneNode becomes the sole owner of the Camera instance. The camera's view matrix is automatically updated when `worldTransform()` is called.
Parameters
camera A unique pointer to the camera to be owned by this scene node.
Exceptions
std::invalid_argument if camera is a nullptr.
References camera().
Member Function Documentation
addNode()
SceneNode * helios::scene::CameraSceneNode::addNode (std::unique_ptr< SceneNode > sceneNode) nodiscard override export virtual
Prevents adding child nodes to a camera scene node.
This method does nothing and returns `nullptr`, indicating that a `CameraSceneNode` must not have child nodes.
Parameters
sceneNode The attempted child node to add (ignored).
Returns
Always returns `nullptr`.
See also
https://stackoverflow.com/questions/24609872/delete-virtual-function-from-a-derived-class
Reimplemented from helios::scene::SceneNode.
References helios::scene::SceneNode::SceneNode().
camera() [1/2]
const helios::scene::Camera & helios::scene::CameraSceneNode::camera () const nodiscard export noexcept
Gets the camera associated with this scene node.
Returns
A const ref to the associated camera instance.
Referenced by camera(), and CameraSceneNode().
camera() [2/2]
helios::scene::Camera & helios::scene::CameraSceneNode::camera () nodiscard export noexcept
Gets the camera associated with this scene node.
Returns
A ref to the associated camera instance.
References camera().
lookAt()
void helios::scene::CameraSceneNode::lookAt (helios::math::vec3f target, helios::math::vec3f up) export
Orients this camera node to look at a target position in world space.
Computes the rotation matrix required to align this scene node's forward direction with the specified target position. The rotation is computed in world space and then converted to local space by factoring out the parent's rotation.
Parameters
target The world-space coordinates of the target to look at.
up The up vector defining the camera's vertical orientation in world space.
Precondition
The camera node must have a valid parent (i.e., must be added to a scene graph).
Note
The up vector should typically be `(0, 1, 0)` for standard upright orientation.
See also
lookAtLocal()
helios::scene::SceneNode::setRotation()
References lookAt().
Referenced by lookAt().
lookAtLocal()
void helios::scene::CameraSceneNode::lookAtLocal (helios::math::vec3f targetLocal, helios::math::vec3f upLocal) export
Orients this camera node to look at a target position in local space.
Similar to `lookAt()`, but the target and up vector are interpreted relative to this node's local coordinate system rather than world space. Useful when the camera should track objects within the same local hierarchy.
Parameters
targetLocal The local-space coordinates of the target to look at.
upLocal The up vector defining the camera's vertical orientation in local space.
See also
lookAt()
References lookAtLocal().
Referenced by lookAtLocal().
onWorldTransformUpdate()
void helios::scene::CameraSceneNode::onWorldTransformUpdate () override export virtual noexcept
Callback invoked when the world transform of this node changes.
Overrides the base class implementation to update the camera's view matrix whenever the node's position or orientation in the scene graph changes. This ensures the camera always reflects the current world-space transform.
See also
SceneNode::onWorldTransformUpdate()
Reimplemented from helios::scene::SceneNode.
References onWorldTransformUpdate().
Referenced by onWorldTransformUpdate().
The documentation for this class was generated from the following file:
include/helios/scene/CameraSceneNode.ixx