helios: helios::engine::FramePacer Class Reference
helios::engine::FramePacer Class Reference export
module helios.engine.FramePacer
Controls and maintains a target frame rate through precise timing and pacing.
Public Member Functions
FramePacer (std::unique_ptr< helios::util::time::Stopwatch > stopwatch)
Constructs a FramePacer with the given stopwatch.
void setTargetFps (float fps)
Sets the desired target frame rate.
float getTargetFps () const noexcept
Retrieves the current target frame rate.
void beginFrame ()
Marks the beginning of a new frame.
FrameStats sync ()
Synchronizes frame timing and returns frame statistics.
Detailed Description
Controls and maintains a target frame rate through precise timing and pacing.
The FramePacer class utilizes a `Stopwatch` to measure frame execution time and introduces necessary sleep delays to maintain a consistent target frame rate. It returns detailed timing statistics via the `FrameStats` structure upon synchronization.
The pacing mechanism helps in achieving smoother frame delivery by minimizing jitter, although strict adherence depends on the OS scheduler's precision.
Note
If `targetFps` is set to 0.0f, no frame pacing is performed, and frames run as fast as the hardware and OS allow (unlocked framerate).
Usage Example:
```cpp auto stopwatch = std::make_unique<helios::util::time::Stopwatch>(); FramePacer pacer(std::move(stopwatch)); pacer.setTargetFps(60.0f);
while (running) { pacer.beginFrame(); // ... game logic and rendering ... FrameStats stats = pacer.sync(); } ```
Definition at line 43 of file FramePacer.ixx.
Constructor & Destructor Documentation
FramePacer()
helios::engine::FramePacer::FramePacer (std::unique_ptr< helios::util::time::Stopwatch > stopwatch) explicit export
Constructs a FramePacer with the given stopwatch.
Initializes a new FramePacer instance in unlimited FPS mode (targetFps = 0.0f).
Parameters
stopwatch Unique pointer to a valid `Stopwatch` instance. Ownership is transferred to the FramePacer.
Member Function Documentation
beginFrame()
void helios::engine::FramePacer::beginFrame () export
Marks the beginning of a new frame.
Starts the internal stopwatch to begin measuring the frame's work time. This method must be called at the very beginning of each frame cycle, before any game logic, physics, or rendering operations.
References beginFrame().
Referenced by beginFrame().
getTargetFps()
float helios::engine::FramePacer::getTargetFps () const nodiscard export noexcept
Retrieves the current target frame rate.
Returns the frame rate target that has been set for pacing, expressed in Frames Per Second (FPS). If the target frame rate is set to 0.0f, frame pacing is disabled, and the frame rate is unlocked.
Returns
The target frame rate in FPS.
Note
A return value of 0.0f indicates that the frame pacing mechanism is not active.
setTargetFps()
void helios::engine::FramePacer::setTargetFps (float fps) export
Sets the desired target frame rate.
Parameters
fps The target frame rate in Frames Per Second (FPS). Set to 0.0f to disable pacing (unlocked framerate).
sync()
FrameStats helios::engine::FramePacer::sync () nodiscard export
Synchronizes frame timing and returns frame statistics.
Measures the elapsed work time since `beginFrame()`. If a target FPS is set and the work time is less than the target frame duration, this method sleeps the current thread to meet the target timing.
Returns
A `FrameStats` structure containing the total frame time (including wait), the actual work time (CPU processing), and the wait time (idle).
Note
If `targetFps` is 0.0f or the frame took longer than the target duration, no sleeping occurs, and `waitTime` in the returned stats will be 0.0f.
Todo
Implement hybrid spinning for the last millisecond of the wait time to improve timing precision and mitigate OS scheduler wake-up latency.
References sync().
Referenced by sync().
The documentation for this class was generated from the following file:
include/helios/engine/FramePacer.ixx