helios: helios::scene::Scene Class Reference
helios::scene::Scene Class Reference export
module helios.scene.Scene
Represents a hierarchical SceneGraph that organizes all renderable and non-renderable objects within a scene.
Public Member Functions
Scene (const Scene &)=delete
Prevent copying.
Scene & operator= (const Scene &)=delete
Prevent copy assignment.
Scene (Scene &&) noexcept=delete
Prevent move constructor.
Scene & operator= (Scene &&) noexcept=delete
Prevent move assignment operator.
~Scene ()=default
Scene (std::unique_ptr< helios::scene::FrustumCullingStrategy > frustumCullingStrategy)
Constructs a new Scene.
SceneNode * addNode (std::unique_ptr< SceneNode > node) const
Adds a new SceneNode to this scene.
void updateNodes () const
Updates the world transformations of SceneNodes in the graph.
std::vector< const helios::scene::SceneNode * > findVisibleNodes (const helios::scene::CameraSceneNode *cameraSceneNode) const
Applies this Scene's frustumCullingStrategy and returns all nodes visible for the specified CameraSceneNode and its associated `Camera`.
helios::scene::SceneNode & root () const noexcept
Returns the root node of this Scene.
std::optional< Snapshot > createSnapshot (const std::shared_ptr< const rendering::Viewport > &viewport) const
Creates a Snapshot of the Scene and returns it.
Detailed Description
Represents a hierarchical SceneGraph that organizes all renderable and non-renderable objects within a scene.
Every scene has one implicit root node all nodes are appended to when `addNode` is called.
A Scene is responsible for managing the SceneGraph, consisting of SceneNodes; it provides methods to frustum cull SceneNodes based on a specific `FrustumCullingStrategy` and a particular `CameraSceneNode` and also allows for propagating world transformations through the contained subtrees.
See also
[RTR, pp. 828]
[Gre19, pp. 693]
[HDMS+14, pp. 138]
Note
By default, we're not allowing copying/moving Scenes. These constraints may be relaxed in the future, depending on valid use cases.
Definition at line 50 of file Scene.ixx.
Constructor & Destructor Documentation
Scene() [1/3]
helios::scene::Scene::Scene (const Scene &) export delete
Prevent copying.
A Scene is not intended to be copied.
References Scene().
Referenced by operator=(), operator=(), Scene(), Scene(), Scene(), and ~Scene().
Scene() [2/3]
helios::scene::Scene::Scene (Scene &&) export delete noexcept
Prevent move constructor.
References Scene().
~Scene()
helios::scene::Scene::~Scene () export default
References Scene().
Scene() [3/3]
helios::scene::Scene::Scene (std::unique_ptr< helios::scene::FrustumCullingStrategy > frustumCullingStrategy) explicit export
Constructs a new Scene.
The root node for this scene is automatically created.
Parameters
frustumCullingStrategy The frustum culling strategy to use with this Scene.
References Scene().
Member Function Documentation
addNode()
SceneNode * helios::scene::Scene::addNode (std::unique_ptr< SceneNode > node) const nodiscard export
Adds a new SceneNode to this scene.
The SceneNode becomes a direct descendant of this scene's root.
Parameters
node The SceneNode to add to this Scene.
Returns
The raw pointer to the newly added node, or `nullptr` if the node was not added.
References addNode().
Referenced by addNode().
createSnapshot()
std::optional< Snapshot > helios::scene::Scene::createSnapshot (const std::shared_ptr< const rendering::Viewport > & viewport) const nodiscard export
Creates a Snapshot of the Scene and returns it.
Taking a snapshot will frustum cull the SceneNodes and place their Renderables along with the current matrices of this scene into the Snapshot object.
Parameters
viewport The viewport for which the Snapshot is created.
Returns
An optional Snapshot created for this Scene, or `std::nullopt` if creation failed.
Todo
This should be refactored into a factory to prevent domain leakage between Scene and Rendering.
References createSnapshot().
Referenced by createSnapshot().
findVisibleNodes()
std::vector< const helios::scene::SceneNode * > helios::scene::Scene::findVisibleNodes (const helios::scene::CameraSceneNode * cameraSceneNode) const nodiscard export
Applies this Scene's frustumCullingStrategy and returns all nodes visible for the specified CameraSceneNode and its associated `Camera`.
This method ensures that all nodes' world geometry is properly updated before culling is applied.
Parameters
cameraSceneNode The cameraSceneNode used to determine the view frustum for culling.
Returns
A list of currently visible nodes (const pointers into the scene graph).
References findVisibleNodes().
Referenced by findVisibleNodes().
operator=() [1/2]
Scene & helios::scene::Scene::operator= (const Scene &) export delete
Prevent copy assignment.
A Scene is not intended to be copied.
References Scene().
operator=() [2/2]
Scene & helios::scene::Scene::operator= (Scene &&) export delete noexcept
Prevent move assignment operator.
References Scene().
root()
helios::scene::SceneNode & helios::scene::Scene::root () const nodiscard export noexcept
Returns the root node of this Scene.
The root node is guaranteed to exist.
Returns
The root node of this Scene.
References root().
Referenced by root().
updateNodes()
void helios::scene::Scene::updateNodes () const export
Updates the world transformations of SceneNodes in the graph.
The method traverses the Scene and propagates updated world transformations to their respective child nodes if the processed node is considered to be dirty.
The documentation for this class was generated from the following file:
include/helios/scene/Scene.ixx