helios: helios::scene::Transform Class Reference
helios::scene::Transform Class Reference export
module helios.scene.Transform
Represents a 3D transformation consisting of translation, rotation and scale.
Public Member Functions
~Transform ()=default
Transform ()=default
Constructs a new Transform object with the default identity transformation, i.e. scale (1, 1, 1), rotation 4x4_id, translate (0, 0, 0).
Transform (const helios::math::mat4f &rotation, helios::math::vec3f scale, helios::math::vec3f translation) noexcept
Constructs a new Transformation matrix from the specified rotation, scale and translation.
void setRotation (const math::mat4f &rotation) noexcept
Sets the rotation component of this Transform. Marks this Transform object as dirty.
void setTranslation (const math::vec3f &translation) noexcept
Sets the translation component of this Transform. Marks this Transform object as dirty.
void setScale (const math::vec3f &scale) noexcept
Sets the scale component of this Transform. Marks this Transform object as dirty.
helios::math::mat4f rotation () const noexcept
Returns the current rotation component of this Transform object.
helios::math::vec3f translation () const noexcept
Returns the current translation component of this Transform object.
helios::math::vec3f scaling () const noexcept
Returns the current scale component of this Transform object.
helios::math::mat4f transform () const noexcept
Returns the 4x4 transformation matrix combined from scale, rotation, and translation.
bool needsUpdate () const noexcept
Checks whether this Transform needs to be updated, e.g. because the various components changed.
Detailed Description
Represents a 3D transformation consisting of translation, rotation and scale.
This class encapsulates the components of a local transform for SceneNodes. It uses lazy evaluation to compute the final transform. The current scale, translation and rotation is queryable. Changing the transformation is always considered against an "origin" of an object, that is, a 4x4 identity matrix
Todo
use quaternions for rotation
Definition at line 29 of file Transform.ixx.
Constructor & Destructor Documentation
~Transform()
helios::scene::Transform::~Transform () export default
Transform() [1/2]
helios::scene::Transform::Transform () export default
Constructs a new Transform object with the default identity transformation, i.e. scale (1, 1, 1), rotation 4x4_id, translate (0, 0, 0).
Transform() [2/2]
helios::scene::Transform::Transform (const helios::math::mat4f & rotation, helios::math::vec3f scale, helios::math::vec3f translation) export noexcept
Constructs a new Transformation matrix from the specified rotation, scale and translation.
Parameters
rotation The initial rotation matrix.
scale The initial scaling vector.
translation The initial translation vector.
References rotation(), and translation().
Member Function Documentation
needsUpdate()
bool helios::scene::Transform::needsUpdate () const nodiscard export noexcept
Checks whether this Transform needs to be updated, e.g. because the various components changed.
Returns
true if this Transform is considered to be dirty, otherwise false.
References needsUpdate().
Referenced by needsUpdate().
rotation()
helios::math::mat4f helios::scene::Transform::rotation () const nodiscard export noexcept
Returns the current rotation component of this Transform object.
Returns
The current 4x4 rotation matrix.
Referenced by setRotation(), and Transform().
scaling()
helios::math::vec3f helios::scene::Transform::scaling () const nodiscard export noexcept
Returns the current scale component of this Transform object.
Returns
The current 3D scale vector.
References scaling().
Referenced by scaling().
setRotation()
void helios::scene::Transform::setRotation (const math::mat4f & rotation) export noexcept
Sets the rotation component of this Transform. Marks this Transform object as dirty.
Parameters
rotation A const ref to the new rotation matrix.
References rotation().
setScale()
void helios::scene::Transform::setScale (const math::vec3f & scale) export noexcept
Sets the scale component of this Transform. Marks this Transform object as dirty.
Parameters
scale A const ref to the new scale vector.
setTranslation()
void helios::scene::Transform::setTranslation (const math::vec3f & translation) export noexcept
Sets the translation component of this Transform. Marks this Transform object as dirty.
Parameters
translation A const ref to the new translation vector.
References translation().
transform()
helios::math::mat4f helios::scene::Transform::transform () const nodiscard export noexcept
Returns the 4x4 transformation matrix combined from scale, rotation, and translation.
Returns
The current 4x4 affine transformation matrix.
References transform().
Referenced by transform().
translation()
helios::math::vec3f helios::scene::Transform::translation () const nodiscard export noexcept
Returns the current translation component of this Transform object.
Returns
The current 3D translation vector.
References translation().
Referenced by setTranslation(), Transform(), and translation().
The documentation for this class was generated from the following file:
include/helios/scene/Transform.ixx