helios: helios::rendering::Viewport Class Reference
helios::rendering::Viewport Class Reference export
module helios.rendering.Viewport
Represents a rectangular area within a RenderTarget where a scene is rendered.
Public Member Functions
Viewport () noexcept
Constructs a Viewport with normalized bounds set to (0.0f, 0.0f, 1.0f, 1.0f) and z-index 0.
Viewport (float x, float y, float width, float height, int zIndex=0) noexcept
Constructs a Viewport with specified normalized dimensions.
const helios::rendering::RenderTarget * renderTarget () const noexcept
Gets the parent RenderTarget.
Viewport & setCameraSceneNode (helios::scene::CameraSceneNode *cameraSceneNode) noexcept
Assigns a camera scene node to this viewport.
const helios::scene::CameraSceneNode * cameraSceneNode () const noexcept
Gets the camera scene node associated with this viewport.
Viewport & setRenderTarget (const helios::rendering::RenderTarget *renderTarget, ViewportKey key) noexcept
Sets the parent RenderTarget for this viewport and updates the CameraSceneNode and its associated Camera of this Viewport with an Aspect Ratio based on the dimensions of the RenderTarget.
const helios::math::vec4f & bounds () const noexcept
Gets the cached dimensions of the viewport.
void setBounds (float x, float y, float width, float height) noexcept
Sets the normalized bounds of the viewport.
int clearFlags () const noexcept
Gets the clear flags for this viewport.
const helios::math::vec4f & clearColor () const noexcept
Gets the color used for clearing the color buffer.
Viewport & setClearFlags (int clearFlags) noexcept
Sets the clear flags for this viewport.
Viewport & setClearColor (const helios::math::vec4f &color) noexcept
Specifies the RGBA values used when clearing color buffers.
Viewport & setZIndex (int zIndex) noexcept
Sets the z-index that controls rendering order relative to sibling viewports.
void onRenderTargetResize (const helios::rendering::RenderTarget &source, unsigned int width, unsigned int height) noexcept
Notifies the viewport of a change in the parent RenderTarget's dimensions.
Detailed Description
Represents a rectangular area within a RenderTarget where a scene is rendered.
A Viewport defines the 2D rectangle into which a 3D scene is projected. Its dimensions are specified in normalized coordinates relative to its parent `RenderTarget`. It is associated with a `CameraSceneNode`, which provides the view and projection matrices. The viewport automatically updates the CameraSceneNode associated camera's aspect ratio when its parent `RenderTarget` is resized.
Since a Viewport only stores normalized values for its location and dimensions relative to the owning RenderTarget, rendering APIs should query the size of the RenderTarget when a viewport is about to be rendered, allowing them to compute the final screen coordinates and dimensions correctly.
See also
helios::rendering::RenderTarget
helios::scene::CameraSceneNode
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glViewport.xhtml
Definition at line 56 of file Viewport.ixx.
Constructor & Destructor Documentation
Viewport() [1/2]
helios::rendering::Viewport::Viewport () export noexcept
Constructs a Viewport with normalized bounds set to (0.0f, 0.0f, 1.0f, 1.0f) and z-index 0.
Referenced by setCameraSceneNode(), setClearColor(), setClearFlags(), setRenderTarget(), setZIndex(), and Viewport().
Viewport() [2/2]
helios::rendering::Viewport::Viewport (float x, float y, float width, float height, int zIndex = 0) explicit export noexcept
Constructs a Viewport with specified normalized dimensions.
Parameters
x The normalized horizontal offset [0, 1].
y The normalized vertical offset [0, 1].
width The normalized width [0, 1].
height The normalized height [0, 1].
zIndex The z-index that determines the rendering order.
References Viewport().
Member Function Documentation
bounds()
const helios::math::vec4f & helios::rendering::Viewport::bounds () const nodiscard export noexcept
Gets the cached dimensions of the viewport.
Returns
A const reference to a vec4f containing [x, y, width, height].
References bounds().
Referenced by bounds().
cameraSceneNode()
const helios::scene::CameraSceneNode * helios::rendering::Viewport::cameraSceneNode () const nodiscard export noexcept
Gets the camera scene node associated with this viewport.
Returns
A const pointer to the associated `CameraSceneNode`, or `nullptr` if none is set.
References cameraSceneNode().
Referenced by cameraSceneNode(), and setCameraSceneNode().
clearColor()
const helios::math::vec4f & helios::rendering::Viewport::clearColor () const nodiscard export noexcept
Gets the color used for clearing the color buffer.
Returns
A const reference to the clear color.
References clearColor().
Referenced by clearColor().
clearFlags()
int helios::rendering::Viewport::clearFlags () const nodiscard export noexcept
Gets the clear flags for this viewport.
Returns
An integer bitmask representing the `ClearFlags`.
References clearFlags().
Referenced by clearFlags(), and setClearFlags().
onRenderTargetResize()
void helios::rendering::Viewport::onRenderTargetResize (const helios::rendering::RenderTarget & source, unsigned int width, unsigned int height) export noexcept
Notifies the viewport of a change in the parent RenderTarget's dimensions.
This method is called by the parent `RenderTarget` when it is resized. The viewport uses the new dimensions to calculate the correct aspect ratio for its associated camera.
Parameters
source A const reference to the notifying RenderTarget.
width The new width of the RenderTarget in pixels.
height The new height of the RenderTarget in pixels.
See also
updateCamera()
References onRenderTargetResize().
Referenced by onRenderTargetResize().
renderTarget()
const helios::rendering::RenderTarget * helios::rendering::Viewport::renderTarget () const nodiscard export noexcept
Gets the parent RenderTarget.
If the returned value is a nullptr, this Viewport is not owned by any RenderTarget.
Returns
A const pointer to the parent RenderTarget, or `nullptr` if not set.
References renderTarget().
Referenced by renderTarget(), and setRenderTarget().
setBounds()
void helios::rendering::Viewport::setBounds (float x, float y, float width, float height) export noexcept
Sets the normalized bounds of the viewport.
Parameters
x The normalized horizontal offset [0, 1].
y The normalized vertical offset [0, 1].
width The normalized width [0, 1].
height The normalized height [0, 1].
References setBounds().
Referenced by setBounds().
setCameraSceneNode()
Viewport & helios::rendering::Viewport::setCameraSceneNode (helios::scene::CameraSceneNode * cameraSceneNode) export noexcept
Assigns a camera scene node to this viewport.
The viewport uses the associated camera's projection matrix and the node's computed view matrix for rendering. The camera's aspect ratio is automatically updated when the parent RenderTarget is resized.
Parameters
cameraSceneNode A non-owning raw pointer to the `CameraSceneNode`. Must remain valid for the lifetime of this viewport.
Returns
A reference to this viewport to allow fluent chaining.
References cameraSceneNode(), setCameraSceneNode(), and Viewport().
Referenced by setCameraSceneNode().
setClearColor()
Viewport & helios::rendering::Viewport::setClearColor (const helios::math::vec4f & color) export noexcept
Specifies the RGBA values used when clearing color buffers.
Values are automatically clamped to the range [0, 1].
Parameters
color The color to use for clearing.
Returns
A reference to this viewport to allow fluent chaining.
References setClearColor(), and Viewport().
Referenced by setClearColor().
setClearFlags()
Viewport & helios::rendering::Viewport::setClearFlags (int clearFlags) export noexcept
Sets the clear flags for this viewport.
Parameters
clearFlags An integer bitmask created from `ClearFlags` enum values.
Returns
A reference to this viewport to allow fluent chaining.
References clearFlags(), setClearFlags(), and Viewport().
Referenced by setClearFlags().
setRenderTarget()
Viewport & helios::rendering::Viewport::setRenderTarget (const helios::rendering::RenderTarget * renderTarget, ViewportKey key) export noexcept
Sets the parent RenderTarget for this viewport and updates the CameraSceneNode and its associated Camera of this Viewport with an Aspect Ratio based on the dimensions of the RenderTarget.
This function can only be called by classes that can construct a `ViewportKey`, effectively restricting its use to the `RenderTarget` class.
Parameters
renderTarget A pointer to the parent RenderTarget.
key A `ViewportKey` instance, required for authorization.
Returns
A reference to this viewport to allow fluent chaining.
See also
updateCamera()
Todo
The Viewport should observe the RenderTarget for state changes (e.g., resize).
References renderTarget(), setRenderTarget(), and Viewport().
Referenced by setRenderTarget().
setZIndex()
Viewport & helios::rendering::Viewport::setZIndex (int zIndex) export noexcept
Sets the z-index that controls rendering order relative to sibling viewports.
Parameters
zIndex The new z-index value; higher values are rendered later.
Returns
A reference to this viewport to allow fluent chaining.
References setZIndex(), and Viewport().
Referenced by setZIndex().
The documentation for this class was generated from the following file:
include/helios/rendering/Viewport.ixx