helios: helios::engine::game::components::gameplay::ShootComponent Class Reference
helios::engine::game::components::gameplay::ShootComponent Class Reference export
module helios.engine.game.components.gameplay.ShootComponent
Component for handling projectile shooting with rate limiting.
Public Member Functions
void onAttach (::helios::engine::game::GameObject *gameObject) noexcept override
Called when the component is attached to a GameObject.
void shoot (float intensity, helios::math::vec3f sourceVelocity)
Sets the shooting intensity.
void update (helios::engine::game::UpdateContext &updateContext) noexcept override
Updates the component, spawning projectiles when ready.
float intensity () const noexcept
Returns the current fire intensity.
float cooldownTime () const noexcept
Returns the cooldown time between shots.
void setCooldownTime (float cooldown) noexcept
Sets the cooldown time between shots.
float projectileSpeed () const noexcept
Returns the projectile speed.
void setProjectileSpeed (float speed) noexcept
Sets the projectile speed.
Public Member Functions inherited from helios::engine::game::Component
virtual ~Component ()=default
Component ()=default
virtual void onAttach (GameObject *gameObject) noexcept
Called when the component is attached to a GameObject.
GameObject * gameObject () const noexcept
Returns the owning GameObject.
Public Member Functions inherited from helios::engine::game::Updatable
virtual ~Updatable ()=default
Updatable ()=default
Protected Attributes
float intensity_ = 0.0f
Current fire intensity (0.0 to 1.0).
helios::engine::game::components::gameplay::Aim2DComponent * aimComponent_ = nullptr
Pointer to the aim component for direction.
helios::engine::game::components::physics::TransformComponent * transformComponent_ = nullptr
Pointer to the scene node component for spawn position.
float cooldownDelta_ = 0.0f
Cooldown timer for fire rate limiting, in seconds.
float cooldownTime_ = 0.0625f
Cooldown timer for fire rate limiting, in seconds.
float projectileSpeed_ = 60.0f
The projectile speed, in meters per second.
helios::math::vec3f sourceVelocity_
Velocity of the source object in three-dimensional space.
Protected Attributes inherited from helios::engine::game::Component
GameObject * gameObject_ = nullptr
Non-owning pointer to the owning GameObject.
Detailed Description
Component for handling projectile shooting with rate limiting.
Manages the shooting mechanics for a GameObject by coordinating with aim-components for direction and a projectile pool for projectile spawning. Implements a cooldown timer to control fire rate.
Example usage: ```cpp auto shootComponent = std::make_unique<ShootComponent>(); gameObject.add(std::move(shootComponent));
// Trigger shooting (typically from ShootCommand) shootComponent->shoot(1.0f); ```
Definition at line 55 of file ShootComponent.ixx.
Member Function Documentation
cooldownTime()
float helios::engine::game::components::gameplay::ShootComponent::cooldownTime () const inline nodiscard export noexcept
Returns the cooldown time between shots.
Returns
Cooldown duration in seconds.
Definition at line 196 of file ShootComponent.ixx.
References cooldownTime_.
intensity()
float helios::engine::game::components::gameplay::ShootComponent::intensity () const inline nodiscard export noexcept
Returns the current fire intensity.
Returns
The intensity value (0.0 to 1.0).
Definition at line 187 of file ShootComponent.ixx.
References intensity_.
Referenced by shoot().
onAttach()
void helios::engine::game::components::gameplay::ShootComponent::onAttach (::helios::engine::game::GameObject * gameObject) inline override export noexcept
Called when the component is attached to a GameObject.
Retrieves references to required sibling components.
Parameters
gameObject The GameObject this component is being attached to.
Definition at line 120 of file ShootComponent.ixx.
References aimComponent_, helios::engine::game::Component::gameObject(), helios::engine::game::Component::onAttach(), and transformComponent_.
projectileSpeed()
float helios::engine::game::components::gameplay::ShootComponent::projectileSpeed () const inline nodiscard export noexcept
Returns the projectile speed.
Returns
Projectile speed in meters per second.
Definition at line 214 of file ShootComponent.ixx.
References projectileSpeed_.
setCooldownTime()
void helios::engine::game::components::gameplay::ShootComponent::setCooldownTime (float cooldown) inline export noexcept
Sets the cooldown time between shots.
Parameters
cooldown New cooldown duration in seconds.
Definition at line 205 of file ShootComponent.ixx.
References cooldownTime_.
setProjectileSpeed()
void helios::engine::game::components::gameplay::ShootComponent::setProjectileSpeed (float speed) inline export noexcept
Sets the projectile speed.
Parameters
speed New projectile speed in meters per second.
Definition at line 223 of file ShootComponent.ixx.
References projectileSpeed_.
shoot()
void helios::engine::game::components::gameplay::ShootComponent::shoot (float intensity, helios::math::vec3f sourceVelocity) inline export
Sets the shooting intensity.
Call with a non-zero value to start shooting, or zero to stop. The intensity affects whether projectiles are spawned during update().
Parameters
intensity Fire intensity (0.0 to 1.0). Zero stops firing.
sourceVelocity The velocity of the object emitting the projectile.
Definition at line 138 of file ShootComponent.ixx.
References aimComponent_, intensity(), intensity_, and sourceVelocity_.
update()
void helios::engine::game::components::gameplay::ShootComponent::update (helios::engine::game::UpdateContext & updateContext) inline override export virtual noexcept
Updates the component, spawning projectiles when ready.
Checks the cooldown timer and aim direction. If conditions are met, spawns a projectile from the ProjectilePoolSystem at the current position traveling in the aim direction.
Parameters
updateContext The update context containing timing and game state.
Implements helios::engine::game::Updatable.
Definition at line 157 of file ShootComponent.ixx.
References aimComponent_, cooldownDelta_, cooldownTime_, helios::math::EPSILON_LENGTH, intensity_, projectileSpeed_, sourceVelocity_, helios::engine::game::systems::gameplay::ProjectilePoolSystem::spawn(), and transformComponent_.
The documentation for this class was generated from the following file:
include/helios/engine/game/components/gameplay/ShootComponent.ixx