helios: helios::event::BasicEventManager Class Reference
helios::event::BasicEventManager Class Reference final export
module helios.event.BasicEventManager
Basic implementation of the EventManager.
Public Member Functions
BasicEventManager (std::unique_ptr< EventQueue > eventQueue, std::unique_ptr< Dispatcher > dispatcher)
Constructs a new BasicEventManager, using the specified EventQueue and the Dispatcher.
EventManager & post (std::unique_ptr< const Event > event, PostPolicy policy, const std::function< bool(const std::unique_ptr< const Event > &event, const std::unique_ptr< const Event > &evt)> &func) override
Posts an event based on the specified policy to the EventQueue.
EventManager & dispatchAll () override
Dispatches all events of the queue, passing ownership to the underlying Dispatcher. Clears the underlying EventQueue.
EventManager & post (std::unique_ptr< const Event > event)
Posts the event to the queue using the APPEND policy, passing ownership of the event to the underlying queue.
EventManager & post (std::unique_ptr< const Event > event, PostPolicy policy)
Posts the event to the queue, passing ownership of the event to the underlying queue.
Public Member Functions inherited from helios::event::EventManager
virtual ~EventManager ()=default
EventManager (std::unique_ptr< EventQueue > eventQueue, std::unique_ptr< Dispatcher > dispatcher)
Creates a new EventManager using the specified EventQueue and Dispatcher.
EventManager & post (std::unique_ptr< const Event > event)
Posts the event to the queue using the APPEND policy, passing ownership of the event to the underlying queue.
EventManager & post (std::unique_ptr< const Event > event, PostPolicy policy)
Posts the event to the queue, passing ownership of the event to the underlying queue.
template<typename EventType>
EventManager & subscribe (std::function< void(const EventType &)> callback)
Subscribes a callback to the specified EventType.
Dispatcher & dispatcher () const noexcept
Returns a reference to the dispatcher used with this EventManager.
Additional Inherited Members
Protected Member Functions inherited from helios::event::EventManager
EventManager ()=default
Protected Attributes inherited from helios::event::EventManager
std::unique_ptr< EventQueue > eventQueue_
A unique_ptr to the EventQueue this EventManager owns.
std::unique_ptr< Dispatcher > dispatcher_
A unique_ptr to the Dispatcher this EventManager owns.
Static Protected Attributes inherited from helios::event::EventManager
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Detailed Description
Basic implementation of the EventManager.
This implementation provides the concrete logic for post() and dispatchAll().
Definition at line 28 of file BasicEventManager.ixx.
Constructor & Destructor Documentation
BasicEventManager()
helios::event::BasicEventManager::BasicEventManager (std::unique_ptr< EventQueue > eventQueue, std::unique_ptr< Dispatcher > dispatcher) explicit export
Constructs a new BasicEventManager, using the specified EventQueue and the Dispatcher.
Parameters
eventQueue
dispatcher
References helios::event::EventManager::dispatcher().
Member Function Documentation
dispatchAll()
EventManager & helios::event::BasicEventManager::dispatchAll () override export virtual
Dispatches all events of the queue, passing ownership to the underlying Dispatcher. Clears the underlying EventQueue.
Returns
EventManager
Implements helios::event::EventManager.
References helios::event::EventManager::EventManager().
post() [1/3]
EventManager & helios::event::EventManager::post (std::unique_ptr< const Event > event)
Posts the event to the queue using the APPEND policy, passing ownership of the event to the underlying queue.
Calling this function is functionally identical to calling post() with the second argument set to APPEND.
Parameters
event The event to post to the EventQueue.
Returns
EventManager
post() [2/3]
EventManager & helios::event::EventManager::post (std::unique_ptr< const Event > event, PostPolicy policy)
Posts the event to the queue, passing ownership of the event to the underlying queue.
Calling this function is identical to calling post() with the third argument func set to nullptr, relying on the default implementations.
Parameters
event The event to post to the EventQueue.
policy The policy to use for posting the event.
Returns
EventManager
post() [3/3]
EventManager & helios::event::BasicEventManager::post (std::unique_ptr< const Event > event, PostPolicy policy, const std::function< bool(const std::unique_ptr< const Event > &event, const std::unique_ptr< const Event > &evt)> & func) override export virtual
Posts an event based on the specified policy to the EventQueue.
Parameters
event A unique_ptr to the event that should be posted
policy The policy to use for positing the event.
func A comparison function for LATEST_WINS policy. If none is specified, this method will compare the events based on type and tag equality.
Returns
EventManager
Implements helios::event::EventManager.
References helios::event::EventManager::EventManager().
The documentation for this class was generated from the following file:
include/helios/event/BasicEventManager.ixx