helios: helios::ext::imgui::widgets::LogWidget Class Reference
helios::ext::imgui::widgets::LogWidget Class Reference export
module helios.ext.imgui.widgets.LogWidget
Debug widget for displaying log output in a scrollable ImGui panel.
Public Member Functions
LogWidget ()=default
~LogWidget () override=default
void addLog (LogLevel level, const std::string &scope, const std::string &message)
Adds a log entry to the appropriate scope buffer(s).
void debug (const std::string &scope, const std::string &message)
Convenience method to add a debug-level log entry.
void info (const std::string &scope, const std::string &message)
Convenience method to add an info-level log entry.
void warn (const std::string &scope, const std::string &message)
Convenience method to add a warning-level log entry.
void error (const std::string &scope, const std::string &message)
Convenience method to add an error-level log entry.
void clear () noexcept
Clears all log entries from all buffers.
void setMaxEntries (std::size_t max) noexcept
Sets the maximum number of entries to retain per scope.
void setAutoScroll (bool enabled) noexcept
Enables or disables auto-scrolling to the latest entry.
void setFilterLevel (LogLevel level) noexcept
Sets the minimum log level to display.
void setScopeFilterCallback (std::function< void(const std::string &)> callback)
Sets a callback to be invoked when the scope filter changes.
std::size_t entryCount () const noexcept
Returns the current number of log entries in the active buffer.
void draw () override
Renders the log widget using ImGui.
Public Member Functions inherited from helios::ext::imgui::ImGuiWidget
ImGuiWidget ()=default
virtual ~ImGuiWidget ()=default
Detailed Description
Debug widget for displaying log output in a scrollable ImGui panel.
This widget maintains separate buffers for each log scope and renders them in a scrollable text area. It supports filtering by log level, clearing the buffer, and auto-scrolling to the latest messages.
Each scope has its own buffer with a maximum of 1000 entries, allowing efficient scope-based filtering without losing messages from other scopes.
Note
This widget uses internal locking for adding log entries from multiple threads.
Definition at line 73 of file LogWidget.ixx.
Constructor & Destructor Documentation
LogWidget()
helios::ext::imgui::widgets::LogWidget::LogWidget () export default
~LogWidget()
helios::ext::imgui::widgets::LogWidget::~LogWidget () override export default
Member Function Documentation
addLog()
void helios::ext::imgui::widgets::LogWidget::addLog (LogLevel level, const std::string & scope, const std::string & message) inline export
Adds a log entry to the appropriate scope buffer(s).
Thread-safe. Adds to both the scope-specific buffer and the "all" buffer.
Definition at line 290 of file LogWidget.ixx.
References helios::ext::imgui::widgets::LogEntry::level, helios::ext::imgui::widgets::LogEntry::message, helios::ext::imgui::widgets::LogEntry::scope, and helios::ext::imgui::widgets::LogEntry::timestamp.
Referenced by debug(), error(), info(), and warn().
clear()
void helios::ext::imgui::widgets::LogWidget::clear () inline export noexcept
Clears all log entries from all buffers.
Definition at line 367 of file LogWidget.ixx.
Referenced by draw().
debug()
void helios::ext::imgui::widgets::LogWidget::debug (const std::string & scope, const std::string & message) inline export
Convenience method to add a debug-level log entry.
Parameters
scope The source scope or module name.
message The log message text.
Definition at line 330 of file LogWidget.ixx.
References addLog(), and helios::ext::imgui::widgets::Debug.
draw()
void helios::ext::imgui::widgets::LogWidget::draw () inline override export virtual
Renders the log widget using ImGui.
Implements helios::ext::imgui::ImGuiWidget.
Definition at line 435 of file LogWidget.ixx.
References clear(), helios::ext::imgui::widgets::LogEntry::level, helios::ext::imgui::widgets::LogEntry::message, helios::ext::imgui::widgets::LogEntry::scope, and helios::ext::imgui::widgets::LogEntry::timestamp.
entryCount()
std::size_t helios::ext::imgui::widgets::LogWidget::entryCount () const inline nodiscard export noexcept
Returns the current number of log entries in the active buffer.
Returns
The number of entries currently stored.
Definition at line 427 of file LogWidget.ixx.
error()
void helios::ext::imgui::widgets::LogWidget::error (const std::string & scope, const std::string & message) inline export
Convenience method to add an error-level log entry.
Parameters
scope The source scope or module name.
message The log message text.
Definition at line 360 of file LogWidget.ixx.
References addLog(), and helios::ext::imgui::widgets::Error.
info()
void helios::ext::imgui::widgets::LogWidget::info (const std::string & scope, const std::string & message) inline export
Convenience method to add an info-level log entry.
Parameters
scope The source scope or module name.
message The log message text.
Definition at line 340 of file LogWidget.ixx.
References addLog(), and helios::ext::imgui::widgets::Info.
setAutoScroll()
void helios::ext::imgui::widgets::LogWidget::setAutoScroll (bool enabled) inline export noexcept
Enables or disables auto-scrolling to the latest entry.
Parameters
enabled True to enable auto-scroll.
Definition at line 396 of file LogWidget.ixx.
setFilterLevel()
void helios::ext::imgui::widgets::LogWidget::setFilterLevel (LogLevel level) inline export noexcept
Sets the minimum log level to display.
Parameters
level Entries below this level are hidden.
Definition at line 405 of file LogWidget.ixx.
setMaxEntries()
void helios::ext::imgui::widgets::LogWidget::setMaxEntries (std::size_t max) inline export noexcept
Sets the maximum number of entries to retain per scope.
Parameters
max The maximum buffer size.
Definition at line 378 of file LogWidget.ixx.
setScopeFilterCallback()
void helios::ext::imgui::widgets::LogWidget::setScopeFilterCallback (std::function< void(const std::string &)> callback) inline export
Sets a callback to be invoked when the scope filter changes.
The callback receives the selected scope string, or an empty string when "All" is selected. Use this to integrate with LogManager::setScopeFilter().
Parameters
callback Function to call on scope filter change.
Definition at line 418 of file LogWidget.ixx.
warn()
void helios::ext::imgui::widgets::LogWidget::warn (const std::string & scope, const std::string & message) inline export
Convenience method to add a warning-level log entry.
Parameters
scope The source scope or module name.
message The log message text.
Definition at line 350 of file LogWidget.ixx.
References addLog(), and helios::ext::imgui::widgets::Warn.
The documentation for this class was generated from the following file:
include/ext/imgui/widgets/LogWidget.ixx