helios: helios::scene::Snapshot Class Reference
helios::scene::Snapshot Class Reference final export
module helios.scene.Snapshot
Represents an immutable snapshot of a SceneGraph at a given point in time.
Public Member Functions
~Snapshot ()=default
Snapshot (const Snapshot &)=delete
Delete copy constructor.
Snapshot & operator= (const Snapshot &)=delete
Delete copy assignment operator.
Snapshot (std::shared_ptr< const helios::rendering::Viewport > viewport, const math::mat4f &projectionMatrix, const math::mat4f &viewMatrix, std::vector< SnapshotItem > snapshotItems) noexcept
Constructs a new immutable Snapshot from the given data.
const std::vector< SnapshotItem > & snapshotItems () const noexcept
Returns a const reference to this Snapshot's SnapshotItems.
std::shared_ptr< const helios::rendering::Viewport > viewport () const noexcept
Returns the viewport associated with this Snapshot.
const helios::math::mat4f & projectionMatrix () const noexcept
Returns a const reference to the projection matrix for this Snapshot.
const helios::math::mat4f & viewMatrix () const noexcept
Returns a const reference to the view matrix for this Snapshot.
Protected Attributes
const helios::math::mat4f projectionMatrix_
The projection matrix that should be used with this Snapshot.
const helios::math::mat4f viewMatrix_
The view matrix that should be used with this Snapshot.
const std::vector< SnapshotItem > snapshotItems_
A const collection of `SnapshotItem`s representing all renderable objects visible in this Snapshot.
std::shared_ptr< const helios::rendering::Viewport > viewport_
The viewport associated with this Snapshot.
Detailed Description
Represents an immutable snapshot of a SceneGraph at a given point in time.
The class encapsulates all necessary data to render a single frame. It is designed to be a lightweight DTO to pass information to the rendering engine abstraction layer, such as the `RenderPass` class.
A snapshot includes a camera's projection and view matrix that should be used for rendering the scene. A collection of `SnapshotItems` holds the information about the renderable objects in the scene, preferably computed by using a `FrustumCullingStrategy` (
See also
Scene::createSnapshot).
The class is not copyable to enforce its immutability and prevent unintended duplication of potentially large data sets.
Definition at line 34 of file Snapshot.ixx.
Constructor & Destructor Documentation
~Snapshot()
helios::scene::Snapshot::~Snapshot () export default
Snapshot() [1/2]
helios::scene::Snapshot::Snapshot (const Snapshot &) export delete
Delete copy constructor.
Snapshots are not intended to be copied.
References Snapshot().
Referenced by operator=(), and Snapshot().
Snapshot() [2/2]
helios::scene::Snapshot::Snapshot (std::shared_ptr< const helios::rendering::Viewport > viewport, const math::mat4f & projectionMatrix, const math::mat4f & viewMatrix, std::vector< SnapshotItem > snapshotItems) export noexcept
Constructs a new immutable Snapshot from the given data.
Parameters
viewport The viewport associated with this snapshot.
projectionMatrix The projection matrix of the camera for this snapshot.
viewMatrix The view matrix of the camera for this snapshot.
snapshotItems A vector of snapshot items. The vector is moved into the Snapshot, transferring ownership to this instance.
References projectionMatrix(), snapshotItems(), viewMatrix(), and viewport().
Member Function Documentation
operator=()
Snapshot & helios::scene::Snapshot::operator= (const Snapshot &) export delete
Delete copy assignment operator.
Snapshots are not intended to be copied.
References Snapshot().
projectionMatrix()
const helios::math::mat4f & helios::scene::Snapshot::projectionMatrix () const nodiscard export noexcept
Returns a const reference to the projection matrix for this Snapshot.
The matrix represents the projection matrix of the camera that was used to capture this scene.
Returns
A const reference to the projection matrix used for creating this Snapshot.
References projectionMatrix().
Referenced by projectionMatrix(), and Snapshot().
snapshotItems()
const std::vector< SnapshotItem > & helios::scene::Snapshot::snapshotItems () const nodiscard export noexcept
Returns a const reference to this Snapshot's SnapshotItems.
The vector contains all renderable items in the scene.
Returns
A const reference to this Snapshot's collection of SnapshotItems.
Referenced by Snapshot().
viewMatrix()
const helios::math::mat4f & helios::scene::Snapshot::viewMatrix () const nodiscard export noexcept
Returns a const reference to the view matrix for this Snapshot.
The matrix represents the view matrix of the camera that was used to capture this scene.
Returns
A const reference to the view matrix used for creating this Snapshot.
References viewMatrix().
Referenced by Snapshot(), and viewMatrix().
viewport()
std::shared_ptr< const helios::rendering::Viewport > helios::scene::Snapshot::viewport () const nodiscard export noexcept
Returns the viewport associated with this Snapshot.
Returns
A shared pointer to the const Viewport.
References viewport().
Referenced by Snapshot(), and viewport().
The documentation for this class was generated from the following file:
include/helios/scene/Snapshot.ixx