helios: helios::engine::game::components::physics::ScaleComponent Class Reference
helios::engine::game::components::physics::ScaleComponent Class Reference export
module helios.engine.game.components.physics.ScaleComponent
Component that defines the physical dimensions (scale) of an entity.
Public Member Functions
ScaleComponent (const float width, const float height, const float depth, helios::core::units::Unit unit)
Constructs a ScaleComponent with specified dimensions and unit.
void onAttach (GameObject *gameObject) noexcept override
Called when the component is attached to a GameObject.
void clearDirty () noexcept
Clears the dirty flag.
bool isDirty () const noexcept
Checks if the scale has changed.
helios::core::units::Unit unit () const noexcept
Retrieves the unit of measurement.
helios::math::vec3f scaling () const noexcept
Retrieves the scaling vector (width, height, depth).
void setScale (const float width, const float height, const float depth, const helios::core::units::Unit unit=helios::core::units::Unit::Meter) noexcept
Sets the dimensions and unit of the entity.
Public Member Functions inherited from helios::engine::game::Component
virtual ~Component ()=default
Component ()=default
GameObject * gameObject () const noexcept
Returns the owning GameObject.
Additional Inherited Members
Protected Attributes inherited from helios::engine::game::Component
GameObject * gameObject_ = nullptr
Non-owning pointer to the owning GameObject.
Detailed Description
Component that defines the physical dimensions (scale) of an entity.
This component stores the width, height, and depth of an entity, along with the unit of measurement. It tracks changes via a dirty flag, allowing other systems to react to scale updates.
Definition at line 25 of file ScaleComponent.ixx.
Constructor & Destructor Documentation
ScaleComponent()
helios::engine::game::components::physics::ScaleComponent::ScaleComponent (const float width, const float height, const float depth, helios::core::units::Unit unit) inline explicit export
Constructs a ScaleComponent with specified dimensions and unit.
Parameters
width Width of the entity.
height Height of the entity.
depth Depth of the entity.
unit Unit of measurement (default: Meter).
Definition at line 62 of file ScaleComponent.ixx.
References unit().
Member Function Documentation
clearDirty()
void helios::engine::game::components::physics::ScaleComponent::clearDirty () inline export noexcept
Clears the dirty flag.
Definition at line 77 of file ScaleComponent.ixx.
Referenced by helios::engine::game::systems::post::ScaleClearSystem::update().
isDirty()
bool helios::engine::game::components::physics::ScaleComponent::isDirty () const inline nodiscard export noexcept
Checks if the scale has changed.
Returns
True if dirty, false otherwise.
Definition at line 86 of file ScaleComponent.ixx.
onAttach()
void helios::engine::game::components::physics::ScaleComponent::onAttach (GameObject * gameObject) inline override export virtual noexcept
Called when the component is attached to a GameObject.
Parameters
gameObject Pointer to the parent GameObject.
Reimplemented from helios::engine::game::Component.
Definition at line 70 of file ScaleComponent.ixx.
References helios::engine::game::Component::gameObject(), and helios::engine::game::Component::onAttach().
scaling()
helios::math::vec3f helios::engine::game::components::physics::ScaleComponent::scaling () const inline nodiscard export noexcept
Retrieves the scaling vector (width, height, depth).
Returns
A vec3f containing the dimensions.
Definition at line 105 of file ScaleComponent.ixx.
setScale()
void helios::engine::game::components::physics::ScaleComponent::setScale (const float width, const float height, const float depth, const helios::core::units::Unit unit = helios::core::units::Unit::Meter) inline export noexcept
Sets the dimensions and unit of the entity.
Parameters
width New width.
height New height.
depth New depth.
unit New unit of measurement (default: Meter).
Definition at line 117 of file ScaleComponent.ixx.
References helios::core::units::Meter, and unit().
unit()
helios::core::units::Unit helios::engine::game::components::physics::ScaleComponent::unit () const inline nodiscard export noexcept
Retrieves the unit of measurement.
Returns
The unit enum value.
Definition at line 96 of file ScaleComponent.ixx.
Referenced by ScaleComponent(), and setScale().
The documentation for this class was generated from the following file:
include/helios/engine/game/components/physics/ScaleComponent.ixx