helios: helios::rendering::RenderCommand Class Reference
helios::rendering::RenderCommand Class Reference export
module helios.rendering.RenderCommand
DTO for storing rendering-specific command information to be passed to the RenderQueue.
Public Member Functions
RenderCommand (const RenderCommand &)=delete
Prevent copying. A RenderCommand is not intended to be copied.
RenderCommand & operator= (const RenderCommand &)=delete
Prevent copy assignment. A RenderCommand is not intended to be copied.
RenderCommand (RenderCommand &&) noexcept=delete
Delete move constructor.
RenderCommand & operator= (RenderCommand &&) noexcept=delete
Delete move assignment.
~RenderCommand ()=default
RenderCommand (std::weak_ptr< const helios::rendering::RenderPrototype > renderPrototype, std::unique_ptr< const helios::rendering::shader::UniformValueMap > objectUniformValues, std::unique_ptr< const helios::rendering::shader::UniformValueMap > materialUniformValues) noexcept
Constructs a new `RenderCommand`. Initializes this `RenderCommand` with weak pointers to the shader and mesh, and takes ownership of the provided `UniformValueMaps`.
std::weak_ptr< const helios::rendering::RenderPrototype > renderPrototype () const noexcept
Returns a weak ptr to the RenderPrototype associated with this command. Use `renderPrototype.lock()` on the return value to lock the RenderPrototype into a shared ptr. If `lock()` returns a nullptr, the RenderPrototype is no longer available.
const helios::rendering::shader::UniformValueMap & objectUniformValues () const noexcept
Returns a const ref to this command's UniformValueMap for the object.
const helios::rendering::shader::UniformValueMap & materialUniformValues () const noexcept
Returns a const ref to this command's UniformValueMap for the material.
Detailed Description
DTO for storing rendering-specific command information to be passed to the RenderQueue.
A `RenderCommand` does not extend the lifetime of the `renderPrototype_` as it's referenced by a weak pointer. If the referenced RenderPrototype is no longer valid when this command is about to be executed, this `RenderCommand` should be ignored for rendering.
Definition at line 25 of file RenderCommand.ixx.
Constructor & Destructor Documentation
RenderCommand() [1/3]
helios::rendering::RenderCommand::RenderCommand (const RenderCommand &) export delete
Prevent copying. A RenderCommand is not intended to be copied.
References RenderCommand().
Referenced by operator=(), operator=(), RenderCommand(), RenderCommand(), RenderCommand(), and ~RenderCommand().
RenderCommand() [2/3]
helios::rendering::RenderCommand::RenderCommand (RenderCommand &&) export delete noexcept
Delete move constructor.
References RenderCommand().
~RenderCommand()
helios::rendering::RenderCommand::~RenderCommand () export default
References RenderCommand().
RenderCommand() [3/3]
helios::rendering::RenderCommand::RenderCommand (std::weak_ptr< const helios::rendering::RenderPrototype > renderPrototype, std::unique_ptr< const helios::rendering::shader::UniformValueMap > objectUniformValues, std::unique_ptr< const helios::rendering::shader::UniformValueMap > materialUniformValues) export noexcept
Constructs a new `RenderCommand`. Initializes this `RenderCommand` with weak pointers to the shader and mesh, and takes ownership of the provided `UniformValueMaps`.
Parameters
renderPrototype A weak_ptr to the `RenderPrototype` to be associated with this command.
objectUniformValues A unique ptr to a `UniformValueMap` containing all uniform values for the rendered object.
materialUniformValues A unique ptr to a `UniformValueMap` containing all uniform values for the material.
References materialUniformValues(), objectUniformValues(), RenderCommand(), and renderPrototype().
Member Function Documentation
materialUniformValues()
const helios::rendering::shader::UniformValueMap & helios::rendering::RenderCommand::materialUniformValues () const nodiscard export noexcept
Returns a const ref to this command's UniformValueMap for the material.
Returns
A const ref to this command's UniformValueMap for the material.
References materialUniformValues().
Referenced by materialUniformValues(), and RenderCommand().
objectUniformValues()
const helios::rendering::shader::UniformValueMap & helios::rendering::RenderCommand::objectUniformValues () const nodiscard export noexcept
Returns a const ref to this command's UniformValueMap for the object.
Returns
A const ref to this command's UniformValueMap for the object.
References objectUniformValues().
Referenced by objectUniformValues(), and RenderCommand().
operator=() [1/2]
RenderCommand & helios::rendering::RenderCommand::operator= (const RenderCommand &) export delete
Prevent copy assignment. A RenderCommand is not intended to be copied.
References RenderCommand().
operator=() [2/2]
RenderCommand & helios::rendering::RenderCommand::operator= (RenderCommand &&) export delete noexcept
Delete move assignment.
References RenderCommand().
renderPrototype()
std::weak_ptr< const helios::rendering::RenderPrototype > helios::rendering::RenderCommand::renderPrototype () const nodiscard export noexcept
Returns a weak ptr to the RenderPrototype associated with this command. Use `renderPrototype.lock()` on the return value to lock the RenderPrototype into a shared ptr. If `lock()` returns a nullptr, the RenderPrototype is no longer available.
Returns
A weak ptr to this command's Shader.
References renderPrototype().
Referenced by RenderCommand(), and renderPrototype().
The documentation for this class was generated from the following file:
include/helios/rendering/RenderCommand.ixx