helios: helios::event::Event Class Reference
helios::event::Event Class Reference abstract export
module helios.event.Event
Base class for events in the helios framework.
Public Member Functions
virtual ~Event ()=default
Event ()
Constructs a new event with a unique Guid and a default tag of 0.
Event (uint64_t tag)
Constructs a new event with a unique Guid and teh specified default tag.
const helios::util::Guid & guid () const
Returns a const reference to this event's unique Guid.
uint64_t tag () const
Returns the tag for this event. Will be 0 if none was specified.
virtual std::string toString () const noexcept=0
bool operator== (const Event &e) const
Compares two event instances based on their unique Guids.
Detailed Description
Base class for events in the helios framework.
`Event` provides a common interface for all application related events. Each event instance is uniquely identified by a `Guid` generated upon construction. An additional tag can be provided to identify groups of events for further categorization or filtering.
Events should be treated as immutable after construction.
Todo
can we reset the value for Guids in between frames, if events are guaranteed to be dispatched and processed in between frames?
Definition at line 29 of file Event.ixx.
Constructor & Destructor Documentation
~Event()
virtual helios::event::Event::~Event () export virtual default
Event() [1/2]
helios::event::Event::Event () export
Constructs a new event with a unique Guid and a default tag of 0.
Referenced by operator==().
Event() [2/2]
helios::event::Event::Event (uint64_t tag) explicit export
Constructs a new event with a unique Guid and teh specified default tag.
Parameters
tag
References tag().
Member Function Documentation
guid()
const helios::util::Guid & helios::event::Event::guid () const nodiscard export
Returns a const reference to this event's unique Guid.
Returns
operator==()
bool helios::event::Event::operator== (const Event & e) const export
Compares two event instances based on their unique Guids.
Parameters
e
Returns
References Event().
tag()
uint64_t helios::event::Event::tag () const nodiscard export
Returns the tag for this event. Will be 0 if none was specified.
Returns
Referenced by Event(), helios::window::event::FrameBufferResizeEvent::FrameBufferResizeEvent(), and helios::window::event::WindowEvent::WindowEvent().
toString()
virtual std::string helios::event::Event::toString () const nodiscard export pure virtual noexcept
Implemented in helios::window::event::FrameBufferResizeEvent.
The documentation for this class was generated from the following file:
include/helios/event/Event.ixx