helios: helios::engine::game::GameObject Class Reference
helios::engine::game::GameObject Class Reference abstract export
module helios.engine.game.GameObject
Base class representing an interactive game entity in the game world.
Public Member Functions
GameObject (helios::scene::SceneNode *sceneNode)
Constructs a GameObject associated with a SceneNode.
virtual ~GameObject ()=default
Virtual destructor to ensure proper cleanup of derived classes.
GameObject & setSize (float width, float height, float depth, helios::core::units::Unit unit=helios::core::units::Unit::Meter) noexcept
Sets the size of the GameObject in the game world.
const helios::math::vec3f & position () const noexcept
Returns a ref to the current position of the GameObject in local coordinates.
const helios::math::vec2f & steeringInput () const noexcept
Returns a const ref to the current steering input vector.
float throttle () const noexcept
Returns the current throttle value.
const helios::math::vec3f & velocity () const noexcept
Returns a const ref to the current velocity vector.
virtual float speedRatio () const noexcept
Returns the current speed as a ratio of maximum speed.
virtual void update (float deltaTime)=0
Updates the GameObject state for the current frame.
const helios::util::Guid & guid () const noexcept
Returns the unique identifier of this GameObject.
GameObject & setScale (const helios::math::vec3f &scale) noexcept
Applies a scaling transformation to the GameObject.
GameObject & setRotation (const helios::math::mat4f &rotation) noexcept
Applies a rotation transformation to the GameObject.
GameObject & setTranslation (const helios::math::vec3f &translation) noexcept
Applies a translation transformation to the GameObject.
Protected Attributes
const helios::math::vec3f canonicalSize_ {}
Canonical size of the GameObject.
helios::util::Guid guid_
Unique identifier for this GameObject.
helios::scene::Transform * transform_
Pointer to the SceneNode's transform component.
helios::math::vec3f velocity_ {}
The current velocity-vector, if any.
helios::math::vec3f position_ {}
The current position-vector in local coordinates (model space).
helios::math::vec2f steeringInput_ {}
The current steeringInput-vector, if any.
float throttle_ = 0.0f
Normalized value for the throttle, if any.
Detailed Description
Base class representing an interactive game entity in the game world.
The `GameObject` provides a game-logic-level abstraction over a `SceneNode`. It serves as the primary building block for game-specific entities like players or enemies, designed to be subclassed to add further behavior. Each `GameObject` has a unique `Guid` for easy identification and provides convenient methods for manipulating the transform of its underlying `SceneNode`. It also acts as the target for `Command` execution.
Example usage: ```cpp class Player : public helios::engine::game::GameObject { public: using GameObject::GameObject;
void jump() { setTranslation({0.0f, 5.0f, 0.0f}); } };
auto sceneNode = std::make_shared<helios::scene::SceneNode>(); auto player = std::make_unique<Player>(sceneNode.get()); player->setTranslation({1.0f, 0.0f, 0.0f}); ```
Warning
The GameObject does NOT own the SceneNode. The caller must ensure the SceneNode outlives the GameObject. If the SceneNode is destroyed while the GameObject is still alive, all transform operations will result in undefined behavior.
Todo
Implement observer pattern or weak_ptr to detect SceneNode destruction and invalidate the transform pointer to prevent dangling pointer issues.
Definition at line 49 of file GameObject.ixx.
Constructor & Destructor Documentation
GameObject()
helios::engine::game::GameObject::GameObject (helios::scene::SceneNode * sceneNode) explicit export
Constructs a GameObject associated with a SceneNode.
Parameters
sceneNode Pointer to the SceneNode this GameObject wraps. Must not be null.
Precondition
sceneNode != nullptr
Note
The GameObject does NOT take ownership of the SceneNode. The caller is responsible for ensuring the SceneNode outlives this GameObject.
A unique Guid is automatically generated during construction.
Warning
Passing a null sceneNode will result in undefined behavior when accessing transform methods. In debug builds, this should trigger an assertion.
Referenced by setRotation(), setScale(), setSize(), and setTranslation().
~GameObject()
virtual helios::engine::game::GameObject::~GameObject () export virtual default
Virtual destructor to ensure proper cleanup of derived classes.
Member Function Documentation
guid()
const helios::util::Guid & helios::engine::game::GameObject::guid () const nodiscard export noexcept
Returns the unique identifier of this GameObject.
Returns
Const reference to the GameObject's Guid.
Note
The Guid is generated during construction and never changes.
References guid().
Referenced by guid().
position()
const helios::math::vec3f & helios::engine::game::GameObject::position () const nodiscard export noexcept
Returns a ref to the current position of the GameObject in local coordinates.
Returns
The position vector in model space (local).
setRotation()
GameObject & helios::engine::game::GameObject::setRotation (const helios::math::mat4f & rotation) export noexcept
Applies a rotation transformation to the GameObject.
Parameters
rotation The rotation matrix to apply.
Returns
Reference to this GameObject for method chaining.
Note
This modifies the underlying SceneNode's local transform.
Warning
If the SceneNode has been destroyed, this will cause undefined behavior.
References GameObject(), and setRotation().
Referenced by setRotation().
setScale()
GameObject & helios::engine::game::GameObject::setScale (const helios::math::vec3f & scale) export noexcept
Applies a scaling transformation to the GameObject.
Parameters
scale The scale vector to apply (x, y, z components).
Returns
Reference to this GameObject for method chaining.
Note
This modifies the underlying SceneNode's local transform.
Warning
If the SceneNode has been destroyed, this will cause undefined behavior.
References GameObject(), and setScale().
Referenced by setScale().
setSize()
GameObject & helios::engine::game::GameObject::setSize (float width, float height, float depth, helios::core::units::Unit unit = helios::core::units::Unit::Meter) export noexcept
Sets the size of the GameObject in the game world.
Parameters
width The width of the GameObject, specified in the given unit.
height The height of the GameObject, specified in the given unit.
depth The depth of the GameObject, specified in the given unit.
unit The unit of measurement for the size (default is meters).
Returns
Reference to this GameObject for method chaining.
Note
The size is applied to the underlying SceneNode's transform.
Warning
If the associated SceneNode is destroyed, calling this method will result in undefined behavior.
References GameObject(), and helios::core::units::Meter.
setTranslation()
GameObject & helios::engine::game::GameObject::setTranslation (const helios::math::vec3f & translation) export noexcept
Applies a translation transformation to the GameObject.
Parameters
translation The translation vector to apply (x, y, z components).
Returns
Reference to this GameObject for method chaining.
Note
This modifies the underlying SceneNode's local transform.
Warning
If the SceneNode has been destroyed, this will cause undefined behavior.
References GameObject(), and setTranslation().
Referenced by setTranslation().
speedRatio()
virtual float helios::engine::game::GameObject::speedRatio () const nodiscard export virtual noexcept
Returns the current speed as a ratio of maximum speed.
Returns
A value between 0.0 (stationary) and 1.0 (maximum speed).
This ratio can be used for UI elements (e.g., speedometer), audio effects (e.g., engine pitch), or visual effects that scale with velocity. Derived classes should override this method to provide entity-specific speed calculations.
References speedRatio().
Referenced by speedRatio().
steeringInput()
const helios::math::vec2f & helios::engine::game::GameObject::steeringInput () const nodiscard export noexcept
Returns a const ref to the current steering input vector.
Returns
The normalized direction vector representing input from controls.
This vector indicates the desired movement direction as provided by the player or AI controller. A zero vector indicates no input.
References steeringInput().
Referenced by steeringInput().
throttle()
float helios::engine::game::GameObject::throttle () const nodiscard export noexcept
Returns the current throttle value.
Returns
A normalized value between 0.0 (idle) and 1.0 (full throttle).
Represents the intensity of the movement input, typically derived from analog stick magnitude or key press duration.
References throttle().
Referenced by throttle().
update()
virtual void helios::engine::game::GameObject::update (float deltaTime) export pure virtual
Updates the GameObject state for the current frame.
Parameters
deltaTime Time elapsed since the last frame, in seconds.
Note
Derived classes must implement this method to define frame-by-frame behavior such as physics updates, animation, AI logic, or other time-dependent state changes.
Called once per frame by the GameWorld during its update cycle.
References update().
Referenced by update().
velocity()
const helios::math::vec3f & helios::engine::game::GameObject::velocity () const nodiscard export noexcept
Returns a const ref to the current velocity vector.
Returns
The velocity vector in units per second.
Represents the current movement direction and speed of the GameObject in world space.
References velocity().
Referenced by velocity().
The documentation for this class was generated from the following file:
include/helios/engine/game/GameObject.ixx