helios: helios::input::GamepadState Class Reference
helios::input::GamepadState Class Reference export
module helios.input.GamepadState
A lightweight class for transferring the state of a Gamepad.
Public Member Functions
~GamepadState ()=default
GamepadState ()=default
Default constructor.
GamepadState (const float axisLeftX, const float axisLeftY, const float axisRightX, const float axisRightY, const float triggerLeft, const float triggerRight, const bool buttonA, const bool buttonB, const bool buttonX, const bool buttonY, const bool buttonStart, const bool buttonBack, const bool buttonGuide, const bool buttonLeftBumper, const bool buttonRightBumper, const bool buttonLeftThumb, const bool buttonRightThumb, const bool buttonDpadUp, const bool buttonDpadRight, const bool buttonDpadDown, const bool buttonDpadLeft) noexcept
Creates a new GamepadState object.
void updateAxes (const float axisLeftX, const float axisLeftY, const float axisRightX, const float axisRightY, const float triggerLeft, const float triggerRight, const bool buttonA, const bool buttonB, const bool buttonX, const bool buttonY, const bool buttonStart, const bool buttonBack, const bool buttonGuide, const bool buttonLeftBumper, const bool buttonRightBumper, const bool buttonLeftThumb, const bool buttonRightThumb, const bool buttonDpadUp, const bool buttonDpadRight, const bool buttonDpadDown, const bool buttonDpadLeft) noexcept
Updates the axes and button states of this GamepadState object.
float leftX () const noexcept
Returns the current value of the left stick's x-axis.
float leftY () const noexcept
Returns the current value of the left stick's y-axis.
float rightX () const noexcept
Returns the current value of the right stick's x-axis.
float rightY () const noexcept
Returns the current value of the right stick's y-axis.
float triggerLeft () const noexcept
Returns the current value of the left trigger.
float triggerRight () const noexcept
Returns the current value of the right trigger.
helios::math::vec2f left () const noexcept
Returns the state of the left stick as a helios::math::vec2f.
helios::math::vec2f right () const noexcept
Returns the state of the right stick as a helios::math::vec2f.
helios::math::vec2f trigger () const noexcept
Returns the state of the triggers as a helios::math::vec2f.
bool buttonA () const noexcept
Returns true when the A button is pressed.
bool buttonB () const noexcept
Returns true when the B button is pressed.
bool buttonX () const noexcept
Returns true when the X button is pressed.
bool buttonY () const noexcept
Returns true when the Y button is pressed.
bool buttonStart () const noexcept
Returns true when the Start button is pressed.
bool buttonBack () const noexcept
Returns true when the Back button is pressed.
bool buttonGuide () const noexcept
Returns true when the Guide button is pressed.
bool buttonLeftBumper () const noexcept
Returns true when the left bumper is pressed.
bool buttonRightBumper () const noexcept
Returns true when the right bumper is pressed.
bool buttonLeftThumb () const noexcept
Returns true when the left thumbstick button is pressed.
bool buttonRightThumb () const noexcept
Returns true when the right thumbstick button is pressed.
bool buttonDpadUp () const noexcept
Returns true when the D-pad Up button is pressed.
bool buttonDpadRight () const noexcept
Returns true when the D-pad Right button is pressed.
bool buttonDpadDown () const noexcept
Returns true when the D-pad Down button is pressed.
bool buttonDpadLeft () const noexcept
Returns true when the D-pad Left button is pressed.
Detailed Description
A lightweight class for transferring the state of a Gamepad.
This class models a reusable object representing the input state of a gamepad. The input state of a gamepad consists of the state of the left and right trigger, ranging from [0, 1], where 1 means fully pressed and 0 means not pressed at all.
Similarly, a GamepadState provides information about the left and the right gamepad axes. Both the x- and the y-axis range from [-1, 1]. For the x-axis, the following holds:
0.00 => not moved at all
-1.00 => moved all the way to the left
1.00 => moved all the way to the right
For the y-axis the positive direction corresponds to "up" and the negative direction corresponds to "down".
Updating the values is done by calling `updateAxes` on this object.
For convenient access of the axes in 2D coordinates, the class provides accessors to the sticks' axes in `vec2f` form.
Button states are generally represented with boolean values, i.e. true for pressed, otherwise false.
Note
Implementations must account for joystick drift: achieving exactly 0.0 for x/y when no human input occurred is rare. Consider applying a dead zone when processing the GamepadState. Axis values are individually clipped to [-1.0, 1.0], but the magnitude of the resulting (x, y) vector may exceed 1.0. Applications should normalize input vectors where appropriate and possibly offer calibration.
This implementation is inspired by the GLFW gamepad input model.
See also
https://www.glfw.org/docs/latest/input_guide.html#joystick
Definition at line 53 of file GamepadState.ixx.
Constructor & Destructor Documentation
~GamepadState()
helios::input::GamepadState::~GamepadState () export default
GamepadState() [1/2]
helios::input::GamepadState::GamepadState () export default
Default constructor.
Initializes all the values with 0.0f.
GamepadState() [2/2]
helios::input::GamepadState::GamepadState (const float axisLeftX, const float axisLeftY, const float axisRightX, const float axisRightY, const float triggerLeft, const float triggerRight, const bool buttonA, const bool buttonB, const bool buttonX, const bool buttonY, const bool buttonStart, const bool buttonBack, const bool buttonGuide, const bool buttonLeftBumper, const bool buttonRightBumper, const bool buttonLeftThumb, const bool buttonRightThumb, const bool buttonDpadUp, const bool buttonDpadRight, const bool buttonDpadDown, const bool buttonDpadLeft) inline explicit export noexcept
Creates a new GamepadState object.
Delegates to `updateAxes` for value initialization.
See also
updateAxes
Definition at line 217 of file GamepadState.ixx.
References buttonA(), buttonB(), buttonBack(), buttonDpadDown(), buttonDpadLeft(), buttonDpadRight(), buttonDpadUp(), buttonGuide(), buttonLeftBumper(), buttonLeftThumb(), buttonRightBumper(), buttonRightThumb(), buttonStart(), buttonX(), buttonY(), triggerLeft(), triggerRight(), and updateAxes().
Member Function Documentation
buttonA()
bool helios::input::GamepadState::buttonA () const inline nodiscard export noexcept
Returns true when the A button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 434 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonB()
bool helios::input::GamepadState::buttonB () const inline nodiscard export noexcept
Returns true when the B button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 443 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonBack()
bool helios::input::GamepadState::buttonBack () const inline nodiscard export noexcept
Returns true when the Back button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 479 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonDpadDown()
bool helios::input::GamepadState::buttonDpadDown () const inline nodiscard export noexcept
Returns true when the D-pad Down button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 551 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonDpadLeft()
bool helios::input::GamepadState::buttonDpadLeft () const inline nodiscard export noexcept
Returns true when the D-pad Left button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 560 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonDpadRight()
bool helios::input::GamepadState::buttonDpadRight () const inline nodiscard export noexcept
Returns true when the D-pad Right button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 542 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonDpadUp()
bool helios::input::GamepadState::buttonDpadUp () const inline nodiscard export noexcept
Returns true when the D-pad Up button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 533 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonGuide()
bool helios::input::GamepadState::buttonGuide () const inline nodiscard export noexcept
Returns true when the Guide button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 488 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonLeftBumper()
bool helios::input::GamepadState::buttonLeftBumper () const inline nodiscard export noexcept
Returns true when the left bumper is pressed.
Returns
true if pressed, false otherwise.
Definition at line 497 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonLeftThumb()
bool helios::input::GamepadState::buttonLeftThumb () const inline nodiscard export noexcept
Returns true when the left thumbstick button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 515 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonRightBumper()
bool helios::input::GamepadState::buttonRightBumper () const inline nodiscard export noexcept
Returns true when the right bumper is pressed.
Returns
true if pressed, false otherwise.
Definition at line 506 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonRightThumb()
bool helios::input::GamepadState::buttonRightThumb () const inline nodiscard export noexcept
Returns true when the right thumbstick button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 524 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonStart()
bool helios::input::GamepadState::buttonStart () const inline nodiscard export noexcept
Returns true when the Start button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 470 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonX()
bool helios::input::GamepadState::buttonX () const inline nodiscard export noexcept
Returns true when the X button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 452 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
buttonY()
bool helios::input::GamepadState::buttonY () const inline nodiscard export noexcept
Returns true when the Y button is pressed.
Returns
true if pressed, false otherwise.
Definition at line 461 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
left()
helios::math::vec2f helios::input::GamepadState::left () const inline nodiscard export noexcept
Returns the state of the left stick as a helios::math::vec2f.
Returns
A helios::math::vec2f, with the first component being the x-axis, the second component the y-axis.
Definition at line 395 of file GamepadState.ixx.
leftX()
float helios::input::GamepadState::leftX () const inline nodiscard export noexcept
Returns the current value of the left stick's x-axis.
Returns
float value in the range [-1, 1]
Definition at line 335 of file GamepadState.ixx.
leftY()
float helios::input::GamepadState::leftY () const inline nodiscard export noexcept
Returns the current value of the left stick's y-axis.
Returns
float value in the range [-1, 1]
Definition at line 345 of file GamepadState.ixx.
right()
helios::math::vec2f helios::input::GamepadState::right () const inline nodiscard export noexcept
Returns the state of the right stick as a helios::math::vec2f.
Returns
A helios::math::vec2f, with the first component being the x-axis, the second component the y-axis.
Definition at line 408 of file GamepadState.ixx.
rightX()
float helios::input::GamepadState::rightX () const inline nodiscard export noexcept
Returns the current value of the right stick's x-axis.
Returns
float value in the range [-1, 1]
Definition at line 355 of file GamepadState.ixx.
rightY()
float helios::input::GamepadState::rightY () const inline nodiscard export noexcept
Returns the current value of the right stick's y-axis.
Returns
float value in the range [-1, 1]
Definition at line 365 of file GamepadState.ixx.
trigger()
helios::math::vec2f helios::input::GamepadState::trigger () const inline nodiscard export noexcept
Returns the state of the triggers as a helios::math::vec2f.
Returns
A helios::math::vec2f, with the first component being the left trigger-axis, the second component the right trigger-axis.
Definition at line 422 of file GamepadState.ixx.
triggerLeft()
float helios::input::GamepadState::triggerLeft () const inline nodiscard export noexcept
Returns the current value of the left trigger.
Returns
float value in the range [0, 1]
Definition at line 375 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
triggerRight()
float helios::input::GamepadState::triggerRight () const inline nodiscard export noexcept
Returns the current value of the right trigger.
Returns
float value in the range [0, 1]
Definition at line 385 of file GamepadState.ixx.
Referenced by GamepadState(), and updateAxes().
updateAxes()
void helios::input::GamepadState::updateAxes (const float axisLeftX, const float axisLeftY, const float axisRightX, const float axisRightY, const float triggerLeft, const float triggerRight, const bool buttonA, const bool buttonB, const bool buttonX, const bool buttonY, const bool buttonStart, const bool buttonBack, const bool buttonGuide, const bool buttonLeftBumper, const bool buttonRightBumper, const bool buttonLeftThumb, const bool buttonRightThumb, const bool buttonDpadUp, const bool buttonDpadRight, const bool buttonDpadDown, const bool buttonDpadLeft) inline export noexcept
Updates the axes and button states of this GamepadState object.
This method updates raw axis and trigger values and stores the boolean state of all standard gamepad buttons. Float parameters are asserted to be in their expected ranges and then clamped.
For the sticks' range [-1, 1] the following holds: -1 means moved all the way left/down, 0 means not moved at all, 1 means moved all the way right/up.
For the triggers' range of [0, 1] the following holds: 0 means not pressed, 1 means fully pressed.
Parameters
axisLeftX The x-axis of the left stick, expected in [-1, 1].
axisLeftY The y-axis of the left stick, expected in [-1, 1].
axisRightX The x-axis of the right stick, expected in [-1, 1].
axisRightY The y-axis of the right stick, expected in [-1, 1].
triggerLeft The left trigger value, expected in [0, 1].
triggerRight The right trigger value, expected in [0, 1].
buttonA True if the A button is pressed.
buttonB True if the B button is pressed.
buttonX True if the X button is pressed.
buttonY True if the Y button is pressed.
buttonStart True if the Start button is pressed.
buttonBack True if the Back button is pressed.
buttonGuide True if the Guide (platform) button is pressed.
buttonLeftBumper True if the left bumper is pressed.
buttonRightBumper True if the right bumper is pressed.
buttonLeftThumb True if the left thumbstick button is pressed.
buttonRightThumb True if the right thumbstick button is pressed.
buttonDpadUp True if the D-pad Up button is pressed.
buttonDpadRight True if the D-pad Right button is pressed.
buttonDpadDown True if the D-pad Down button is pressed.
buttonDpadLeft True if the D-pad Left button is pressed.
Definition at line 272 of file GamepadState.ixx.
References buttonA(), buttonB(), buttonBack(), buttonDpadDown(), buttonDpadLeft(), buttonDpadRight(), buttonDpadUp(), buttonGuide(), buttonLeftBumper(), buttonLeftThumb(), buttonRightBumper(), buttonRightThumb(), buttonStart(), buttonX(), buttonY(), triggerLeft(), and triggerRight().
Referenced by GamepadState().
The documentation for this class was generated from the following file:
include/helios/input/GamepadState.ixx