helios: helios::app::Application Class Reference
helios::app::Application Class Reference abstract export
module helios.app.Application
Class providing the entry point for a helios application.
Public Member Functions
virtual ~Application ()=default
Application (std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice, std::unique_ptr< helios::input::InputManager > inputManager, std::unique_ptr< helios::event::EventManager > eventManager)
Creates a new application instance.
void addController (std::unique_ptr< helios::app::controller::Controller > controller) noexcept
Registers a new controller with this application.
virtual helios::window::Window & createWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const helios::window::WindowConfig &cfg)=0
Creates the container for the native window and performs all necessary steps to properly initialize it.
virtual void init ()
Initializes the application.
virtual void setCurrent (helios::window::Window &win)=0
Sets the application's active window.
bool hasWindow (const helios::window::Window &win) const noexcept
Returns true if the specified window is owned by this application, otherwise false.
virtual helios::window::Window * current () const noexcept=0
Returns the currently focused window, or nullptr if none exists or no window is being treated as current.
helios::input::InputManager & inputManager () const
Returns the input manager owned by this application.
helios::rendering::RenderingDevice & renderingDevice () const
Returns the rendering device owned by this application.
helios::event::EventManager & eventManager () const
Returns the event manager owned by this application.
Protected Attributes
bool initialized_ = false
Flag indicating whether the application has been initialized.
std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice_
The rendering device owned by this application.
std::unique_ptr< input::InputManager > inputManager_
The input manager owned by this application.
std::unique_ptr< event::EventManager > eventManager_
The event manager owned by this application.
std::list< std::unique_ptr< helios::window::Window > > windowList_
A list containing all windows managed by this application.
std::vector< std::unique_ptr< helios::app::controller::Controller > > controllers_
Collection of controllers registered with this application.
Static Protected Attributes
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Shared logger instance for all Application objects.
Detailed Description
Class providing the entry point for a helios application.
`Application` serves as the central hub for the helios framework, offering convenient access and management for key subsystems such as the EventManager, the InputManager and the RenderingDevice.
It also allows for the registration of `helios.app.controller.Controller`s, which can provide specialized logic and management for the various subsystems and related events.
Definition at line 36 of file Application.ixx.
Constructor & Destructor Documentation
~Application()
virtual helios::app::Application::~Application () export virtual default
Todo
free resource allocations from renderingDevice, window and InputManager
Application()
helios::app::Application::Application (std::unique_ptr< helios::rendering::RenderingDevice > renderingDevice, std::unique_ptr< helios::input::InputManager > inputManager, std::unique_ptr< helios::event::EventManager > eventManager) explicit export
Creates a new application instance.
The application will take ownership of the specified constructor arguments.
Parameters
renderingDevice Unique rendering device owned by the application.
inputManager Unique input manager instance.
eventManager Unique event manager instance.
References eventManager(), inputManager(), and renderingDevice().
Member Function Documentation
addController()
void helios::app::Application::addController (std::unique_ptr< helios::app::controller::Controller > controller) export noexcept
Registers a new controller with this application.
Makes sure that the controller subscribes to the event manager's dispatcher of this application. The application receives ownership of the specified controller.
Parameters
controller Unique pointer to the controller to add.
createWindow()
virtual helios::window::Window & helios::app::Application::createWindow (std::unique_ptr< helios::rendering::RenderTarget > renderTarget, const helios::window::WindowConfig & cfg) nodiscard export pure virtual
Creates the container for the native window and performs all necessary steps to properly initialize it.
Parameters
renderTarget Render target that wraps the framebuffer used by the window.
cfg Window configuration defining properties such as title, dimensions, and hints.
Returns
Reference to the created window instance.
Exceptions
std::invalid_argument If the configuration was invalid.
Implemented in helios::ext::glfw::app::GLFWApplication.
current()
virtual helios::window::Window * helios::app::Application::current () const nodiscard export pure virtual noexcept
Returns the currently focused window, or nullptr if none exists or no window is being treated as current.
Returns
Pointer to the current window, or nullptr if none is active.
Implemented in helios::ext::glfw::app::GLFWApplication.
eventManager()
helios::event::EventManager & helios::app::Application::eventManager () const inline nodiscard export
Returns the event manager owned by this application.
Returns
Reference to the event manager instance.
Definition at line 190 of file Application.ixx.
References eventManager_.
Referenced by Application(), and helios::ext::glfw::app::GLFWApplication::GLFWApplication().
hasWindow()
bool helios::app::Application::hasWindow (const helios::window::Window & win) const nodiscard export noexcept
Returns true if the specified window is owned by this application, otherwise false.
Parameters
win The window to look up in this application's window list.
Returns
True if the window is owned by this application, otherwise false.
init()
virtual void helios::app::Application::init () export virtual
Initializes the application.
Performs any bootstrapping necessary for this application and provides an idiomatic entry point for APIs using this application. This method ensures that all controllers are initialized and subscribe to this application's event manager dispatcher.
Exceptions
std::runtime_error If the application was already initialized.
Reimplemented in helios::ext::glfw::app::GLFWApplication.
inputManager()
helios::input::InputManager & helios::app::Application::inputManager () const inline nodiscard export
Returns the input manager owned by this application.
Returns
Reference to the input manager instance.
Definition at line 172 of file Application.ixx.
References inputManager(), and inputManager_.
Referenced by Application(), helios::ext::glfw::app::GLFWApplication::GLFWApplication(), and inputManager().
renderingDevice()
helios::rendering::RenderingDevice & helios::app::Application::renderingDevice () const inline nodiscard export
Returns the rendering device owned by this application.
Returns
Reference to the rendering device instance.
Definition at line 181 of file Application.ixx.
References renderingDevice_.
Referenced by Application(), and helios::ext::glfw::app::GLFWApplication::GLFWApplication().
setCurrent()
virtual void helios::app::Application::setCurrent (helios::window::Window & win) export pure virtual
Sets the application's active window.
Advises the input manager to poll this window's events.
Parameters
win Reference to the window that becomes the current active window.
Implemented in helios::ext::glfw::app::GLFWApplication.
The documentation for this class was generated from the following file:
include/helios/app/Application.ixx