helios: helios::input::gamepad::DeadzoneStrategy Class Reference
helios::input::gamepad::DeadzoneStrategy Class Reference abstract export
module helios.input.gamepad.DeadzoneStrategy
Abstract strategy interface for normalizing gamepad stick input with deadzone handling.
Public Member Functions
virtual ~DeadzoneStrategy ()=default
Virtual destructor for proper polymorphic cleanup.
DeadzoneStrategy ()=default
Default constructor.
DeadzoneStrategy (float stickNoiseThreshold)
Interface for applying deadzone handling to gamepad stick input.
virtual void normalize (float deadzone, float &x, float &y) const noexcept=0
Normalizes stick input values based on the configured deadzone.
float stickNoiseThreshold () const noexcept
Retrieves the current noise threshold for stick input.
void setStickNoiseThreshold (float threshold) noexcept
Sets the noise threshold for stick inputs to handle minor hardware drift.
Static Public Attributes
static constexpr float DEFAULT_STICK_NOISE_THRESHOLD = 0.002f
Default threshold used to filter out minor noise in gamepad stick input.
Protected Attributes
float stickNoiseThreshold_ = DEFAULT_STICK_NOISE_THRESHOLD
Threshold used to filter out minor noise in gamepad stick input.
Detailed Description
Abstract strategy interface for normalizing gamepad stick input with deadzone handling.
Gamepad analog sticks rarely return exactly (0, 0) when at rest due to hardware drift. A deadzone defines a threshold below which input is ignored. Implementations of this interface define how input values are normalized once they exceed the deadzone threshold.
See also
RadialDeadzoneStrategy for a circular deadzone implementation.
Definition at line 21 of file DeadzoneStrategy.ixx.
Constructor & Destructor Documentation
~DeadzoneStrategy()
virtual helios::input::gamepad::DeadzoneStrategy::~DeadzoneStrategy () export virtual default
Virtual destructor for proper polymorphic cleanup.
DeadzoneStrategy() [1/2]
helios::input::gamepad::DeadzoneStrategy::DeadzoneStrategy () export default
Default constructor.
Referenced by helios::input::gamepad::RadialDeadzoneStrategy::RadialDeadzoneStrategy(), and helios::input::gamepad::RadialDeadzoneStrategy::RadialDeadzoneStrategy().
DeadzoneStrategy() [2/2]
helios::input::gamepad::DeadzoneStrategy::DeadzoneStrategy (float stickNoiseThreshold) inline export
Interface for applying deadzone handling to gamepad stick input.
Defines a method for processing and normalizing analog stick input while accounting for a deadzone. A deadzone eliminates unintended small input values caused by hardware imperfections. Implementations of this interface provide specific strategies for handling the deadzone and input normalization.
See also
AxisDeadzoneStrategy for an axis-aligned deadzone implementation.
Definition at line 63 of file DeadzoneStrategy.ixx.
References stickNoiseThreshold(), and stickNoiseThreshold_.
Member Function Documentation
normalize()
virtual void helios::input::gamepad::DeadzoneStrategy::normalize (float deadzone, float & x, float & y) const export pure virtual noexcept
Normalizes stick input values based on the configured deadzone.
This method modifies the input coordinates in-place. Values within the deadzone are typically zeroed out, while values outside are scaled to provide a smooth response curve from the edge of the deadzone to the maximum input value.
Parameters
deadzone The deadzone threshold in the range [0.0, 1.0].
x Reference to the x-axis value, modified in-place.
y Reference to the y-axis value, modified in-place.
Implemented in helios::input::gamepad::RadialDeadzoneStrategy.
setStickNoiseThreshold()
void helios::input::gamepad::DeadzoneStrategy::setStickNoiseThreshold (float threshold) export noexcept
Sets the noise threshold for stick inputs to handle minor hardware drift.
The noise threshold defines the minimum magnitude for stick input to be considered valid. Inputs with a magnitude below this threshold are ignored to prevent unintentional movement caused by hardware noise or drift.
Parameters
threshold The new stick noise threshold, typically in the range [0.0, 1.0].
References setStickNoiseThreshold().
Referenced by setStickNoiseThreshold().
stickNoiseThreshold()
float helios::input::gamepad::DeadzoneStrategy::stickNoiseThreshold () const nodiscard export noexcept
Retrieves the current noise threshold for stick input.
The noise threshold determines the minimum magnitude of input required to be processed as valid. Values below this threshold are considered noise and ignored to prevent unintentional drift detection.
Returns
The configured noise threshold value.
Referenced by DeadzoneStrategy(), and helios::input::gamepad::RadialDeadzoneStrategy::RadialDeadzoneStrategy().
The documentation for this class was generated from the following file:
include/helios/input/gamepad/DeadzoneStrategy.ixx