helios: helios::rendering::RenderPass Class Reference
helios::rendering::RenderPass Class Reference export
module helios.rendering.RenderPass
Represents a single RenderPass under a set of specific uniform values.
Public Member Functions
~RenderPass ()=default
RenderPass (const RenderPass &)=delete
Prevent copying. A RenderPass is not intended to be copied.
RenderPass & operator= (const RenderPass &)=delete
Prevent copy assignment. A RenderPass is not intended to be copied.
RenderPass (RenderPass &&) noexcept=delete
Prevent move.
RenderPass & operator= (RenderPass &&) noexcept=delete
Prevent move assignment.
RenderPass (std::shared_ptr< const helios::rendering::Viewport > viewport, std::unique_ptr< helios::rendering::RenderQueue > renderQueue, std::unique_ptr< const helios::rendering::shader::UniformValueMap > frameUniformValues=nullptr) noexcept
Create a new `RenderPass` with the specified `Viewport`, `RenderQueue` and the `UniformValueMap`. Ownership of Viewport is shared with this instance, the latter objects are transferred to **this** `RenderPass`.
const RenderQueue & renderQueue () const noexcept
Returns a const ref to the `RenderQueue` this `RenderPass` holds.
const Viewport & viewport () const noexcept
Returns a const ref to the `Viewport` this `RenderPass` holds.
void setFrameUniformValues (std::unique_ptr< const helios::rendering::shader::UniformValueMap > frameUniformValues) noexcept
Sets this `RenderPass`' `UniformValueMap` containing per-frame specific uniform values. Transfers ownership of the provided UniformValueMap to this `RenderPass`.
const helios::rendering::shader::UniformValueMap & frameUniformValues () const noexcept
Returns a const reference to this `RenderPass`' `UniformValueMap`.
Static Protected Attributes
static const helios::util::log::Logger & logger_
Shared logger instance for all RenderPass objects.
Detailed Description
Represents a single RenderPass under a set of specific uniform values.
A `RenderPass` holds a `RenderQueue` that contains all `RenderCommands` that need to be processed in the subsequent rendering. The associated uniform values specified with this `RenderPass` remain constant during processing of the `RenderCommand`s.
`RenderPass`es are typically processed sequentially by an API-specific implementation of the pure virtual `RenderingDevice` class.
Note
A `RenderPass` should be configurable with other properties relevant to the underlying rendering backend, e.g. depth testing, draw mode etc.
Definition at line 35 of file RenderPass.ixx.
Constructor & Destructor Documentation
~RenderPass()
helios::rendering::RenderPass::~RenderPass () export default
RenderPass() [1/3]
helios::rendering::RenderPass::RenderPass (const RenderPass &) export delete
Prevent copying. A RenderPass is not intended to be copied.
References RenderPass().
Referenced by operator=(), operator=(), RenderPass(), RenderPass(), and RenderPass().
RenderPass() [2/3]
helios::rendering::RenderPass::RenderPass (RenderPass &&) export delete noexcept
Prevent move.
References RenderPass().
RenderPass() [3/3]
helios::rendering::RenderPass::RenderPass (std::shared_ptr< const helios::rendering::Viewport > viewport, std::unique_ptr< helios::rendering::RenderQueue > renderQueue, std::unique_ptr< const helios::rendering::shader::UniformValueMap > frameUniformValues = nullptr) explicit export noexcept
Create a new `RenderPass` with the specified `Viewport`, `RenderQueue` and the `UniformValueMap`. Ownership of Viewport is shared with this instance, the latter objects are transferred to **this** `RenderPass`.
Parameters
viewport The viewport this RenderPass is processing.
renderQueue A unique ptr to the `RenderQueue` that should be processed with this pass.
frameUniformValues A unique ptr to the `UniformValueMap` associated with this pass, i.e. frame-specific uniform values. If no values are specified, a default empty set is created.
References frameUniformValues(), RenderPass(), renderQueue(), and viewport().
Member Function Documentation
frameUniformValues()
const helios::rendering::shader::UniformValueMap & helios::rendering::RenderPass::frameUniformValues () const nodiscard export noexcept
Returns a const reference to this `RenderPass`' `UniformValueMap`.
The map might be empty.
Returns
A const reference to this `RenderPass`' `UniformValueMap` for the current frame.
References frameUniformValues().
Referenced by frameUniformValues(), RenderPass(), and setFrameUniformValues().
operator=() [1/2]
RenderPass & helios::rendering::RenderPass::operator= (const RenderPass &) export delete
Prevent copy assignment. A RenderPass is not intended to be copied.
References RenderPass().
operator=() [2/2]
RenderPass & helios::rendering::RenderPass::operator= (RenderPass &&) export delete noexcept
Prevent move assignment.
References RenderPass().
renderQueue()
const RenderQueue & helios::rendering::RenderPass::renderQueue () const nodiscard export noexcept
Returns a const ref to the `RenderQueue` this `RenderPass` holds.
Returns
A const ref to this `RenderPass`' `RenderQueue`.
References renderQueue().
Referenced by RenderPass(), and renderQueue().
setFrameUniformValues()
void helios::rendering::RenderPass::setFrameUniformValues (std::unique_ptr< const helios::rendering::shader::UniformValueMap > frameUniformValues) export noexcept
Sets this `RenderPass`' `UniformValueMap` containing per-frame specific uniform values. Transfers ownership of the provided UniformValueMap to this `RenderPass`.
Parameters
frameUniformValues A unique ptr to the `UniformValueMap` for frame specific uniform values.
References frameUniformValues(), and setFrameUniformValues().
Referenced by setFrameUniformValues().
viewport()
const Viewport & helios::rendering::RenderPass::viewport () const nodiscard export noexcept
Returns a const ref to the `Viewport` this `RenderPass` holds.
Returns
A const ref to this `RenderPass`' `Viewport`.
References viewport().
Referenced by RenderPass(), and viewport().
The documentation for this class was generated from the following file:
include/helios/rendering/RenderPass.ixx