helios: helios::rendering::model::Material Class Reference
helios::rendering::model::Material Class Reference final export
module helios.rendering.model.Material
Represents a parameterizable material.
Public Member Functions
virtual ~Material ()=default
Material (std::shared_ptr< const helios::rendering::shader::Shader > shader, std::shared_ptr< const helios::rendering::model::config::MaterialProperties > materialProperties)
Creates a new Material.
const helios::rendering::model::config::MaterialProperties & materialProperties () const noexcept
Returns a const reference to the underlying MaterialProperties.
const helios::rendering::shader::Shader & shader () const noexcept
Returns a const ref to the shader used by this instance.
void writeUniformValues (helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept
Writes this Material's uniform values into the given map.
Protected Member Functions
Material ()=default
Protected Attributes
std::shared_ptr< const helios::rendering::model::config::MaterialProperties > materialProperties_
Shared pointer for the raw, immutable MaterialProperties.
std::shared_ptr< const helios::rendering::shader::Shader > shader_ {}
Shared pointer to the immutable Shader.
Static Protected Attributes
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Shared logger instance for all Material objects.
Detailed Description
Represents a parameterizable material.
A Material contains a reference to a shared, immutable `Shader` and material properties used to configure the shader at draw time.
Definition at line 26 of file Material.ixx.
Constructor & Destructor Documentation
Material() [1/2]
helios::rendering::model::Material::Material () export protected default
~Material()
virtual helios::rendering::model::Material::~Material () export virtual default
Material() [2/2]
helios::rendering::model::Material::Material (std::shared_ptr< const helios::rendering::shader::Shader > shader, std::shared_ptr< const helios::rendering::model::config::MaterialProperties > materialProperties) explicit export
Creates a new Material.
Parameters
shader A shared pointer to the immutable Shader used by this instance.
materialProperties A shared pointer to the MaterialProperties for this Material.
Exceptions
std::invalid_argument if shader or materialProperties is a null shared pointer.
References materialProperties(), and shader().
Member Function Documentation
materialProperties()
const helios::rendering::model::config::MaterialProperties & helios::rendering::model::Material::materialProperties () const nodiscard export noexcept
Returns a const reference to the underlying MaterialProperties.
Returns
The const reference to this Material's MaterialProperties.
Referenced by Material().
shader()
const helios::rendering::shader::Shader & helios::rendering::model::Material::shader () const nodiscard export noexcept
Returns a const ref to the shader used by this instance.
Returns
A const ref to the Shader used by this Material.
References shader().
Referenced by Material(), shader(), and writeUniformValues().
writeUniformValues()
void helios::rendering::model::Material::writeUniformValues (helios::rendering::shader::UniformValueMap & uniformValueMap) const export noexcept
Writes this Material's uniform values into the given map.
Delegates to MaterialProperties::writeUniformValues().
Parameters
uniformValueMap Target map receiving the uniform values.
References shader(), and writeUniformValues().
Referenced by writeUniformValues().
The documentation for this class was generated from the following file:
include/helios/rendering/model/Material.ixx