helios: helios::rendering::RenderTarget Class Reference
helios::rendering::RenderTarget Class Reference export
module helios.rendering.RenderTarget
Represents a destination for rendering operations, such as a window's framebuffer.
Public Member Functions
RenderTarget ()=default
Default constructor.
RenderTarget (std::shared_ptr< helios::rendering::Viewport > viewport, unsigned int width=0, unsigned int height=0)
Constructs a RenderTarget with an initial viewport and dimensions.
std::shared_ptr< helios::rendering::Viewport > addViewport (std::shared_ptr< helios::rendering::Viewport > viewport)
Adds a viewport to this render target and establishes a parent-child relationship.
void setSize (unsigned int width, unsigned int height) noexcept
Resizes this RenderTarget to the specified dimensions and propagates the change to every viewport.
unsigned int width () const noexcept
Gets the width of the render target.
unsigned int height () const noexcept
Gets the height of the render target.
Detailed Description
Represents a destination for rendering operations, such as a window's framebuffer.
A RenderTarget encapsulates a buffer (e.g., the default framebuffer or an off-screen texture) into which a scene can be rendered. It manages one or more `Viewport` objects, which define specific rectangular areas within the target.
When the RenderTarget is resized, it notifies all its associated viewports so they can update their states accordingly (e.g., camera aspect ratio).
Todo
This implementation currently represents only the **default framebuffer**. Future extensions should allow it to represent arbitrary framebuffer objects (FBOs), using indices.
See also
glGenFramebuffers
Definition at line 31 of file RenderTarget.ixx.
Constructor & Destructor Documentation
RenderTarget() [1/2]
helios::rendering::RenderTarget::RenderTarget () export default
Default constructor.
RenderTarget() [2/2]
helios::rendering::RenderTarget::RenderTarget (std::shared_ptr< helios::rendering::Viewport > viewport, unsigned int width = 0, unsigned int height = 0) explicit export
Constructs a RenderTarget with an initial viewport and dimensions.
Parameters
viewport The default viewport for this RenderTarget. The viewport defines the rectangular area where the image is drawn.
width The initial width of the render target in pixels.
height The initial height of the render target in pixels.
Exceptions
std::invalid_argument if viewport is a nullptr.
See also
addViewport()
References height(), and width().
Member Function Documentation
addViewport()
std::shared_ptr< helios::rendering::Viewport > helios::rendering::RenderTarget::addViewport (std::shared_ptr< helios::rendering::Viewport > viewport) export
Adds a viewport to this render target and establishes a parent-child relationship.
Parameters
viewport A shared pointer to the `Viewport` to be added.
Returns
The newly added viewport as a shared pointer.
Exceptions
std::invalid_argument if viewport is a nullptr, or if the viewport already has a parent RenderTarget.
height()
unsigned int helios::rendering::RenderTarget::height () const nodiscard export noexcept
Gets the height of the render target.
Returns
The height in pixels.
References height().
Referenced by height(), RenderTarget(), and setSize().
setSize()
void helios::rendering::RenderTarget::setSize (unsigned int width, unsigned int height) export noexcept
Resizes this RenderTarget to the specified dimensions and propagates the change to every viewport.
Parameters
width The new width of the render target in pixels.
height The new height of the render target in pixels.
Todo
A LayoutManager could be introduced to manage the arrangement of multiple viewports.
See also
helios::rendering::Viewport::onRenderTargetResize()
References height(), and width().
width()
unsigned int helios::rendering::RenderTarget::width () const nodiscard export noexcept
Gets the width of the render target.
Returns
The width in pixels.
Referenced by RenderTarget(), and setSize().
The documentation for this class was generated from the following file:
include/helios/rendering/RenderTarget.ixx