helios: helios::event::EventManager Class Reference
helios::event::EventManager Class Reference abstract export
module helios.event.EventManager
An abstract EventManager managing the buffering and dispatching of events, acting as a central hub for event management.
Public Member Functions
virtual ~EventManager ()=default
EventManager (std::unique_ptr< EventQueue > eventQueue, std::unique_ptr< Dispatcher > dispatcher)
Creates a new EventManager using the specified EventQueue and Dispatcher.
EventManager & post (std::unique_ptr< const Event > event)
Posts the event to the queue using the APPEND policy, passing ownership of the event to the underlying queue.
EventManager & post (std::unique_ptr< const Event > event, PostPolicy policy)
Posts the event to the queue, passing ownership of the event to the underlying queue.
virtual EventManager & post (std::unique_ptr< const Event > event, PostPolicy policy, const std::function< bool(const std::unique_ptr< const Event > &event, const std::unique_ptr< const Event > &evt)> &func)=0
Posts the event to the underlying EventQueue using the specified policy and the specified func.
virtual EventManager & dispatchAll ()=0
Dispatches all events currently held in the event queue.
template<typename EventType>
EventManager & subscribe (std::function< void(const EventType &)> callback)
Subscribes a callback to the specified EventType.
Dispatcher & dispatcher () const noexcept
Returns a reference to the dispatcher used with this EventManager.
Protected Member Functions
EventManager ()=default
Protected Attributes
std::unique_ptr< EventQueue > eventQueue_
A unique_ptr to the EventQueue this EventManager owns.
std::unique_ptr< Dispatcher > dispatcher_
A unique_ptr to the Dispatcher this EventManager owns.
Static Protected Attributes
static const helios::util::log::Logger & logger_ = helios::util::log::LogManager::loggerForScope(HELIOS_LOG_SCOPE)
Detailed Description
An abstract EventManager managing the buffering and dispatching of events, acting as a central hub for event management.
Concrete implementations take care of `dispatchAll()`, that is, the logic for dispatching all events to the subscribed callbacks.
Definition at line 55 of file EventManager.ixx.
Constructor & Destructor Documentation
EventManager() [1/2]
helios::event::EventManager::EventManager () export protected default
Referenced by helios::event::BasicEventManager::dispatchAll(), dispatchAll(), helios::event::BasicEventManager::post(), post(), post(), post(), and subscribe().
~EventManager()
virtual helios::event::EventManager::~EventManager () export virtual default
EventManager() [2/2]
helios::event::EventManager::EventManager (std::unique_ptr< EventQueue > eventQueue, std::unique_ptr< Dispatcher > dispatcher) explicit export
Creates a new EventManager using the specified EventQueue and Dispatcher.
The EventManger takes onwership of the EventQueue and the Dispatcher.
Parameters
eventQueue
dispatcher
References dispatcher().
Member Function Documentation
dispatchAll()
virtual EventManager & helios::event::EventManager::dispatchAll () export pure virtual
Dispatches all events currently held in the event queue.
This method retrieves and removes events one by one from the underlying `EventQueue`, passing ownership to the underlying Dispatcher.
Returns
EventManager
Implemented in helios::event::BasicEventManager.
References EventManager().
dispatcher()
Dispatcher & helios::event::EventManager::dispatcher () const nodiscard export noexcept
Returns a reference to the dispatcher used with this EventManager.
Provides direct access to the dispatcher, allowing for modification of the Dispatcher, e.g. managing subscriptions.
Returns
Dispatcher
Referenced by helios::event::BasicEventManager::BasicEventManager(), and EventManager().
post() [1/3]
EventManager & helios::event::EventManager::post (std::unique_ptr< const Event > event) export
Posts the event to the queue using the APPEND policy, passing ownership of the event to the underlying queue.
Calling this function is functionally identical to calling post() with the second argument set to APPEND.
Parameters
event The event to post to the EventQueue.
Returns
EventManager
References EventManager().
post() [2/3]
EventManager & helios::event::EventManager::post (std::unique_ptr< const Event > event, PostPolicy policy) export
Posts the event to the queue, passing ownership of the event to the underlying queue.
Calling this function is identical to calling post() with the third argument func set to nullptr, relying on the default implementations.
Parameters
event The event to post to the EventQueue.
policy The policy to use for posting the event.
Returns
EventManager
References EventManager().
post() [3/3]
virtual EventManager & helios::event::EventManager::post (std::unique_ptr< const Event > event, PostPolicy policy, const std::function< bool(const std::unique_ptr< const Event > &event, const std::unique_ptr< const Event > &evt)> & func) export pure virtual
Posts the event to the underlying EventQueue using the specified policy and the specified func.
Implementing classes are responsible to treating func according to the specified policy, e.g. APPEND for adding the event to the queue, LATEST_WINS for removing a particular event in favor of the submitted event.
Parameters
event A unique_ptr to the event to be posted. Will be the first argument passed to func.
policy The post policy for the event (
See also
PostPolicy)
Parameters
func The function used with the PostPolicy.
Returns
Implemented in helios::event::BasicEventManager.
References EventManager().
subscribe()
template<typename EventType> EventManager & helios::event::EventManager::subscribe (std::function< void(const EventType &)> callback) inline export
Subscribes a callback to the specified EventType.
Delegates to the subscribe() method of the underlying dispatcher.
Template Parameters
EventType The specific tyoe of the event to subscribe to.
Parameters
callback The callback function that should be called when an event of the specific type is triggered.
Returns
EventManager
Definition at line 167 of file EventManager.ixx.
References dispatcher_, and EventManager().
The documentation for this class was generated from the following file:
include/helios/event/EventManager.ixx