helios: helios::input::gamepad::RadialDeadzoneStrategy Class Reference
helios::input::gamepad::RadialDeadzoneStrategy Class Reference export
module helios.input.gamepad.RadialDeadzoneStrategy
Implements a radial (circular) deadzone strategy for analog stick normalization.
Public Member Functions
RadialDeadzoneStrategy ()
Default constructor.
RadialDeadzoneStrategy (float stickNoiseThreshold)
Interface for applying deadzone handling to gamepad stick input.
void normalize (float deadzone, float &x, float &y) const noexcept override
Applies radial deadzone normalization to stick input.
Public Member Functions inherited from helios::input::gamepad::DeadzoneStrategy
virtual ~DeadzoneStrategy ()=default
Virtual destructor for proper polymorphic cleanup.
DeadzoneStrategy ()=default
Default constructor.
DeadzoneStrategy (float stickNoiseThreshold)
Interface for applying deadzone handling to gamepad stick input.
float stickNoiseThreshold () const noexcept
Retrieves the current noise threshold for stick input.
void setStickNoiseThreshold (float threshold) noexcept
Sets the noise threshold for stick inputs to handle minor hardware drift.
Additional Inherited Members
Static Public Attributes inherited from helios::input::gamepad::DeadzoneStrategy
static constexpr float DEFAULT_STICK_NOISE_THRESHOLD = 0.002f
Default threshold used to filter out minor noise in gamepad stick input.
Protected Attributes inherited from helios::input::gamepad::DeadzoneStrategy
float stickNoiseThreshold_ = DEFAULT_STICK_NOISE_THRESHOLD
Threshold used to filter out minor noise in gamepad stick input.
Detailed Description
Implements a radial (circular) deadzone strategy for analog stick normalization.
This strategy treats the deadzone as a circle centered at the origin. Input vectors with a magnitude less than or equal to the deadzone threshold are zeroed out completely. Input vectors exceeding the deadzone are rescaled so that the effective input range starts at the edge of the deadzone circle, providing a smooth and consistent response.
The radial approach is generally preferred over axial deadzones because it eliminates diagonal movement artifacts and provides uniform sensitivity in all directions.
**Algorithm:** 1. Calculate the magnitude (length) of the input vector. 2. If magnitude <= deadzone, set both axes to zero. 3. If magnitude > 1.0, normalize the vector to unit length. 4. Rescale the magnitude from [deadzone, 1.0] to [0.0, 1.0]. 5. Apply the rescaled magnitude to the normalized direction vector.
See also
DeadzoneStrategy for the abstract interface.
Definition at line 34 of file RadialDeadzoneStrategy.ixx.
Constructor & Destructor Documentation
RadialDeadzoneStrategy() [1/2]
helios::input::gamepad::RadialDeadzoneStrategy::RadialDeadzoneStrategy () inline export
Default constructor.
Definition at line 41 of file RadialDeadzoneStrategy.ixx.
References helios::input::gamepad::DeadzoneStrategy::DeadzoneStrategy().
RadialDeadzoneStrategy() [2/2]
helios::input::gamepad::RadialDeadzoneStrategy::RadialDeadzoneStrategy (float stickNoiseThreshold) inline export
Interface for applying deadzone handling to gamepad stick input.
Defines a method for processing and normalizing analog stick input while accounting for a deadzone. A deadzone eliminates unintended small input values caused by hardware imperfections. Implementations of this interface provide specific strategies for handling the deadzone and input normalization.
See also
AxisDeadzoneStrategy for an axis-aligned deadzone implementation.
Definition at line 46 of file RadialDeadzoneStrategy.ixx.
References helios::input::gamepad::DeadzoneStrategy::DeadzoneStrategy(), and helios::input::gamepad::DeadzoneStrategy::stickNoiseThreshold().
Member Function Documentation
normalize()
void helios::input::gamepad::RadialDeadzoneStrategy::normalize (float deadzone, float & x, float & y) const override export virtual noexcept
Applies radial deadzone normalization to stick input.
Modifies the input coordinates in-place. Values within the circular deadzone are zeroed, while values outside are rescaled for a smooth response curve.
Parameters
deadzone The deadzone radius threshold in the range [0.0, 1.0].
x Reference to the x-axis value, modified in-place.
y Reference to the y-axis value, modified in-place.
Implements helios::input::gamepad::DeadzoneStrategy.
The documentation for this class was generated from the following file:
include/helios/input/gamepad/RadialDeadzoneStrategy.ixx