helios: helios::engine::game::GameWorld Class Reference
helios::engine::game::GameWorld Class Reference export
module helios.engine.game.GameWorld
Central registry for managing game entities, systems, and the active level.
Public Member Functions
GameWorld ()=default
void setLevel (std::unique_ptr< helios::engine::game::Level > level) noexcept
Sets the current level for the game world.
bool hasLevel () const noexcept
Checks if a level is currently loaded.
const helios::engine::game::Level & level () const noexcept
Retrieves the currently loaded level.
template<typename T, typename... Args>
T & add (Args &&... args)
Adds a System to the GameWorld.
template<typename T>
T * get () const
Retrieves a System of the specified type.
template<typename T>
bool has () const
Checks if a System of the specified type is registered.
void update (helios::engine::game::UpdateContext &updateContext) const noexcept
Updates the game world state for the current frame.
helios::engine::game::GameObject * addGameObject (std::unique_ptr< GameObject > gameObject)
Adds a GameObject to the world and transfers ownership.
helios::engine::game::GameObject * find (const helios::util::Guid &guid)
Finds a GameObject by its unique identifier.
const helios::engine::game::GameObject * find (const helios::util::Guid &guid) const
Finds a GameObject by its unique identifier (const overload).
std::unique_ptr< helios::engine::game::GameObject > removeGameObject (const GameObject &gameObject)
Removes a GameObject from the world and transfers ownership to the caller.
const std::unordered_map< helios::util::Guid, std::unique_ptr< GameObject > > & gameObjects () const noexcept
Retrieves a const ref to the map of all active GameObjects.
Protected Attributes
std::unordered_map< helios::util::Guid, std::unique_ptr< GameObject > > gameObjects_
Hash map storing all active GameObjects, indexed by their Guid.
std::vector< std::unique_ptr< System > > systems_
Vector storing all registered Systems.
std::unique_ptr< helios::engine::game::Level > level_ = nullptr
The current level loaded in the game world.
Static Protected Attributes
static const helios::util::log::Logger & logger_
The logger used with this GameWorld instance.
Detailed Description
Central registry for managing game entities, systems, and the active level.
The GameWorld is the root container for the game state. It manages the lifecycle of GameObjects, executes Systems, and holds the current Level.
Key responsibilities:
**Entity Management:** Owns all GameObjects and provides lookup by Guid.
**System Execution:** Manages and updates registered Systems.
**Level Management:** Holds the active Level instance.
**Update Loop:** Orchestrates the frame update by updating GameObjects and then Systems.
Definition at line 37 of file GameWorld.ixx.
Constructor & Destructor Documentation
GameWorld()
helios::engine::game::GameWorld::GameWorld () explicit export default
Member Function Documentation
add()
template<typename T, typename... Args> T & helios::engine::game::GameWorld::add (Args &&... args) inline export
Adds a System to the GameWorld.
Creates a System of the specified type with the given constructor arguments, invokes its `onAdd()` callback, and registers it with this GameWorld. Systems are updated each frame after GameObjects.
Template Parameters
T The System type to add. Must derive from System.
Args Constructor argument types.
Parameters
args Arguments forwarded to the System constructor.
Returns
Reference to the newly added System.
Note
The GameWorld takes ownership of the System.
Definition at line 122 of file GameWorld.ixx.
References systems_.
addGameObject()
helios::engine::game::GameObject * helios::engine::game::GameWorld::addGameObject (std::unique_ptr< GameObject > gameObject) nodiscard export
Adds a GameObject to the world and transfers ownership.
Parameters
gameObject The GameObject to add. Ownership is transferred to the GameWorld.
Returns
Pointer to the added GameObject, or nullptr if addition failed.
Return values
GameObject* Non-owning pointer to the added object (valid until removed)
nullptr If gameObject was null or a GameObject with the same Guid already exists
Note
The GameWorld takes ownership of the GameObject. The returned pointer remains valid until the GameObject is removed from the world.
Attempting to add a nullptr or a GameObject with a duplicate Guid will fail, return nullptr, and log a warning.
find() [1/2]
helios::engine::game::GameObject * helios::engine::game::GameWorld::find (const helios::util::Guid & guid) nodiscard export
Finds a GameObject by its unique identifier.
Parameters
guid The unique identifier of the GameObject to find.
Returns
Pointer to the GameObject if found, nullptr otherwise.
Return values
GameObject* Non-owning pointer to the found object
nullptr If no GameObject with the specified Guid exists
Note
This is the non-const overload. Use the const overload for read-only access.
find() [2/2]
const helios::engine::game::GameObject * helios::engine::game::GameWorld::find (const helios::util::Guid & guid) const nodiscard export
Finds a GameObject by its unique identifier (const overload).
Parameters
guid The unique identifier of the GameObject to find.
Returns
Const pointer to the GameObject if found, nullptr otherwise.
Return values
const GameObject* Non-owning const pointer to the found object
nullptr If no GameObject with the specified Guid exists
Note
This overload is used when the GameWorld is accessed via const reference.
gameObjects()
const std::unordered_map< helios::util::Guid, std::unique_ptr< GameObject > > & helios::engine::game::GameWorld::gameObjects () const inline nodiscard export noexcept
Retrieves a const ref to the map of all active GameObjects.
Returns
A const reference to the internal map of GameObjects, indexed by Guid.
Warning
Modifying the map directly (e.g. adding/removing elements) bypasses GameWorld's management logic and should be avoided. Use addGameObject() and removeGameObject() instead.
Definition at line 252 of file GameWorld.ixx.
References gameObjects_.
get()
template<typename T> T * helios::engine::game::GameWorld::get () const inline nodiscard export
Retrieves a System of the specified type.
Searches through all registered Systems using dynamic_cast to find a matching type.
Template Parameters
T The System type to retrieve. Must derive from System.
Returns
Pointer to the System if found, nullptr otherwise.
Note
Uses dynamic_cast internally; consider type-based registry for performance-critical paths.
Definition at line 146 of file GameWorld.ixx.
References systems_.
Referenced by has().
has()
template<typename T> bool helios::engine::game::GameWorld::has () const inline nodiscard export
Checks if a System of the specified type is registered.
Template Parameters
T The System type to check for. Must derive from System.
Returns
True if a System of type T exists, false otherwise.
Definition at line 163 of file GameWorld.ixx.
References get().
hasLevel()
bool helios::engine::game::GameWorld::hasLevel () const inline nodiscard export noexcept
Checks if a level is currently loaded.
Returns
True if a level is set, false otherwise.
Definition at line 91 of file GameWorld.ixx.
References level_.
level()
const helios::engine::game::Level & helios::engine::game::GameWorld::level () const inline nodiscard export noexcept
Retrieves the currently loaded level.
Returns
Reference to the active Level.
Warning
Calling this method when hasLevel() returns false results in undefined behavior.
Definition at line 102 of file GameWorld.ixx.
References level_.
Referenced by setLevel().
removeGameObject()
std::unique_ptr< helios::engine::game::GameObject > helios::engine::game::GameWorld::removeGameObject (const GameObject & gameObject) nodiscard export
Removes a GameObject from the world and transfers ownership to the caller.
Parameters
gameObject Reference to the GameObject to remove.
Returns
Unique pointer to the removed GameObject, or nullptr if not found.
Return values
std::unique_ptr<GameObject> Ownership of the removed object
nullptr If the GameObject was not found in the world
Note
After successful removal, all non-owning pointers to the GameObject become invalid unless the caller maintains the returned unique_ptr.
Attempting to remove a GameObject that doesn't exist returns nullptr and logs a warning.
setLevel()
void helios::engine::game::GameWorld::setLevel (std::unique_ptr< helios::engine::game::Level > level) inline export noexcept
Sets the current level for the game world.
Parameters
level Unique pointer to the Level instance. Ownership is transferred to the GameWorld.
Definition at line 82 of file GameWorld.ixx.
References level(), and level_.
update()
void helios::engine::game::GameWorld::update (helios::engine::game::UpdateContext & updateContext) const export noexcept
Updates the game world state for the current frame.
This method performs the following steps: 1. Updates all active GameObjects (invoking their `update()` method). 2. Updates all registered Systems (invoking their `update()` method).
Parameters
updateContext Context containing deltaTime, input snapshot, game world and command buffer.
Note
The order of GameObject updates is not guaranteed. Systems are updated in registration order.
The documentation for this class was generated from the following file:
include/helios/engine/game/GameWorld.ixx