helios: helios::util::log::ConsoleSink Class Reference
helios::util::log::ConsoleSink Class Reference export
module helios.util.log.ConsoleSink
LogSink implementation that writes to standard output.
Public Member Functions
SinkTypeId typeId () const noexcept override
Returns the unique type identifier for this sink.
void write (LogLevel level, const std::string &scope, const std::string &message) override
Writes a formatted log message to stdout.
void flush () override
Flushes the stdout buffer.
Public Member Functions inherited from helios::util::log::LogSink
virtual ~LogSink ()=default
Static Public Attributes
static constexpr SinkTypeId TYPE_ID = "console"
Unique type identifier for this sink.
Detailed Description
LogSink implementation that writes to standard output.
This is the default sink for console-based logging. Output is formatted with level prefix and scope tag, mirroring the original Logger behavior.
Definition at line 22 of file ConsoleSink.ixx.
Member Function Documentation
flush()
void helios::util::log::ConsoleSink::flush () override export virtual
Flushes the stdout buffer.
Implements helios::util::log::LogSink.
References flush().
Referenced by flush().
typeId()
SinkTypeId helios::util::log::ConsoleSink::typeId () const nodiscard override export virtual noexcept
Returns the unique type identifier for this sink.
Returns
"console".
Implements helios::util::log::LogSink.
write()
void helios::util::log::ConsoleSink::write (LogLevel level, const std::string & scope, const std::string & message) override export virtual
Writes a formatted log message to stdout.
Parameters
level The severity level of the message.
scope The source scope/module name.
message The log message text.
Implements helios::util::log::LogSink.
References write().
Referenced by write().
The documentation for this class was generated from the following file:
include/helios/util/log/ConsoleSink.ixx