helios: helios::rendering::RenderPrototype Class Reference
helios::rendering::RenderPrototype Class Reference final export
module helios.rendering.RenderPrototype
An immutable, shared prototype of a renderable object.
Public Member Functions
~RenderPrototype ()=default
RenderPrototype (std::shared_ptr< const helios::rendering::model::Material > material, std::shared_ptr< const helios::rendering::model::Mesh > mesh)
Creates a new RenderPrototype using the specified Material and Mesh.
const helios::rendering::model::Mesh & mesh () const noexcept
Returns const ref to the immutable Mesh used by this RenderPrototype.
const helios::rendering::model::Material & material () const noexcept
Returns a const reference to the immutable Material used by this RenderPrototype. The Material contains shader information and default properties. It is guaranteed to exist and be valid.
Detailed Description
An immutable, shared prototype of a renderable object.
A RenderPrototype bundles a specific Mesh (geometry) with a specific Material (shader and default properties). It acts as a shared asset definition, serving as a key for efficient batching and instancing in the rendering pipeline.
Instances of RenderPrototype are designed to be shared across multiple Renderable objects. They are immutable once created, ensuring consistent behavior for all references and providing a stable base for per-instance overrides.
Definition at line 30 of file RenderPrototype.ixx.
Constructor & Destructor Documentation
~RenderPrototype()
helios::rendering::RenderPrototype::~RenderPrototype () export default
RenderPrototype()
helios::rendering::RenderPrototype::RenderPrototype (std::shared_ptr< const helios::rendering::model::Material > material, std::shared_ptr< const helios::rendering::model::Mesh > mesh) explicit export
Creates a new RenderPrototype using the specified Material and Mesh.
Parameters
material A shared pointer to the immutable Material this RenderPrototype uses.
mesh A shared pointer to the immutable Mesh this RenderPrototype uses.
Exceptions
std::invalid_argument If either material or mesh represent a nullptr.
References material(), and mesh().
Member Function Documentation
material()
const helios::rendering::model::Material & helios::rendering::RenderPrototype::material () const nodiscard export noexcept
Returns a const reference to the immutable Material used by this RenderPrototype. The Material contains shader information and default properties. It is guaranteed to exist and be valid.
Returns
A const ref to the Material object.
References material().
Referenced by material(), and RenderPrototype().
mesh()
const helios::rendering::model::Mesh & helios::rendering::RenderPrototype::mesh () const nodiscard export noexcept
Returns const ref to the immutable Mesh used by this RenderPrototype.
Represents a const reference to an unmodifiable Mesh object, containing geometric data such as vertices and indices used for rendering operations or computational tasks.
Referenced by RenderPrototype().
The documentation for this class was generated from the following file:
include/helios/rendering/RenderPrototype.ixx