helios: helios::util::log::LogManager Class Reference
helios::util::log::LogManager Class Reference export
module helios.util.log.LogManager
LogManager for managing scoped Loggers and global sink configuration.
Public Member Functions
~LogManager ()=default
LogManager (const LogManager &)=delete
LogManager & operator= (const LogManager &)=delete
const Logger & logger () const noexcept
Returns a const reference to the default logger managed with this LogManager.
const Logger & logger (const std::string &scope) const noexcept
Returns a const reference to the logger instance for the specified scope.
Logger & registerLogger (const std::string &scope) noexcept
Registers a new logger with this manager.
void enableLogging (bool enable) noexcept
Enables or disables all log output of the Loggers registered with this LogManager.
void setScopeFilter (const std::string &scope) noexcept
Sets the filter scope for the logger.
void registerSink (std::shared_ptr< LogSink > sink)
Registers a sink and enables it by default.
void registerSink (std::shared_ptr< LogSink > sink, bool enabled)
Registers a sink with optional auto-enable.
void enableSink (SinkTypeId typeId)
Enables a sink by its type identifier.
void enableSink (std::shared_ptr< LogSink > sink)
Enables a sink, registering it first if necessary.
void disableSink (SinkTypeId typeId)
Disables a sink by its type identifier.
void disableSink (std::shared_ptr< LogSink > sink)
Disables a sink by instance.
bool isSinkEnabled (SinkTypeId typeId) const noexcept
Checks if a sink with the given type identifier is currently enabled.
void enableAllSinks ()
Enables all registered sinks.
void disableAllSinks ()
Disables all sinks.
Static Public Member Functions
static const Logger & loggerForScope (const std::string &scope) noexcept
Convenience accessor to obtain a logger for a textual scope via the singleton.
static LogManager & getInstance () noexcept
Returns the LogManager singleton instance.
Detailed Description
LogManager for managing scoped Loggers and global sink configuration.
The LogManager provides centralized control over logging output destinations. Sinks register themselves with a unique type identifier, allowing dynamic enable/disable without compile-time knowledge of all sink types.
```cpp // Register sinks (sinks define their own TYPE_ID) LogManager::getInstance().registerSink(std::make_shared<ConsoleSink>()); LogManager::getInstance().registerSink(std::make_shared<ImGuiLogSink>(widget));
// Enable/disable by type identifier LogManager::getInstance().enableSink("console"); LogManager::getInstance().disableSink("imgui");
// Check status if (LogManager::getInstance().isSinkEnabled("console")) { ... } ```
Definition at line 42 of file LogManager.ixx.
Constructor & Destructor Documentation
~LogManager()
helios::util::log::LogManager::~LogManager () export default
LogManager()
helios::util::log::LogManager::LogManager (const LogManager &) export delete
Enforce singleton (see Meyer's Singleton)
See also
https://en.wikipedia.org/wiki/Singleton_pattern
Member Function Documentation
disableAllSinks()
void helios::util::log::LogManager::disableAllSinks () export
Disables all sinks.
References disableAllSinks().
Referenced by disableAllSinks().
disableSink() [1/2]
void helios::util::log::LogManager::disableSink (SinkTypeId typeId) export
Disables a sink by its type identifier.
Parameters
typeId The unique type identifier of the sink.
References disableSink().
Referenced by disableSink(), and disableSink().
disableSink() [2/2]
void helios::util::log::LogManager::disableSink (std::shared_ptr< LogSink > sink) export
Disables a sink by instance.
Parameters
sink The sink instance to disable.
References disableSink().
enableAllSinks()
void helios::util::log::LogManager::enableAllSinks () export
Enables all registered sinks.
References enableAllSinks().
Referenced by enableAllSinks().
enableLogging()
void helios::util::log::LogManager::enableLogging (bool enable) export noexcept
Enables or disables all log output of the Loggers registered with this LogManager.
Parameters
enable True to enable log output with the registered loggers, otherwise false.
References enableLogging().
Referenced by enableLogging().
enableSink() [1/2]
void helios::util::log::LogManager::enableSink (SinkTypeId typeId) export
Enables a sink by its type identifier.
If a sink with the given typeId is registered, it will be enabled. If no sink with that typeId is registered, this call has no effect.
Parameters
typeId The unique type identifier of the sink (e.g., "console", "imgui").
References enableSink().
Referenced by enableSink(), and enableSink().
enableSink() [2/2]
void helios::util::log::LogManager::enableSink (std::shared_ptr< LogSink > sink) export
Enables a sink, registering it first if necessary.
If the sink is not yet registered, it will be added to the pool. The sink is then enabled for output.
Parameters
sink The sink instance to enable (and register if needed).
References enableSink().
getInstance()
LogManager & helios::util::log::LogManager::getInstance () static export noexcept
Returns the LogManager singleton instance.
Returns
Reference to the global LogManager instance.
isSinkEnabled()
bool helios::util::log::LogManager::isSinkEnabled (SinkTypeId typeId) const nodiscard export noexcept
Checks if a sink with the given type identifier is currently enabled.
Parameters
typeId The unique type identifier of the sink.
Returns
True if the sink is enabled.
References isSinkEnabled().
Referenced by isSinkEnabled().
logger() [1/2]
const Logger & helios::util::log::LogManager::logger () const nodiscard export noexcept
Returns a const reference to the default logger managed with this LogManager.
Returns
The default Logger instance.
References logger().
Referenced by logger(), and logger().
logger() [2/2]
const Logger & helios::util::log::LogManager::logger (const std::string & scope) const nodiscard export noexcept
Returns a const reference to the logger instance for the specified scope.
Will fall back to the default logger if the scope was not registered yet. This method is thread safe for map look-ups.
Parameters
scope The textual scope name of the requested logger.
Returns
The logger registered with the scope, or the default logger if none was found.
References logger().
loggerForScope()
const Logger & helios::util::log::LogManager::loggerForScope (const std::string & scope) static export noexcept
Convenience accessor to obtain a logger for a textual scope via the singleton.
This static helper forwards to `LogManager::getInstance().logger(scope)` and returns a reference to the logger registered for the given scope.
Parameters
scope The textual scope name of the requested logger.
Returns
The logger registered with the scope, or the default logger if none was found.
operator=()
LogManager & helios::util::log::LogManager::operator= (const LogManager &) export delete
registerLogger()
Logger & helios::util::log::LogManager::registerLogger (const std::string & scope) nodiscard export noexcept
Registers a new logger with this manager.
This method is thread safe for map modifications.
Parameters
scope The scope requested for the logger to create.
Returns
The logger registered with the scope, or the logger already registered with the LogManager under the given scope.
References registerLogger().
Referenced by registerLogger().
registerSink() [1/2]
void helios::util::log::LogManager::registerSink (std::shared_ptr< LogSink > sink) export
Registers a sink and enables it by default.
The sink is added to the pool and immediately enabled for output.
Parameters
sink The sink to register.
References registerSink().
Referenced by registerSink(), and registerSink().
registerSink() [2/2]
void helios::util::log::LogManager::registerSink (std::shared_ptr< LogSink > sink, bool enabled) export
Registers a sink with optional auto-enable.
Parameters
sink The sink to register.
enabled Whether to enable the sink immediately (default: true).
References registerSink().
setScopeFilter()
void helios::util::log::LogManager::setScopeFilter (const std::string & scope) export noexcept
Sets the filter scope for the logger.
Will do nothing if logging is not enabled. If the logger for the scope does not exist, it will get implicitly created.
Parameters
scope The scope to filter. Only log messages with this scope will be logged.
References setScopeFilter().
Referenced by setScopeFilter().
The documentation for this class was generated from the following file:
include/helios/util/log/LogManager.ixx