helios: helios::ext::opengl::rendering::shader::OpenGLShader Class Reference
helios::ext::opengl::rendering::shader::OpenGLShader Class Reference export
module helios.ext.opengl.rendering.shader.OpenGLShader
An OpenGL-specific implementation of a Shader program, consisting of a vertex and a fragment shader.
Public Member Functions
OpenGLShader (const OpenGLShader &)=delete
Rule of three.
OpenGLShader & operator= (const OpenGLShader &)=delete
OpenGLShader (const std::string &vertexShaderPath, const std::string &fragmentShaderPath, const helios::util::io::StringFileReader &stringFileReader)
Creates and initializes this OpenGLShader. An instance of this class is guaranteed to have a progId_ != 0, hence shader-files where successfully loaded and compiled, ready to be used.
void use () const noexcept override
Activates this OpenGLShader for subsequent draw calls. This implementation calls `glUseProgram` with the `progId_` received after compilation.
~OpenGLShader () override
Deletes the program object upon destruction of this instance.
void setUniformLocationMap (std::unique_ptr< const OpenGLUniformLocationMap > uniformLocationMap) noexcept
Sets the OpenGLUniformLocationMap for this OpenGLShader. Ownership is transferred to this instance.
int uniformLocation (helios::rendering::shader::UniformSemantics uniformSemantics) const noexcept
Returns the uniform location for the uniform represented by the specified UniformSemantics.
void applyUniformValues (const helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept override
Applies the specified UniformValueMap to the uniforms defined by the shader. This method does not change the binding state of the shader, but it passes the uniform values to the underlying rendering backend. Implementations should ensure that the shader is properly bound before this method is called.
Public Member Functions inherited from helios::rendering::shader::Shader
virtual ~Shader ()=default
Protected Attributes
unsigned int progId_ = 0
The program id as assigned by the underlying rendering backend.
std::unique_ptr< const OpenGLUniformLocationMap > uniformLocationMap_ = nullptr
A unique pointer to the OpenGLUniformLocationMap this shader uses.
Additional Inherited Members
Static Protected Attributes inherited from helios::rendering::shader::Shader
static const helios::util::log::Logger & logger_
Shared logger instance for all Shader objects.
Detailed Description
An OpenGL-specific implementation of a Shader program, consisting of a vertex and a fragment shader.
This class manages the lifecycle of the Shaders. Source files are getting loaded via a StringFileReader and immediately compiled after loading. Any occupied memory for source-files and file-paths to the shader is being cleared once compilation succeeded and are not guaranteed to persist the compilation process.
Definition at line 31 of file OpenGLShader.ixx.
Constructor & Destructor Documentation
OpenGLShader() [1/2]
helios::ext::opengl::rendering::shader::OpenGLShader::OpenGLShader (const OpenGLShader &) export delete
Rule of three.
See also
https://wikis.khronos.org/opengl/Common_Mistakes#RAII_and_hidden_destructor_calls
https://en.cppreference.com/w/cpp/language/rule_of_three.html
Prevent copying.
References OpenGLShader().
Referenced by OpenGLShader(), operator=(), and ~OpenGLShader().
OpenGLShader() [2/2]
helios::ext::opengl::rendering::shader::OpenGLShader::OpenGLShader (const std::string & vertexShaderPath, const std::string & fragmentShaderPath, const helios::util::io::StringFileReader & stringFileReader) export
Creates and initializes this OpenGLShader. An instance of this class is guaranteed to have a progId_ != 0, hence shader-files where successfully loaded and compiled, ready to be used.
Parameters
vertexShaderPath The path to the vertex shader.
fragmentShaderPath The path to the fragment shader.
stringFileReader The StringFileReader used for loading the shader source files.
Exceptions
if creating this shader failed.
~OpenGLShader()
helios::ext::opengl::rendering::shader::OpenGLShader::~OpenGLShader () override export
Deletes the program object upon destruction of this instance.
See also
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml
References OpenGLShader().
Member Function Documentation
applyUniformValues()
void helios::ext::opengl::rendering::shader::OpenGLShader::applyUniformValues (const helios::rendering::shader::UniformValueMap & uniformValueMap) const override export virtual noexcept
Applies the specified UniformValueMap to the uniforms defined by the shader. This method does not change the binding state of the shader, but it passes the uniform values to the underlying rendering backend. Implementations should ensure that the shader is properly bound before this method is called.
Parameters
uniformValueMap A const ref to the `UniformValueMap` containing the values for the uniforms in this shader.
Implements helios::rendering::shader::Shader.
References applyUniformValues().
Referenced by applyUniformValues().
operator=()
OpenGLShader & helios::ext::opengl::rendering::shader::OpenGLShader::operator= (const OpenGLShader &) export delete
References OpenGLShader().
setUniformLocationMap()
void helios::ext::opengl::rendering::shader::OpenGLShader::setUniformLocationMap (std::unique_ptr< const OpenGLUniformLocationMap > uniformLocationMap) export noexcept
Sets the OpenGLUniformLocationMap for this OpenGLShader. Ownership is transferred to this instance.
Parameters
uniformLocationMap The OpenGLUniformMap providing the mappings for the uniforms of the underlying GLSL shader.
References setUniformLocationMap().
Referenced by setUniformLocationMap().
uniformLocation()
int helios::ext::opengl::rendering::shader::OpenGLShader::uniformLocation (helios::rendering::shader::UniformSemantics uniformSemantics) const nodiscard export noexcept
Returns the uniform location for the uniform represented by the specified UniformSemantics.
Parameters
uniformSemantics The `UniformSemantics` identifier.
Returns
The integer representing the uniform variable location in the shader, or -1 if no location map was registered with this shader or if the uniform with the specified semantics was not found.
References uniformLocation().
Referenced by uniformLocation().
use()
void helios::ext::opengl::rendering::shader::OpenGLShader::use () const override export virtual noexcept
Activates this OpenGLShader for subsequent draw calls. This implementation calls `glUseProgram` with the `progId_` received after compilation.
See also
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glUseProgram.xhtml
Implements helios::rendering::shader::Shader.
The documentation for this class was generated from the following file:
include/ext/opengl/rendering/shader/OpenGLShader.ixx