helios: helios::engine::game::components::scene::SceneNodeComponent Class Reference
helios::engine::game::components::scene::SceneNodeComponent Class Reference export
module helios.engine.game.components.scene.SceneNodeComponent
Component that links a GameObject to a SceneNode in the scene graph.
Public Member Functions
SceneNodeComponent (helios::scene::SceneNode *sceneNode)
Constructs a SceneNodeComponent linked to a SceneNode.
void onAttach (helios::engine::game::GameObject *gameObject) noexcept override
Called when the component is attached to a GameObject.
helios::scene::SceneNode * sceneNode () const noexcept
Returns the underlying SceneNode.
Public Member Functions inherited from helios::engine::game::Component
virtual ~Component ()=default
Component ()=default
GameObject * gameObject () const noexcept
Returns the owning GameObject.
Protected Attributes
helios::math::aabbf aabb_ {}
The initial AABB of the model associated with the SceneNode.
helios::scene::SceneNode * sceneNode_
Non-owning pointer to the associated SceneNode.
Protected Attributes inherited from helios::engine::game::Component
GameObject * gameObject_ = nullptr
Non-owning pointer to the owning GameObject.
Detailed Description
Component that links a GameObject to a SceneNode in the scene graph.
This component bridges the game logic layer (GameObject) with the rendering layer (SceneNode). It captures the initial AABB from the SceneNode's mesh (if available) and exposes the underlying SceneNode for other components to use.
Note
The SceneNode must remain valid for the lifetime of this component.
Definition at line 33 of file SceneNodeComponent.ixx.
Constructor & Destructor Documentation
SceneNodeComponent()
helios::engine::game::components::scene::SceneNodeComponent::SceneNodeComponent (helios::scene::SceneNode * sceneNode) inline explicit export
Constructs a SceneNodeComponent linked to a SceneNode.
Parameters
sceneNode Pointer to the SceneNode to control. Must not be nullptr.
Definition at line 54 of file SceneNodeComponent.ixx.
References aabb_, sceneNode(), and sceneNode_.
Member Function Documentation
onAttach()
void helios::engine::game::components::scene::SceneNodeComponent::onAttach (helios::engine::game::GameObject * gameObject) inline override export virtual noexcept
Called when the component is attached to a GameObject.
Automatically adds or retrieves a ModelAabbComponent on the GameObject and initializes it with the captured AABB from the SceneNode.
Parameters
gameObject Pointer to the parent GameObject.
Reimplemented from helios::engine::game::Component.
Definition at line 72 of file SceneNodeComponent.ixx.
References aabb_, helios::engine::game::Component::gameObject(), helios::engine::game::Component::onAttach(), and helios::engine::game::components::model::ModelAabbComponent::setAabb().
sceneNode()
helios::scene::SceneNode * helios::engine::game::components::scene::SceneNodeComponent::sceneNode () const inline nodiscard export noexcept
Returns the underlying SceneNode.
Returns
Non-owning pointer to the associated SceneNode.
Definition at line 85 of file SceneNodeComponent.ixx.
References sceneNode_.
Referenced by SceneNodeComponent().
The documentation for this class was generated from the following file:
include/helios/engine/game/components/scene/SceneNodeComponent.ixx