helios: helios::rendering::model::config::MaterialProperties Class Reference
helios::rendering::model::config::MaterialProperties Class Reference export
module helios.rendering.model.config.MaterialProperties
Represents a Value Object for an immutable set of material properties.
Public Member Functions
~MaterialProperties ()=default
Default destructor for MaterialProperties.
MaterialProperties ()=default
Default constructor for MaterialProperties.
MaterialProperties (helios::math::vec4f baseColor, float roughness=0.0f) noexcept
Constructs a MaterialProperties instance with the specified values.
MaterialProperties withBaseColor (helios::math::vec4f baseColor) const noexcept
MaterialPropertiesOverride overrideBaseColor (helios::math::vec4f baseColor) const noexcept
MaterialProperties withRoughness (float roughness) const noexcept
void writeUniformValues (shader::UniformValueMap &uniformValueMap) const noexcept
Writes the current properties into the given UniformValueMap.
Detailed Description
Represents a Value Object for an immutable set of material properties.
This class acts as a Value Object, encapsulating fundamental material characteristics like base color and roughness. Once an instance is created, its properties cannot be changed. Methods prefixed with `with*` facilitate functional updates by returning a **new** MaterialProperties instance with the specified property modified, leaving the original object - which may still be in use by existing Renderables - untouched.
Definition at line 27 of file MaterialProperties.ixx.
Constructor & Destructor Documentation
~MaterialProperties()
helios::rendering::model::config::MaterialProperties::~MaterialProperties () export default
Default destructor for MaterialProperties.
MaterialProperties() [1/2]
helios::rendering::model::config::MaterialProperties::MaterialProperties () export default
Default constructor for MaterialProperties.
initializes all properties to their default values.
Referenced by withBaseColor(), and withRoughness().
MaterialProperties() [2/2]
helios::rendering::model::config::MaterialProperties::MaterialProperties (helios::math::vec4f baseColor, float roughness = 0.0f) explicit export noexcept
Constructs a MaterialProperties instance with the specified values.
Parameters
baseColor The initial base color for this MaterialProperties instance.
roughness The initial roughness factor for the material, which defaults to 0.0f.
Member Function Documentation
overrideBaseColor()
MaterialPropertiesOverride helios::rendering::model::config::MaterialProperties::overrideBaseColor (helios::math::vec4f baseColor) const nodiscard export noexcept
Creates a new MaterialPropertiesOverride instance with an updated base color.
This method returns a new MaterialPropertiesOverride instance where only the base color has been changed to the provided value.
Parameters
baseColor The new base color for the material.
Returns
A new instance of MaterialPropertiesOvrride with the updated base color.
References overrideBaseColor().
Referenced by overrideBaseColor().
withBaseColor()
MaterialProperties helios::rendering::model::config::MaterialProperties::withBaseColor (helios::math::vec4f baseColor) const nodiscard export noexcept
Creates a new MaterialProperties instance with an updated base color.
This method returns a new MaterialProperties instance where only the base color has been changed to the provided value.
Parameters
baseColor The new base color for the material.
Returns
A new immutable instance of MaterialProperties with the updated base color.
References MaterialProperties(), and withBaseColor().
Referenced by withBaseColor().
withRoughness()
MaterialProperties helios::rendering::model::config::MaterialProperties::withRoughness (float roughness) const nodiscard export noexcept
Creates a new MaterialProperties instance with an updated roughness factor.
This method returns a new MaterialProperties instance where only the roughness factor has been changed to the provided value.
Parameters
roughness The new roughness factor for the material.
Returns
A new immutable instance of MaterialProperties with the updated roughness factor.
References MaterialProperties(), and withRoughness().
Referenced by withRoughness().
writeUniformValues()
void helios::rendering::model::config::MaterialProperties::writeUniformValues (shader::UniformValueMap & uniformValueMap) const export noexcept
Writes the current properties into the given UniformValueMap.
Parameters
uniformValueMap Target map receiving the uniform values.
References writeUniformValues().
Referenced by writeUniformValues().
The documentation for this class was generated from the following file:
include/helios/rendering/model/config/MaterialProperties.ixx