helios: helios::ext::imgui::ImGuiGlfwOpenGLBackend Class Reference
helios::ext::imgui::ImGuiGlfwOpenGLBackend Class Reference export
module helios.ext.imgui.ImGuiGlfwOpenGLBackend
ImGui backend for GLFW windowing and OpenGL 4.6 rendering.
Public Member Functions
ImGuiGlfwOpenGLBackend (const ImGuiGlfwOpenGLBackend &)=delete
ImGuiGlfwOpenGLBackend & operator= (const ImGuiGlfwOpenGLBackend &)=delete
ImGuiGlfwOpenGLBackend (ImGuiGlfwOpenGLBackend &&other) noexcept=delete
ImGuiGlfwOpenGLBackend & operator= (ImGuiGlfwOpenGLBackend &&other) noexcept=delete
ImGuiGlfwOpenGLBackend (GLFWwindow *window)
Constructs and initializes the ImGui backend for GLFW+OpenGL.
void renderDrawData (ImDrawData *drawData) override
Renders ImGui draw data using OpenGL.
void newFrame () override
Starts a new ImGui frame.
~ImGuiGlfwOpenGLBackend () override
Destructor; shuts down ImGui backend and releases resources.
Public Member Functions inherited from helios::ext::imgui::ImGuiBackend
ImGuiBackend ()=default
virtual ~ImGuiBackend ()=default
Detailed Description
ImGui backend for GLFW windowing and OpenGL 4.6 rendering.
Initializes ImGui context, GLFW platform layer, and OpenGL renderer. This backend is non-copyable and non-movable due to resource ownership semantics.
Note
Only one instance should exist per application. Creating multiple instances will throw a `std::runtime_error`.
Definition at line 29 of file ImGuiGlfwOpenGLBackend.ixx.
Constructor & Destructor Documentation
ImGuiGlfwOpenGLBackend() [1/3]
helios::ext::imgui::ImGuiGlfwOpenGLBackend::ImGuiGlfwOpenGLBackend (const ImGuiGlfwOpenGLBackend &) export delete
References ImGuiGlfwOpenGLBackend().
Referenced by ImGuiGlfwOpenGLBackend(), ImGuiGlfwOpenGLBackend(), operator=(), and operator=().
ImGuiGlfwOpenGLBackend() [2/3]
helios::ext::imgui::ImGuiGlfwOpenGLBackend::ImGuiGlfwOpenGLBackend (ImGuiGlfwOpenGLBackend && other) export delete noexcept
References ImGuiGlfwOpenGLBackend().
ImGuiGlfwOpenGLBackend() [3/3]
helios::ext::imgui::ImGuiGlfwOpenGLBackend::ImGuiGlfwOpenGLBackend (GLFWwindow * window) inline explicit export
Constructs and initializes the ImGui backend for GLFW+OpenGL.
Parameters
window GLFW window handle. Must be valid for the lifetime of this backend.
Exceptions
std::runtime_error if ImGui context already exists or initialization fails.
Definition at line 79 of file ImGuiGlfwOpenGLBackend.ixx.
~ImGuiGlfwOpenGLBackend()
helios::ext::imgui::ImGuiGlfwOpenGLBackend::~ImGuiGlfwOpenGLBackend () inline override export
Destructor; shuts down ImGui backend and releases resources.
See also
shutdown()
Definition at line 129 of file ImGuiGlfwOpenGLBackend.ixx.
Member Function Documentation
newFrame()
void helios::ext::imgui::ImGuiGlfwOpenGLBackend::newFrame () inline override export virtual
Starts a new ImGui frame.
Implements helios::ext::imgui::ImGuiBackend.
Definition at line 118 of file ImGuiGlfwOpenGLBackend.ixx.
operator=() [1/2]
ImGuiGlfwOpenGLBackend & helios::ext::imgui::ImGuiGlfwOpenGLBackend::operator= (const ImGuiGlfwOpenGLBackend &) export delete
References ImGuiGlfwOpenGLBackend().
operator=() [2/2]
ImGuiGlfwOpenGLBackend & helios::ext::imgui::ImGuiGlfwOpenGLBackend::operator= (ImGuiGlfwOpenGLBackend && other) export delete noexcept
References ImGuiGlfwOpenGLBackend().
renderDrawData()
void helios::ext::imgui::ImGuiGlfwOpenGLBackend::renderDrawData (ImDrawData * drawData) inline override export virtual
Renders ImGui draw data using OpenGL.
Parameters
drawData Pointer to ImGui draw data.
Implements helios::ext::imgui::ImGuiBackend.
Definition at line 111 of file ImGuiGlfwOpenGLBackend.ixx.
The documentation for this class was generated from the following file:
include/ext/imgui/ImGuiGlfwOpenGLBackend.ixx