helios: helios::engine::game::Level Class Reference
helios::engine::game::Level Class Reference export
module helios.engine.game.Level
Represents a game level containing the scene graph and world boundaries.
Public Member Functions
Level (helios::scene::SceneNode *rootNode)
Constructs a new Level with a specific root scene node.
void setBounds (const helios::math::aabbf &bounds, const helios::core::units::Unit unit=helios::core::units::Unit::Meter) noexcept
Sets the spatial boundaries of the level.
helios::scene::SceneNode * rootNode () const noexcept
Retrieves the root scene node of the level.
helios::math::aabbf bounds () const noexcept
Retrieves the level boundaries in engine units (meters).
Detailed Description
Represents a game level containing the scene graph and world boundaries.
The Level class acts as a container for the scene hierarchy (via a root node) and defines the spatial limits of the game world. It handles unit conversion for boundaries to ensure consistent internal representation (meters).
Definition at line 23 of file Level.ixx.
Constructor & Destructor Documentation
Level()
helios::engine::game::Level::Level (helios::scene::SceneNode * rootNode) inline explicit export
Constructs a new Level with a specific root scene node.
Parameters
rootNode Pointer to the root node of the scene graph for this level. The Level does not take ownership of this pointer.
Definition at line 42 of file Level.ixx.
References rootNode().
Member Function Documentation
bounds()
helios::math::aabbf helios::engine::game::Level::bounds () const inline nodiscard export noexcept
Retrieves the level boundaries in engine units (meters).
Returns
The axis-aligned bounding box of the level.
Definition at line 75 of file Level.ixx.
Referenced by setBounds().
rootNode()
helios::scene::SceneNode * helios::engine::game::Level::rootNode () const inline nodiscard export noexcept
Retrieves the root scene node of the level.
Returns
Pointer to the root SceneNode.
Definition at line 66 of file Level.ixx.
Referenced by Level().
setBounds()
void helios::engine::game::Level::setBounds (const helios::math::aabbf & bounds, const helios::core::units::Unit unit = helios::core::units::Unit::Meter) inline export noexcept
Sets the spatial boundaries of the level.
Converts the provided bounds from the specified unit to the engine's standard unit (meters) before storing them.
Parameters
bounds The axis-aligned bounding box defining the level limits.
unit The unit of measurement for the provided bounds (defaults to Meter).
Definition at line 53 of file Level.ixx.
References bounds(), helios::core::units::from(), and helios::core::units::Meter.
The documentation for this class was generated from the following file:
include/helios/engine/game/Level.ixx