helios: helios::ext::opengl::rendering::model::OpenGLMesh Class Reference
helios::ext::opengl::rendering::model::OpenGLMesh Class Reference final export
module helios.ext.opengl.rendering.model.OpenGLMesh
Representative of an OpenGLMesh. This class manages the OpenGL Vertex Array Object (VAO), the Vertex Buffer Object (VBO) and Element Buffer Object (EBO) handles. The raw mesh data is uploaded to the GPU, preparing it for subsequent rendering commands / draw calls.
Public Member Functions
OpenGLMesh (const OpenGLMesh &)=delete
Rule of three.
OpenGLMesh & operator= (const OpenGLMesh &)=delete
OpenGLMesh (std::shared_ptr< const std::vector< helios::rendering::Vertex > > vertices, std::shared_ptr< const std::vector< unsigned int > > indices, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig)
Constructs a new OpenGLMesh instance from raw mesh data.
OpenGLMesh (const helios::rendering::asset::shape::Shape &shape, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig)
Creates a new OpenGLMesh instance from the specified Shape.
~OpenGLMesh () override
Frees allocated resources bv this instance. If an instance of this class is destructed, `glDeleteBuffers`/`glDeleteVertexArrays` is called to free the associated resources.
const unsigned int & vao () const noexcept
Returns the OpenGL Vertex Array Object Handle.
const unsigned int & vbo () const noexcept
Returns the OpenGL Vertex Buffer Object handle.
const unsigned int & ebo () const noexcept
Returns the OpenGL Element Buffer Object handle for indexed rendering.
Public Member Functions inherited from helios::rendering::model::Mesh
virtual ~Mesh ()=default
Mesh (std::shared_ptr< const std::vector< Vertex > > vertices, std::shared_ptr< const std::vector< unsigned int > > indices, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig)
Creates a new Mesh instance.
Mesh (const helios::rendering::asset::shape::Shape &shape, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig)
Creates a new Mesh instance from the specified Shape.
unsigned int indexCount () const noexcept
Returns the index count of this Mesh.
const std::vector< Vertex > & vertices () const noexcept
Returns a const reference to the underlying vertices. The returned data is guaranteed to be a valid reference to existing data.
const std::vector< unsigned int > & indices () const noexcept
Returns a const reference to the underlying indices. The returned data is guaranteed to be a valid reference to existing data.
const helios::rendering::model::config::MeshConfig & meshConfig () const noexcept
Returns a const reference to MeshConfig used with this Mesh. The returned MeshConfig is guaranteed to be a valid reference to existing data.
const helios::math::aabbf & aabb () const noexcept
Retrieves the axis-aligned bounding box (AABB) of the mesh.
Protected Member Functions
void init () override
Initializes all buffer objects required by OpenGL from the provided mesh data. The current implementation generates all VAO, VBO and EBO handles, loads the vertex and index data to the GPU. It follows [Vri20, 162] in this regard.
Protected Member Functions inherited from helios::rendering::model::Mesh
Mesh ()=default
Static Protected Member Functions
static unsigned int generateGLVertexArray () noexcept
Helper function for generating a Vertex Array Object identifier.
static unsigned int generateGLBuffer () noexcept
Helper function for generating a Buffer Object identifier, to be used with vertex buffer or element buffer.
Protected Attributes
const unsigned int vao_
Vertex Array Object handle.
const unsigned int vbo_
Vertex Buffer Object handle. Stores vertex attributes such as normals and texture coordinates.
const unsigned int ebo_
Element Buffer Object handle. Stores the indices used for indexed drawing.
Protected Attributes inherited from helios::rendering::model::Mesh
bool needsUpdate_ = true
Flag indicating whether the mesh requires updates to its computed data.
helios::math::aabbf aabb_ {}
Represents the axis-aligned bounding box (AABB) for the mesh.
std::shared_ptr< const std::vector< Vertex > > vertices_ = nullptr
Shared pointer to the raw, immutable vertices.
std::shared_ptr< const std::vector< unsigned int > > indices_ = nullptr
Shared pointer to the raw, immutable indices.
std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig_
Shared pointer to the MeshConfig used with this Mesh.
Additional Inherited Members
Static Protected Attributes inherited from helios::rendering::model::Mesh
static const helios::util::log::Logger & logger_
Shared logger instance for all Mesh objects.
Detailed Description
Representative of an OpenGLMesh. This class manages the OpenGL Vertex Array Object (VAO), the Vertex Buffer Object (VBO) and Element Buffer Object (EBO) handles. The raw mesh data is uploaded to the GPU, preparing it for subsequent rendering commands / draw calls.
Definition at line 26 of file OpenGLMesh.ixx.
Constructor & Destructor Documentation
OpenGLMesh() [1/3]
helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh (const OpenGLMesh &) export delete
Rule of three.
See also
https://wikis.khronos.org/opengl/Common_Mistakes#RAII_and_hidden_destructor_calls
https://en.cppreference.com/w/cpp/language/rule_of_three.html
References OpenGLMesh().
Referenced by OpenGLMesh(), OpenGLMesh(), OpenGLMesh(), operator=(), and ~OpenGLMesh().
OpenGLMesh() [2/3]
helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh (std::shared_ptr< const std::vector< helios::rendering::Vertex > > vertices, std::shared_ptr< const std::vector< unsigned int > > indices, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig) explicit export
Constructs a new OpenGLMesh instance from raw mesh data.
Parameters
vertices A shared pointer to a vector of const Vertex
indices A shared pointer to a vector of indices
meshConfig A shared ptr to the const MeshConfig used with this Mesh.
Exceptions
std::invalid_argument if either "vertices", "indices" or meshConfig is a null shared pointer
References helios::rendering::model::Mesh::indices(), helios::rendering::model::Mesh::meshConfig(), OpenGLMesh(), and helios::rendering::model::Mesh::vertices().
OpenGLMesh() [3/3]
helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh (const helios::rendering::asset::shape::Shape & shape, std::shared_ptr< const helios::rendering::model::config::MeshConfig > meshConfig) explicit export
Creates a new OpenGLMesh instance from the specified Shape.
Parameters
shape A const reference to the Shape.
meshConfig A shared ptr to the const MeshConfig used with this OpenGLMesh.
Exceptions
std::invalid_argument if meshConfig is a null shared pointer, or if the shape contained null data
References helios::rendering::model::Mesh::meshConfig(), and OpenGLMesh().
~OpenGLMesh()
helios::ext::opengl::rendering::model::OpenGLMesh::~OpenGLMesh () override export
Frees allocated resources bv this instance. If an instance of this class is destructed, `glDeleteBuffers`/`glDeleteVertexArrays` is called to free the associated resources.
See also
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDeleteBuffers.xhtml
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDeleteVertexArrays.xhtml
References OpenGLMesh().
Member Function Documentation
ebo()
const unsigned int & helios::ext::opengl::rendering::model::OpenGLMesh::ebo () const nodiscard export noexcept
Returns the OpenGL Element Buffer Object handle for indexed rendering.
Returns
EBO handle
References ebo().
Referenced by ebo().
generateGLBuffer()
unsigned int helios::ext::opengl::rendering::model::OpenGLMesh::generateGLBuffer () static export protected noexcept
Helper function for generating a Buffer Object identifier, to be used with vertex buffer or element buffer.
Returns
Vertex Array Object handle.
References generateGLBuffer().
Referenced by generateGLBuffer().
generateGLVertexArray()
unsigned int helios::ext::opengl::rendering::model::OpenGLMesh::generateGLVertexArray () static export protected noexcept
Helper function for generating a Vertex Array Object identifier.
Returns
Vertex Array Object handle.
init()
void helios::ext::opengl::rendering::model::OpenGLMesh::init () override export protected virtual
Initializes all buffer objects required by OpenGL from the provided mesh data. The current implementation generates all VAO, VBO and EBO handles, loads the vertex and index data to the GPU. It follows [Vri20, 162] in this regard.
See also
[Vri20, 162]
Implements helios::rendering::model::Mesh.
References init().
Referenced by init().
operator=()
OpenGLMesh & helios::ext::opengl::rendering::model::OpenGLMesh::operator= (const OpenGLMesh &) export delete
References OpenGLMesh().
vao()
const unsigned int & helios::ext::opengl::rendering::model::OpenGLMesh::vao () const nodiscard export noexcept
Returns the OpenGL Vertex Array Object Handle.
Returns
VAO handle
References vao().
Referenced by vao().
vbo()
const unsigned int & helios::ext::opengl::rendering::model::OpenGLMesh::vbo () const nodiscard export noexcept
Returns the OpenGL Vertex Buffer Object handle.
Returns
VBO handle
References vbo().
Referenced by vbo().
The documentation for this class was generated from the following file:
include/ext/opengl/rendering/model/OpenGLMesh.ixx