helios: helios::ext::glfw::app::GLFWRAIIGuard Class Reference
helios::ext::glfw::app::GLFWRAIIGuard Class Reference export
module helios.ext.glfw.app.GLFWRAIIGuard
A RAII Guard for GLFW.
Public Member Functions
GLFWRAIIGuard ()
Initializes the glfw library by calling `glfwInit()`.
~GLFWRAIIGuard ()
Terminates the glfw library by calling `glfwTerminate()`.
GLFWRAIIGuard (const GLFWRAIIGuard &)=delete
No copy or move.
GLFWRAIIGuard & operator= (const GLFWRAIIGuard &)=delete
GLFWRAIIGuard (const GLFWRAIIGuard &&)=delete
GLFWRAIIGuard & operator= (const GLFWRAIIGuard &&)=delete
Detailed Description
A RAII Guard for GLFW.
This class makes sure that GLFW is properly initialized when an instance is created and terminated when this instance is destroyed.
See also
https://en.cppreference.com/w/cpp/language/raii.html
Definition at line 19 of file GLFWRAIIGuard.ixx.
Constructor & Destructor Documentation
GLFWRAIIGuard() [1/3]
helios::ext::glfw::app::GLFWRAIIGuard::GLFWRAIIGuard () export
Initializes the glfw library by calling `glfwInit()`.
Exceptions
std::runtime_error if initialization fails
See also
https://www.glfw.org/docs/latest/group__init.html#ga317aac130a235ab08c6db0834907d85e
Referenced by GLFWRAIIGuard(), GLFWRAIIGuard(), operator=(), and operator=().
~GLFWRAIIGuard()
helios::ext::glfw::app::GLFWRAIIGuard::~GLFWRAIIGuard () export
Terminates the glfw library by calling `glfwTerminate()`.
See also
https://www.glfw.org/docs/latest/group__init.html#gaaae48c0a18607ea4a4ba951d939f0901
GLFWRAIIGuard() [2/3]
helios::ext::glfw::app::GLFWRAIIGuard::GLFWRAIIGuard (const GLFWRAIIGuard &) export delete
No copy or move.
References GLFWRAIIGuard().
GLFWRAIIGuard() [3/3]
helios::ext::glfw::app::GLFWRAIIGuard::GLFWRAIIGuard (const GLFWRAIIGuard &&) export delete
References GLFWRAIIGuard().
Member Function Documentation
operator=() [1/2]
GLFWRAIIGuard & helios::ext::glfw::app::GLFWRAIIGuard::operator= (const GLFWRAIIGuard &&) export delete
References GLFWRAIIGuard().
operator=() [2/2]
GLFWRAIIGuard & helios::ext::glfw::app::GLFWRAIIGuard::operator= (const GLFWRAIIGuard &) export delete
References GLFWRAIIGuard().
The documentation for this class was generated from the following file:
include/ext/glfw/app/GLFWRAIIGuard.ixx