helios: helios::rendering::model::MaterialInstance Class Reference
helios::rendering::model::MaterialInstance Class Reference final export
module helios.rendering.model.MaterialInstance
MaterialInstance for providing a material definition with optional overrides.
Public Member Functions
~MaterialInstance ()=default
MaterialInstance (std::shared_ptr< const helios::rendering::model::Material > material, std::shared_ptr< const helios::rendering::model::config::MaterialPropertiesOverride > materialOverrides=nullptr)
Constructs a new MaterialInstance.
std::shared_ptr< const helios::rendering::shader::Shader > shader () const noexcept
Returns a shared pointer to the shader used by the Material.
void writeUniformValues (helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept
Writes this MaterialInstance's uniform values into the given map.
Detailed Description
MaterialInstance for providing a material definition with optional overrides.
This class represents a specific instance of a Material: it combines a base Material definition (including shader and default properties) with an optional MaterialPropertiesOverride that customizes the Material's appearance for a particular object or use case. This allows efficient customization while reusing common material logic.
See also
[RTR, pp. 125]
Definition at line 32 of file MaterialInstance.ixx.
Constructor & Destructor Documentation
~MaterialInstance()
helios::rendering::model::MaterialInstance::~MaterialInstance () export default
MaterialInstance()
helios::rendering::model::MaterialInstance::MaterialInstance (std::shared_ptr< const helios::rendering::model::Material > material, std::shared_ptr< const helios::rendering::model::config::MaterialPropertiesOverride > materialOverrides = nullptr) explicit export
Constructs a new MaterialInstance.
Initializes this instance with a base material definition and an optional set of property overrides.
Parameters
material A shared pointer to the base Material definition.
materialOverrides An optional shared pointer to a MaterialPropertiesOverride object, containing values that override the defaults from the base material. If nullptr, only the Material's defaults will be used.
Exceptions
std::invalid_argument if the shared ptr to material represents a nullptr.
Member Function Documentation
shader()
std::shared_ptr< const helios::rendering::shader::Shader > helios::rendering::model::MaterialInstance::shader () const nodiscard export noexcept
Returns a shared pointer to the shader used by the Material.
Delegates to Material::shader().
Returns
A shared_ptr to the Shader that the underlying Material uses.
Referenced by writeUniformValues().
writeUniformValues()
void helios::rendering::model::MaterialInstance::writeUniformValues (helios::rendering::shader::UniformValueMap & uniformValueMap) const export noexcept
Writes this MaterialInstance's uniform values into the given map.
This method first applies the default uniform values from the base Material definition and then overlays any specific overrides provided by this instance's MaterialPropertiesOverride.
Parameters
uniformValueMap Target map receiving the uniform values.
References shader(), and writeUniformValues().
Referenced by writeUniformValues().
The documentation for this class was generated from the following file:
include/helios/rendering/model/MaterialInstance.ixx