helios: helios::engine::game::components::model::ModelAabbComponent Class Reference
helios::engine::game::components::model::ModelAabbComponent Class Reference export
module helios.engine.game.components.model.ModelAabbComponent
Component that stores the canonical Axis-Aligned Bounding Box (AABB) of a model.
Public Member Functions
ModelAabbComponent ()=default
Default constructor.
void setAabb (const helios::math::aabbf &aabb)
Sets the AABB for this component.
const helios::math::aabbf & aabb () const noexcept
Retrieves the stored AABB.
Public Member Functions inherited from helios::engine::game::Component
virtual ~Component ()=default
Component ()=default
virtual void onAttach (GameObject *gameObject) noexcept
Called when the component is attached to a GameObject.
GameObject * gameObject () const noexcept
Returns the owning GameObject.
Additional Inherited Members
Protected Attributes inherited from helios::engine::game::Component
GameObject * gameObject_ = nullptr
Non-owning pointer to the owning GameObject.
Detailed Description
Component that stores the canonical Axis-Aligned Bounding Box (AABB) of a model.
This component is used to associate spatial bounds with an entity, typically derived from a 3D model or mesh. It is essential for culling, collision detection, and other spatial queries.
Definition at line 19 of file ModelAabbComponent.ixx.
Constructor & Destructor Documentation
ModelAabbComponent()
helios::engine::game::components::model::ModelAabbComponent::ModelAabbComponent () export default
Default constructor.
Member Function Documentation
aabb()
const helios::math::aabbf & helios::engine::game::components::model::ModelAabbComponent::aabb () const inline nodiscard export noexcept
Retrieves the stored AABB.
Returns
Constant reference to the AABB.
Definition at line 49 of file ModelAabbComponent.ixx.
Referenced by setAabb().
setAabb()
void helios::engine::game::components::model::ModelAabbComponent::setAabb (const helios::math::aabbf & aabb) inline export
Sets the AABB for this component.
Parameters
aabb The new AABB to store.
Definition at line 39 of file ModelAabbComponent.ixx.
References aabb().
Referenced by helios::engine::game::components::scene::SceneNodeComponent::onAttach().
The documentation for this class was generated from the following file:
include/helios/engine/game/components/model/ModelAabbComponent.ixx