helios: helios::tooling::FpsMetrics Class Reference
helios::tooling::FpsMetrics Class Reference export
module helios.tooling.FpsMetrics
Aggregates and analyzes frame timing data over a rolling window.
Public Member Functions
void addFrame (const helios::engine::FrameStats &stats)
Adds a frame's statistics to the metrics history.
void setHistorySize (size_t size)
Sets the size of the frame history buffer.
size_t getHistorySize () const noexcept
Gets the current history buffer size.
float getFps () noexcept
Gets the average frames per second.
float getFrameTimeMs () noexcept
Gets the average frame time in milliseconds.
float getWorkTimeMs () noexcept
Gets the most recent frame's work time.
float getIdleTimeMs () noexcept
Gets the most recent frame's idle time.
unsigned long long getFrameCount () const noexcept
Gets the frame count.
float getFrameTimeSeconds () noexcept
Gets the average frame time in seconds.
float getWorkTimeSeconds () noexcept
Gets the most recent frame's work time in seconds.
float getIdleTimeSeconds () noexcept
Gets the most recent frame's idle time in seconds.
const std::deque< helios::engine::FrameStats > & getHistory () const noexcept
Gets the complete frame history.
void reset ()
Clears all collected metrics and resets to initial state.
Detailed Description
Aggregates and analyzes frame timing data over a rolling window.
FpsMetrics collects FrameStats data from multiple frames and calculates average FPS and frame times. It maintains a configurable history buffer for smoothing out momentary fluctuations in frame rate.
This class is particularly useful for debugging, profiling, and displaying performance metrics in development tools or debug overlays.
Usage Example:
```cpp helios::tooling::FpsMetrics metrics; metrics.setHistorySize(120);
// In game loop: helios::engine::FrameStats stats = framePacer.sync(); metrics.addFrame(stats);
float fps = metrics.getFps(); float avgFrameTime = metrics.getFrameTimeMs(); ```
Definition at line 39 of file FpsMetrics.ixx.
Member Function Documentation
addFrame()
void helios::tooling::FpsMetrics::addFrame (const helios::engine::FrameStats & stats) export
Adds a frame's statistics to the metrics history.
Processes the provided FrameStats, updates the rolling history, and marks cached values as dirty so they will be recomputed on the next query. Old frames are automatically removed when the history buffer exceeds the configured size. Additionally, the `frameCount_` member is increased by one for each call.
Parameters
stats Frame statistics to add to the history.
Note
When used together with FramePacer, a typical usage pattern is:
helios::engine::FrameStats stats = framePacer.sync();
metrics.addFrame(stats);
This should usually be called once per frame at the end of the frame loop, after timing information for the current frame has been measured.
getFps()
float helios::tooling::FpsMetrics::getFps () nodiscard export noexcept
Gets the average frames per second.
Triggers a lazy recomputation of the underlying metrics if new frames have been added since the last query.
Returns
Average FPS calculated over the frames stored in the history buffer.
References getFps().
Referenced by getFps().
getFrameCount()
unsigned long long helios::tooling::FpsMetrics::getFrameCount () const nodiscard export noexcept
Gets the frame count.
Returns
The total number of frames that have been added via `addFrame()`.
References getFrameCount().
Referenced by getFrameCount().
getFrameTimeMs()
float helios::tooling::FpsMetrics::getFrameTimeMs () nodiscard export noexcept
Gets the average frame time in milliseconds.
Triggers a lazy recomputation of the underlying metrics if needed.
Returns
Average total frame time (work + wait) in milliseconds.
References getFrameTimeMs().
Referenced by getFrameTimeMs().
getFrameTimeSeconds()
float helios::tooling::FpsMetrics::getFrameTimeSeconds () nodiscard export noexcept
Gets the average frame time in seconds.
Convenience wrapper returning the same value as `getFrameTimeMs()` converted from milliseconds to seconds.
Returns
Average total frame time (work + wait) in seconds.
References getFrameTimeSeconds().
Referenced by getFrameTimeSeconds().
getHistory()
const std::deque< helios::engine::FrameStats > & helios::tooling::FpsMetrics::getHistory () const nodiscard export noexcept
Gets the complete frame history.
Returns
Const reference to the deque containing the full frame statistics history.
Note
Useful for rendering frame time graphs or diagnostic views in debug overlays.
References getHistory().
Referenced by getHistory().
getHistorySize()
size_t helios::tooling::FpsMetrics::getHistorySize () const nodiscard export noexcept
Gets the current history buffer size.
Returns
Maximum number of frames kept in history.
getIdleTimeMs()
float helios::tooling::FpsMetrics::getIdleTimeMs () nodiscard export noexcept
Gets the most recent frame's idle time.
Triggers a lazy recomputation if required.
Returns
Wait/idle time of the last processed frame in milliseconds.
References getIdleTimeMs().
Referenced by getIdleTimeMs().
getIdleTimeSeconds()
float helios::tooling::FpsMetrics::getIdleTimeSeconds () nodiscard export noexcept
Gets the most recent frame's idle time in seconds.
Convenience wrapper returning the same value as `getIdleTimeMs()` converted from milliseconds to seconds.
Returns
Wait/idle time of the last processed frame in seconds.
References getIdleTimeSeconds().
Referenced by getIdleTimeSeconds().
getWorkTimeMs()
float helios::tooling::FpsMetrics::getWorkTimeMs () nodiscard export noexcept
Gets the most recent frame's work time.
Triggers a lazy recomputation if required.
Returns
Work time of the last processed frame in milliseconds.
References getWorkTimeMs().
Referenced by getWorkTimeMs().
getWorkTimeSeconds()
float helios::tooling::FpsMetrics::getWorkTimeSeconds () nodiscard export noexcept
Gets the most recent frame's work time in seconds.
Convenience wrapper returning the same value as `getWorkTimeMs()` converted from milliseconds to seconds.
Returns
Work time of the last processed frame in seconds.
References getWorkTimeSeconds().
Referenced by getWorkTimeSeconds().
reset()
void helios::tooling::FpsMetrics::reset () export
Clears all collected metrics and resets to initial state.
Removes all stored frame statistics and resets cached metrics and counters to their default values. After calling this function, all query functions will report zeros until new frames are added.
References reset().
Referenced by reset().
setHistorySize()
void helios::tooling::FpsMetrics::setHistorySize (size_t size) export
Sets the size of the frame history buffer.
Determines how many frames are used for calculating averages. Larger values produce smoother metrics but respond slower to changes.
Parameters
size Number of frames to keep in history (default: 60).
Note
Common values: 30 for roughly half-second average at 60 FPS, 60 for roughly one-second average at 60 FPS.
The documentation for this class was generated from the following file:
include/helios/tooling/FpsMetrics.ixx