helios: helios::scene::SceneNode Class Reference
helios::scene::SceneNode Class Reference export
module helios.scene.SceneNode
Represents a SceneNode within a SceneGraph.
Public Member Functions
virtual ~SceneNode ()=default
SceneNode (const SceneNode &)=delete
Delete copy constructor. A SceneNode is not copyable.
SceneNode & operator= (const SceneNode &)=delete
Delete copy assignment operator.
SceneNode () noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
SceneNode (const Transform &transform) noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable, const Transform &transform) noexcept
Constructs a new SceneNode representing a renderable object.
SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable) noexcept
Constructs a new SceneNode representing a renderable object.
const helios::util::Guid & guid () const noexcept
Returns the globally unique identifier for this SceneNode.
virtual SceneNode * addNode (std::unique_ptr< SceneNode > sceneNode)
Adds a new child node to this SceneNode. The node's parent is automatically set to **this** node.
const std::vector< std::unique_ptr< SceneNode > > & children () const noexcept
Returns a const ref to the list of this node's children.
std::shared_ptr< const helios::rendering::Renderable > renderable () const noexcept
Returns a shared pointer to the Renderable of this SceneNode.
bool hasRenderable () const noexcept
Returns true if this SceneNode was configured with a Renderable.
std::shared_ptr< helios::rendering::Renderable > renderable () noexcept
Returns a shared pointer to the non-const Renderable of this SceneNode.
SceneNode & setScale (const helios::math::vec3f &scale) noexcept
Applies a scaling transformation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
SceneNode & setRotation (const helios::math::mat4f &rotation) noexcept
Applies rotation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
SceneNode & setTranslation (const helios::math::vec3f &translation) noexcept
Applies translation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
const Transform & localTransform () const noexcept
Returns this SceneNode's localTransform.
Transform & localTransform () noexcept
Returns this SceneNode's localTransform.
SceneNode * parent () const noexcept
Returns a pointer to this node's parent node.
bool applyWorldTransform (const helios::math::mat4f &wf, helios::scene::SceneGraphKey sceneGraphKey) noexcept
Sets the world transform for this SceneNode.
const helios::math::mat4f & worldTransform () noexcept
Computes and returns the world transform for this SceneNode. Will request the current world transform from the parent node to calculate this SceneNode's world transform. For efficiency, this method should cache the result and only trigger a recompute if this SceneNode is dirty (`needsUpdate_ == true`).
const helios::math::mat4f & cachedWorldTransform () const noexcept
Returns the current worldTransform matrix of this SceneNode **without triggering any recomputation**. This method is efficient for access when the world transform is known to be up-to-date.
bool needsUpdate () const noexcept
Checks whether this SceneNode needs to be updated.
helios::math::aabbf aabb () noexcept
Returns the axis-aligned bounding box for this SceneNode in world coordinates.
void update () noexcept
Updates the world transform and axis-aligned bounding box of this SceneNode.
virtual void onWorldTransformUpdate () noexcept
Virtual callback invoked after the world transform has been updated.
helios::math::mat4f inheritWorldTransform (const helios::math::mat4f &parentWorldTransform) noexcept
Filters a parent world transform based on the node's inheritance flags.
void setInheritance (const helios::math::TransformType inherit) noexcept
Sets which transform components this node inherits from its parent.
helios::math::TransformType inheritance () const noexcept
Returns the current transform inheritance flags for this node.
bool isActive () const noexcept
Returns whether this SceneNode and its child nodes should be considered for rendering.
void setActive (bool active) noexcept
Sets the active state of this SceneNode.
Protected Member Functions
void setParent (SceneNode *parentNode)
Sets the parent of this SceneNode. Internally used once a child was added to this SceneNode.
Protected Attributes
bool needsUpdate_ = true
Boolean flag to represent the dirty-state of this node. Should be set to false if the current `worldTransform_` for this node was computed, otherwise true, e.g. if the node's local transform has been changed.
std::shared_ptr< helios::rendering::Renderable > renderable_
A shared pointer to the Renderable this node represents in the SceneGraph. May be nullptr if this node does not represent a renderable object.
SceneNode * parent_ = nullptr
The parent node of **this** node. This will be nullptr for any root node. Implementing APIs must take care of properly assigning parent nodes when adding child nodes.
std::vector< std::unique_ptr< SceneNode > > children_
A list of unique pointers to this node's children. Ensures ownership of the child nodes withing the graph hierarchy.
math::mat4f worldTransform_ = math::mat4f::identity()
The 4x4 worldTransform-Matrix of this node. This matrix is initially set to the identity matrix. Implementing APIs MUST make sure to recompute the worldTransform before each rendering pass.
Transform localTransform_
A local transformation representing affine transformation information for this SceneNode. Encapsulates rotation, scaling and translation.
bool isActive_ = true
Boolean flag indicating whether this SceneNode should be considered for rendering.
helios::math::aabbf aabb_ {}
The axis-aligned-bounding-box for this SceneNode in world-coordinates.
helios::math::TransformType inheritance_ = helios::math::TransformType::All
Flags controlling which transform components are inherited from the parent node.
Detailed Description
Represents a SceneNode within a SceneGraph.
A SceneNode holds its local transformation and a (shared) pointer to a Renderable object (the representative of a visible element). Furthermore, a SceneNode can have multiple child nodes uniquely owned by **this** SceneNode.
A SceneNode holds a global unique identifier and tracks a dirty state (`needsUpdate_`) related to any transformations that occurred on the SceneNode. Ownership is managed by a collection of unique pointers of the child nodes. SceneNodes are designed to be not copyable and not assignable to prevent duplication and to enforce the hierarchical tree structure.
The `worldTransform_` is derived from a SceneNode's `localTransform_` and the SceneNode's parent's `worldTransform`s. A call to `worldTransform()` will update the particular subtree of the SceneNode bottom-up to make sure the actual values are available with the SceneNode's `worldTransform`. A Scene might also propagate changes top-bottom - see `Scene::updateNodes()`.
Definition at line 60 of file SceneNode.ixx.
Constructor & Destructor Documentation
~SceneNode()
virtual helios::scene::SceneNode::~SceneNode () export virtual default
SceneNode() [1/5]
helios::scene::SceneNode::SceneNode (const SceneNode &) export delete
Delete copy constructor. A SceneNode is not copyable.
References SceneNode().
Referenced by helios::scene::CameraSceneNode::addNode(), addNode(), children(), operator=(), parent(), SceneNode(), SceneNode(), SceneNode(), SceneNode(), setParent(), setRotation(), setScale(), and setTranslation().
SceneNode() [2/5]
helios::scene::SceneNode::SceneNode () export noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
Todo
explicitly implement move (assignment) constructor if required, since we have deleted the copy constructors
SceneNode() [3/5]
helios::scene::SceneNode::SceneNode (const Transform & transform) explicit export noexcept
Constructs a new SceneNode that represents no renderable object. Nodes constructed in this way should be treated as transformation nodes.
Parameters
transform The initial transformation for this node.
References SceneNode().
SceneNode() [4/5]
helios::scene::SceneNode::SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable, const Transform & transform) explicit export noexcept
Constructs a new SceneNode representing a renderable object.
Parameters
renderable A shared_ptr to the Renderable this SceneNode represents in a Scene.
transform The initial local transform for this node.
References renderable(), and SceneNode().
SceneNode() [5/5]
helios::scene::SceneNode::SceneNode (std::shared_ptr< helios::rendering::Renderable > renderable) explicit export noexcept
Constructs a new SceneNode representing a renderable object.
Parameters
renderable A shared_ptr to the Renderable this SceneNode represents in a Scene.
References renderable(), and SceneNode().
Member Function Documentation
aabb()
helios::math::aabbf helios::scene::SceneNode::aabb () nodiscard export noexcept
Returns the axis-aligned bounding box for this SceneNode in world coordinates.
Returns
The AABB transformed to world space.
References aabb().
Referenced by aabb(), and helios::engine::game::systems::gameplay::ProjectilePoolSystem::prepareProjectiles().
addNode()
virtual SceneNode * helios::scene::SceneNode::addNode (std::unique_ptr< SceneNode > sceneNode) nodiscard export virtual
Adds a new child node to this SceneNode. The node's parent is automatically set to **this** node.
Parameters
sceneNode The node to add as a child.
Returns
The raw pointer to the newly added node, or nullptr if adding failed
Reimplemented in helios::scene::CameraSceneNode.
References addNode(), and SceneNode().
Referenced by addNode().
applyWorldTransform()
bool helios::scene::SceneNode::applyWorldTransform (const helios::math::mat4f & wf, helios::scene::SceneGraphKey sceneGraphKey) nodiscard export noexcept
Sets the world transform for this SceneNode.
Does nothing if the current SceneNode's world transform is considered equal to the specified world transform.
Parameters
wf The worldTransform to use for this SceneNode.
sceneGraphKey The sceneGraphKey as constructed by the `Scene`. Serves as the passkey so this method is not callable from outside.
Returns
true if the world transform was updated, otherwise false.
References applyWorldTransform().
Referenced by applyWorldTransform().
cachedWorldTransform()
const helios::math::mat4f & helios::scene::SceneNode::cachedWorldTransform () const nodiscard export noexcept
Returns the current worldTransform matrix of this SceneNode **without triggering any recomputation**. This method is efficient for access when the world transform is known to be up-to-date.
Returns
The current worldTransform matrix of this SceneNode.
References cachedWorldTransform().
Referenced by cachedWorldTransform().
children()
const std::vector< std::unique_ptr< SceneNode > > & helios::scene::SceneNode::children () const nodiscard export noexcept
Returns a const ref to the list of this node's children.
Returns
A const ref to the list of children of this node.
References children(), and SceneNode().
Referenced by children().
guid()
const helios::util::Guid & helios::scene::SceneNode::guid () const nodiscard export noexcept
Returns the globally unique identifier for this SceneNode.
Returns
The unique identifier for this SceneNode.
References guid().
Referenced by guid().
hasRenderable()
bool helios::scene::SceneNode::hasRenderable () const nodiscard export noexcept
Returns true if this SceneNode was configured with a Renderable.
Returns
true if the SceneNode was configured with a Renderable, otherwise false.
References hasRenderable().
Referenced by hasRenderable().
inheritance()
helios::math::TransformType helios::scene::SceneNode::inheritance () const nodiscard export noexcept
Returns the current transform inheritance flags for this node.
Returns
The active inheritance mask.
See also
setInheritance()
References inheritance().
Referenced by inheritance().
inheritWorldTransform()
helios::math::mat4f helios::scene::SceneNode::inheritWorldTransform (const helios::math::mat4f & parentWorldTransform) export noexcept
Filters a parent world transform based on the node's inheritance flags.
This method extracts only the transform components (Translation, Rotation, Scale) that this node is configured to inherit from its parent. Components not included in `inheritance_` are replaced with identity values.
Parameters
parentWorldTransform The parent's world transform matrix.
Returns
A filtered transform matrix containing only the inherited components.
See also
setInheritance()
helios::math::TransformType
References inheritWorldTransform().
Referenced by inheritWorldTransform().
isActive()
bool helios::scene::SceneNode::isActive () const nodiscard export noexcept
Returns whether this SceneNode and its child nodes should be considered for rendering.
Returns
true if the SceneNode should be considered for rendering, otherwise false.
References isActive().
Referenced by isActive().
localTransform() [1/2]
const Transform & helios::scene::SceneNode::localTransform () const nodiscard export noexcept
Returns this SceneNode's localTransform.
Returns
A const reference to this SceneNode's `Transform` object.
References localTransform().
Referenced by localTransform(), and localTransform().
localTransform() [2/2]
Transform & helios::scene::SceneNode::localTransform () nodiscard export noexcept
Returns this SceneNode's localTransform.
Returns
A reference to this SceneNode's `Transform` object.
References localTransform().
needsUpdate()
bool helios::scene::SceneNode::needsUpdate () const nodiscard export noexcept
Checks whether this SceneNode needs to be updated.
The SceneNode is considered "dirty" if either the `localTransform_` needs an update, or if the `needsUpdate_` property is set to true.
Returns
true if this SceneNode is considered to be dirty, otherwise false.
References needsUpdate().
Referenced by needsUpdate().
onWorldTransformUpdate()
virtual void helios::scene::SceneNode::onWorldTransformUpdate () export virtual noexcept
Virtual callback invoked after the world transform has been updated.
Derived classes can override this method to perform additional processing when the node's world transform changes, such as updating dependent resources or triggering view matrix recalculations in camera nodes.
Reimplemented in helios::scene::CameraSceneNode.
References onWorldTransformUpdate().
Referenced by onWorldTransformUpdate().
operator=()
SceneNode & helios::scene::SceneNode::operator= (const SceneNode &) export delete
Delete copy assignment operator.
A SceneNode is not intended to be copied.
References SceneNode().
parent()
SceneNode * helios::scene::SceneNode::parent () const nodiscard export noexcept
Returns a pointer to this node's parent node.
Returns
The pointer to this node's parent, or nullptr if no parent exists, e.g. for the root node.
References parent(), and SceneNode().
Referenced by parent().
renderable() [1/2]
std::shared_ptr< const helios::rendering::Renderable > helios::scene::SceneNode::renderable () const nodiscard export noexcept
Returns a shared pointer to the Renderable of this SceneNode.
Returns
A shared_ptr to the Renderable, may be nullptr if none is set.
References renderable().
Referenced by renderable(), renderable(), SceneNode(), and SceneNode().
renderable() [2/2]
std::shared_ptr< helios::rendering::Renderable > helios::scene::SceneNode::renderable () nodiscard export noexcept
Returns a shared pointer to the non-const Renderable of this SceneNode.
Returns
A shared_ptr to the Renderable, may be nullptr if none is set.
References renderable().
setActive()
void helios::scene::SceneNode::setActive (bool active) export noexcept
Sets the active state of this SceneNode.
The active state determines whether the SceneNode should be considered for rendering.
Parameters
active true to consider this SceneNodefor rendering, otherwise false.
References setActive().
Referenced by setActive().
setInheritance()
void helios::scene::SceneNode::setInheritance (const helios::math::TransformType inherit) export noexcept
Sets which transform components this node inherits from its parent.
By default, nodes inherit all transform components (`TransformType::All`). Use this method to selectively inherit only Translation, Rotation, or Scale, enabling behaviors like cameras that follow an object's position but maintain independent orientation.
Parameters
inherit The inheritance flags to apply.
See also
helios::math::TransformType
References setInheritance().
Referenced by setInheritance().
setParent()
void helios::scene::SceneNode::setParent (SceneNode * parentNode) export protected
Sets the parent of this SceneNode. Internally used once a child was added to this SceneNode.
Parameters
parentNode The parent of this SceneNode
See also
addNode()
References SceneNode().
setRotation()
SceneNode & helios::scene::SceneNode::setRotation (const helios::math::mat4f & rotation) export noexcept
Applies rotation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
Parameters
rotation The helios::math::mat4f rotation matrix.
Returns
A reference to this SceneNode.
References SceneNode(), and setRotation().
Referenced by setRotation().
setScale()
SceneNode & helios::scene::SceneNode::setScale (const helios::math::vec3f & scale) export noexcept
Applies a scaling transformation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
Parameters
scale The helios::math::vec3f representing the node's scaling factors.
Returns
A reference to this SceneNode.
References SceneNode(), and setScale().
Referenced by setScale().
setTranslation()
SceneNode & helios::scene::SceneNode::setTranslation (const helios::math::vec3f & translation) export noexcept
Applies translation to this node's **local** transform. Marks the node dirty. Implementing APIs should consider updating the worldTransform of this node before rendering.
Parameters
translation The helios::math::vec3f representing the node's translation.
Returns
A reference to this SceneNode.
References SceneNode(), and setTranslation().
Referenced by setTranslation().
update()
void helios::scene::SceneNode::update () export noexcept
Updates the world transform and axis-aligned bounding box of this SceneNode.
Recomputes the `worldTransform_` based on the parent's world transform and this node's `localTransform_`. Also updates the `aabb_` to reflect the current world-space bounds.
References update().
Referenced by update().
worldTransform()
const helios::math::mat4f & helios::scene::SceneNode::worldTransform () export noexcept
Computes and returns the world transform for this SceneNode. Will request the current world transform from the parent node to calculate this SceneNode's world transform. For efficiency, this method should cache the result and only trigger a recompute if this SceneNode is dirty (`needsUpdate_ == true`).
Returns
The current world transform matrix for this scene node.
References worldTransform().
Referenced by worldTransform().
The documentation for this class was generated from the following file:
include/helios/scene/SceneNode.ixx