helios: helios::core::units Namespace Reference
helios::core::units Namespace Reference export
Enumerations
enum class helios::core::units::Unit { Meter , Centimeter , Seconds , MilliSeconds }
Enumeration of length and time units supported by helios.
Functions
constexpr float helios::core::units::fromCm (const float cm) noexcept
Converts centimeters to meters.
constexpr float helios::core::units::fromM (const float m) noexcept
Pass-through helper for meter values.
constexpr helios::math::vec3f helios::core::units::fromM (helios::math::vec3f v) noexcept
Pass-through helper for meter vectors.
constexpr helios::math::aabbf helios::core::units::fromM (helios::math::aabbf v) noexcept
Pass-through helper for meter AABBs.
constexpr float helios::core::units::fromS (const float s) noexcept
Converts seconds to seconds (identity helper).
constexpr float helios::core::units::fromMs (const float ms) noexcept
Converts milliseconds to seconds.
constexpr float helios::core::units::from (const float v, const Unit unit) noexcept
Converts a value from a given unit to helios units.
constexpr helios::math::aabbf helios::core::units::from (helios::math::aabbf aabb, const Unit unit) noexcept
Converts an AABB from a given unit to helios units.
Variables
constexpr auto helios::core::units::HELIOS_SPATIAL_UNIT = Unit::Meter
Default length unit used throughout helios (1 meter per helios unit).
constexpr auto helios::core::units::HELIOS_TEMPORAL_UNIT = Unit::Seconds
Default time unit used for all timing APIs (seconds).
constexpr float helios::core::units::CENTIMETERS = 0.01f
Ratio of centimeters to meters.
constexpr float helios::core::units::METERS = 1.0f
Ratio of meters to meters (identity).
constexpr float helios::core::units::MILLISECONDS = 0.001f
Ratio of milliseconds to seconds.
constexpr float helios::core::units::SECONDS = 1.0f
Ratio of seconds to seconds (identity).
Enumeration Type Documentation
Unit
enum class helios::core::units::Unit export strong
Enumeration of length and time units supported by helios.
Enumerator
Meter
Base length unit (meters) in helios. 1.0f represents 1 meter.
Centimeter
Centimeter helper unit for authoring convenience. Converted to meters (0.01f) when used.
Seconds
Base time unit (seconds) in helios. 1.0f represents 1 second.
MilliSeconds
Millisecond helper unit derived from seconds. Converted to seconds (0.001f) when used.
Definition at line 18 of file units.ixx.
Function Documentation
from() [1/2]
float helios::core::units::from (const float v, const Unit unit) nodiscard constexpr export noexcept
Converts a value from a given unit to helios units.
This method takes a value in the specified unit and converts it to helios units, e.g. spatial units to METER, temporal values to SECONDS.
Parameters
v Value to convert.
unit Unit of the value to convert.
Returns
Value expressed in temporal or spatial helios units.
Definition at line 155 of file units.ixx.
References Centimeter, fromCm(), fromM(), fromMs(), fromS(), Meter, MilliSeconds, and Seconds.
Referenced by helios::engine::game::Level::setBounds(), and helios::engine::game::systems::physics::ScaleSystem::update().
from() [2/2]
helios::math::aabbf helios::core::units::from (helios::math::aabbf aabb, const Unit unit) nodiscard constexpr export noexcept
Converts an AABB from a given unit to helios units.
Parameters
aabb AABB to convert.
unit Unit of the AABB coordinates.
Returns
AABB expressed in helios spatial units (meters).
Definition at line 178 of file units.ixx.
References fromM(), and Meter.
fromCm()
float helios::core::units::fromCm (const float cm) constexpr export noexcept
Converts centimeters to meters.
Parameters
cm Value expressed in centimeters.
Returns
Converted value expressed in meters.
Definition at line 82 of file units.ixx.
References CENTIMETERS.
Referenced by from().
fromM() [1/3]
float helios::core::units::fromM (const float m) constexpr export noexcept
Pass-through helper for meter values.
Parameters
m Value expressed in meters.
Returns
Same value expressed in meters.
Definition at line 93 of file units.ixx.
References METERS.
Referenced by from(), and from().
fromM() [2/3]
helios::math::aabbf helios::core::units::fromM (helios::math::aabbf v) constexpr export noexcept
Pass-through helper for meter AABBs.
Parameters
v AABB with bounds expressed in meters.
Returns
AABB with bounds expressed in meters.
Definition at line 115 of file units.ixx.
References METERS.
fromM() [3/3]
helios::math::vec3f helios::core::units::fromM (helios::math::vec3f v) constexpr export noexcept
Pass-through helper for meter vectors.
Parameters
v Vector with components expressed in meters.
Returns
Vector with components expressed in meters.
Definition at line 104 of file units.ixx.
References METERS.
fromMs()
float helios::core::units::fromMs (const float ms) constexpr export noexcept
Converts milliseconds to seconds.
Parameters
ms Value expressed in milliseconds.
Returns
Converted value expressed in seconds.
Definition at line 140 of file units.ixx.
References MILLISECONDS.
Referenced by from().
fromS()
float helios::core::units::fromS (const float s) constexpr export noexcept
Converts seconds to seconds (identity helper).
Parameters
s Value expressed in seconds.
Returns
Same value expressed in seconds.
Definition at line 129 of file units.ixx.
References SECONDS.
Referenced by from().
Variable Documentation
CENTIMETERS
float helios::core::units::CENTIMETERS = 0.01f constexpr export
Ratio of centimeters to meters.
Definition at line 58 of file units.ixx.
Referenced by fromCm().
HELIOS_SPATIAL_UNIT
auto helios::core::units::HELIOS_SPATIAL_UNIT = Unit::Meter constexpr export
Default length unit used throughout helios (1 meter per helios unit).
Definition at line 48 of file units.ixx.
HELIOS_TEMPORAL_UNIT
auto helios::core::units::HELIOS_TEMPORAL_UNIT = Unit::Seconds constexpr export
Default time unit used for all timing APIs (seconds).
Definition at line 53 of file units.ixx.
METERS
float helios::core::units::METERS = 1.0f constexpr export
Ratio of meters to meters (identity).
Definition at line 63 of file units.ixx.
Referenced by fromM(), fromM(), and fromM().
MILLISECONDS
float helios::core::units::MILLISECONDS = 0.001f constexpr export
Ratio of milliseconds to seconds.
Definition at line 68 of file units.ixx.
Referenced by fromMs().
SECONDS
float helios::core::units::SECONDS = 1.0f constexpr export
Ratio of seconds to seconds (identity).
Definition at line 73 of file units.ixx.
Referenced by fromS().