helios: helios::math Namespace Reference
helios::math Namespace Reference export
Mathematical operations and types.
Namespaces
namespace concepts
Mathematical concepts for type constraints.
namespace transform
Transformation utilities for 3D graphics and scene graph inheritance.
namespace types
Vector and matrix types.
Classes
struct aabb
Axis-Aligned Bounding Box for spatial culling and collision detection.
struct mat4
Represents a 4x4 matrix, stored in column-major order.
struct vec3
Represents a 3-dimensional vector of the generic type <T>.
struct vec2
Represents a 2-dimensional vector of the generic type <T>.
struct vec4
Represents a 4-dimensional vector of the generic type <T>.
Concepts
concept Numeric
Concept to constrain types to either integral or floating point.
Typedefs
template<typename T>
using helios::math::FloatingPointType
Type trait that promotes integral types to double, while preserving floating-point types.
using helios::math::aabbf = aabb<float>
Single-precision floating-point AABB.
using helios::math::aabbi = aabb<int>
Integer AABB.
using helios::math::aabbd = aabb<double>
Double-precision floating-point AABB.
using helios::math::mat4f = mat4<float>
using helios::math::mat4d = mat4<double>
using helios::math::mat4i = mat4<int>
using helios::math::vec2f = vec2<float>
using helios::math::vec2d = vec2<double>
using helios::math::vec2i = vec2<int>
using helios::math::vec3f = vec3<float>
Single-precision floating-point 3D vector.
using helios::math::vec3i = vec3<int>
Integer 3D vector.
using helios::math::vec3d = vec3<double>
Double-precision floating-point 3D vector.
using helios::math::vec4f = vec4<float>
Single-precision floating-point 4D vector.
using helios::math::vec4d = vec4<double>
Double-precision floating-point 4D vector.
using helios::math::vec4i = vec4<int>
Integer 4D vector.
Enumerations
enum class helios::math::TransformType : uint8_t { Translation = 1 << 0 , Rotation = 1 << 1 , Scale = 1 << 2 , All = Translation | Rotation | Scale }
Bitmask enum controlling which transform components a child node inherits from its parent.
Functions
mat4f helios::math::perspective (float fovY, float aspect, float zNear, float zFar) noexcept
Computes the 4x4 perspective projection matrix based on the specified field of view, aspect ratio, and near and far clipping planes.
mat4f helios::math::lookAt (const vec3f &eye, const vec3f &center, const vec3f &up) noexcept
Returns the 4x4 lookAt-matrix for transforming world coordinates to camera space. The method creates the camera coordinate system based on the parameters eye, i.e. the vantage point in world space, the camera's up direction and center, representing the point of interest. Note that the returned matrix is essentially a composition of a change of coordinates matrix P(C <- W) and a translation to the origin, i.e. the camera is sitting at the origin (0, 0, 0) looking down the negative z-axis, i.e. conceptually.
mat4f helios::math::rotate (const mat4f &model, float radians, const vec3f &axis) noexcept
Creates an affine rotation matrix R' = M * R by "baking" the rotation part into the model matrix. Any operation R' * v will make sure that v is rotated around the local origin, then transformed into world space.
constexpr mat4f helios::math::translate (const mat4f &model, const vec3f &v) noexcept
Creates an affine transformation matrix M' = M * T by "baking" the translation part into the model matrix. Any operation M' * v will make sure that v is translated in local space, then transformed into world space.
constexpr mat4f helios::math::scale (const mat4f &model, const vec3f &v) noexcept
Creates an affine transformation matrix S' = M * S by ""baking" the scaling part into the model matrix. Any operation S' * v will make sure that v is scaled in local space, then transformed into world space.
constexpr mat4f helios::math::scale (const mat4f &model, const float scale_by) noexcept
Creates an affine transformation matrix S' = M * S by "baking" the scaling part into the model matrix. Any operation S' * v will make sure that v is scaled in local space, then transformed into world space.
TransformType helios::math::operator| (TransformType a, TransformType b)
Combines two Inherit flags using bitwise OR.
bool helios::math::transformTypeMatch (TransformType mask, TransformType flag)
Checks if a specific inheritance flag is set in a mask.
template<typename T>
constexpr helios::math::aabb< T > helios::math::operator+ (const helios::math::aabb< T > aabb, const helios::math::vec3< T > v) noexcept
Adds a translation vector to an AABB.
template<typename T>
constexpr helios::math::aabb< T > helios::math::operator* (const helios::math::aabb< T > &aabb, const helios::math::vec3< T > v) noexcept
Scales an AABB by a given vector.
template<helios::math::Numeric T>
const T * helios::math::value_ptr (const mat4< T > &m) noexcept
Returns a const pointer to the first element of the matrix's components.
template<helios::math::Numeric T>
T * helios::math::value_ptr (mat4< T > &m) noexcept
Returns a pointer to the first element of the matrix's components.
template<helios::math::Numeric T>
constexpr vec2< T > helios::math::operator* (const vec2< T > &v, const T n) noexcept
Multiplies a 2D vector by a scalar value.
template<helios::math::Numeric T>
constexpr T helios::math::dot (const vec2< T > &v1, const vec2< T > &v2) noexcept
Computes the dot product of two 2D vectors.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::operator* (const vec3< T > &v, const T n) noexcept
Multiplies a 3D vector by a scalar value.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::operator/ (const vec3< T > &v, T s) noexcept
Divides a 3D vector by a scalar value.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::operator* (const T n, const vec3< T > &v) noexcept
Multiplies a scalar value by a 3D vector.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::operator* (const vec3< T > &v1, const vec3< T > &v2) noexcept
Multiplies two vectors componentwise.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::operator+ (const vec3< T > &v1, const vec3< T > &v2) noexcept
Calculates the componentwise sum of the two vectors.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::cross (const vec3< T > &v1, const vec3< T > &v2) noexcept
Computes the cross product of two 3D vectors.
template<helios::math::Numeric T>
constexpr T helios::math::dot (const vec3< T > &v1, const vec3< T > &v2) noexcept
Computes the dot product of two 3D vectors.
template<helios::math::Numeric T>
constexpr vec3< T > helios::math::operator- (const vec3< T > &v1, const vec3< T > &v2) noexcept
Computes the difference between two vectors (vector subtraction).
template<helios::math::Numeric T>
const T * helios::math::value_ptr (const vec4< T > &m) noexcept
Returns a const pointer to the first element of the vector's components.
constexpr float helios::math::radians (const float angle) noexcept
Converts an angle from degrees to radians.
constexpr float helios::math::degrees (const float radians) noexcept
Converts an angle from radians to degrees.
Variables
constexpr float helios::math::EPSILON_LENGTH = 1e-6f
A small epsilon value used for length-based comparisons.
Detailed Description
Mathematical operations and types.
This namespace provides comprehensive mathematical functionality including vector and matrix types, transformation utilities, mathematical concepts, and utility functions for 3D graphics and game framework computations. Provides all mathematical operations required for 3D graphics, including transformations, projections, and spatial computations.
Typedef Documentation
aabbd
using helios::math::aabbd = aabb<double> export
Double-precision floating-point AABB.
Definition at line 283 of file aabb.ixx.
aabbf
using helios::math::aabbf = aabb<float> export
Single-precision floating-point AABB.
Definition at line 273 of file aabb.ixx.
aabbi
using helios::math::aabbi = aabb<int> export
Integer AABB.
Definition at line 278 of file aabb.ixx.
FloatingPointType
template<typename T> using helios::math::FloatingPointType export
Initial value:
 std::conditional_t<
        std::is_floating_point_v<T>,
        T,
        double
    >
Type trait that promotes integral types to double, while preserving floating-point types.
Template Parameters
T the input type
Definition at line 18 of file FloatingPointTypeTrait.ixx.
mat4d
using helios::math::mat4d = mat4<double> export
Definition at line 490 of file mat4.ixx.
mat4f
using helios::math::mat4f = mat4<float> export
Definition at line 489 of file mat4.ixx.
mat4i
using helios::math::mat4i = mat4<int> export
Definition at line 491 of file mat4.ixx.
vec2d
using helios::math::vec2d = vec2<double> export
Definition at line 188 of file vec2.ixx.
vec2f
using helios::math::vec2f = vec2<float> export
Definition at line 187 of file vec2.ixx.
vec2i
using helios::math::vec2i = vec2<int> export
Definition at line 189 of file vec2.ixx.
vec3d
using helios::math::vec3d = vec3<double> export
Double-precision floating-point 3D vector.
Definition at line 433 of file vec3.ixx.
vec3f
using helios::math::vec3f = vec3<float> export
Single-precision floating-point 3D vector.
Definition at line 423 of file vec3.ixx.
vec3i
using helios::math::vec3i = vec3<int> export
Integer 3D vector.
Definition at line 428 of file vec3.ixx.
vec4d
using helios::math::vec4d = vec4<double> export
Double-precision floating-point 4D vector.
Definition at line 154 of file vec4.ixx.
vec4f
using helios::math::vec4f = vec4<float> export
Single-precision floating-point 4D vector.
Definition at line 149 of file vec4.ixx.
vec4i
using helios::math::vec4i = vec4<int> export
Integer 4D vector.
Definition at line 159 of file vec4.ixx.
Enumeration Type Documentation
TransformType
enum class helios::math::TransformType : uint8_t export strong
Bitmask enum controlling which transform components a child node inherits from its parent.
When a SceneNode is attached to a parent, its final world transform is computed by combining the parent's world transform with the child's local transform. The `Inherit` flags determine which components (Translation, Rotation, Scale) of the parent transform are applied to the child.
This enables flexible scene graph behaviors such as:
A camera that follows an object's position but maintains its own orientation (`TransformType::Translation`)
UI elements that inherit full transforms (`TransformType::All`)
Objects that only inherit rotation for billboard effects (`TransformType::Rotation`)
Example usage: ```cpp using namespace helios::math;
// Camera follows spaceship position only cameraNode->setInheritance(TransformType::Translation);
// Full transform inheritance (default) childNode->setInheritance(TransformType::All);
// Combine specific flags node->setInheritance(TransformType::Translation | TransformType::Rotation); ```
Enumerator
Translation
Inherit only the translation component from the parent.
The child's world position is offset by the parent's world position, but rotation and scale remain unaffected by the parent.
Rotation
Inherit only the rotation component from the parent.
The child's orientation is combined with the parent's orientation, but position and scale remain unaffected.
Scale
Inherit only the scale component from the parent.
The child's scale is multiplied by the parent's scale, but position and rotation remain unaffected.
All
Inherit all transform components (Translation, Rotation, Scale).
This is the default behavior where the child's world transform is the full composition of parent and local transforms.
Definition at line 41 of file TransformType.ixx.
Function Documentation
cross()
template<helios::math::Numeric T> vec3< T > helios::math::cross (const vec3< T > & v1, const vec3< T > & v2) constexpr export noexcept
Computes the cross product of two 3D vectors.
Template Parameters
T The numeric type of the vector components.
Parameters
v1 The first vec3<T> vector.
v2 The second vec3<T> vector.
Returns
A new vec3<T> instance representing the cross product.
Definition at line 341 of file vec3.ixx.
Referenced by helios::math::mat4< float >::inverse().
degrees()
float helios::math::degrees (const float radians) constexpr export noexcept
Converts an angle from radians to degrees.
Parameters
radians The angle value in radians.
Returns
The converted angle value in degrees.
Definition at line 40 of file utils.ixx.
References radians().
Referenced by helios::engine::game::components::physics::Move2DComponent::move().
dot() [1/2]
template<helios::math::Numeric T> T helios::math::dot (const vec2< T > & v1, const vec2< T > & v2) constexpr export noexcept
Computes the dot product of two 2D vectors.
Template Parameters
T The numeric type of the vector components.
Parameters
v1 The first vec2<T> vector.
v2 The second vec2<T> vector.
Returns
The dot product as a value of type T.
Definition at line 183 of file vec2.ixx.
Referenced by helios::math::mat4< float >::inverse().
dot() [2/2]
template<helios::math::Numeric T> T helios::math::dot (const vec3< T > & v1, const vec3< T > & v2) constexpr export noexcept
Computes the dot product of two 3D vectors.
Template Parameters
T The numeric type of the vector components.
Parameters
v1 The first vec3<T> vector.
v2 The second vec3<T> vector.
Returns
The dot product as a value of type T.
Definition at line 359 of file vec3.ixx.
lookAt()
mat4f helios::math::lookAt (const vec3f & eye, const vec3f & center, const vec3f & up) export noexcept
Returns the 4x4 lookAt-matrix for transforming world coordinates to camera space. The method creates the camera coordinate system based on the parameters eye, i.e. the vantage point in world space, the camera's up direction and center, representing the point of interest. Note that the returned matrix is essentially a composition of a change of coordinates matrix P(C <- W) and a translation to the origin, i.e. the camera is sitting at the origin (0, 0, 0) looking down the negative z-axis, i.e. conceptually.
P(W<-C) * T(-eye)
The 4x4 matrix can then be used for computing the perspective projection for creating the clip space
clip = P * V * W * M
Parameters
eye
center
up
Returns
operator*() [1/5]
template<typename T> helios::math::aabb< T > helios::math::operator* (const helios::math::aabb< T > & aabb, const helios::math::vec3< T > v) nodiscard constexpr export noexcept
Scales an AABB by a given vector.
This operator overload allows scaling of an axis-aligned bounding box (AABB) by multiplying its min and max points with the given vector.
Template Parameters
T The numeric type of the vector components.
Parameters
aabb The AABB to be scaled.
v The scaling vector, for which only positive values are allowed.
Returns
A new AABB scaled by the given vector.
Definition at line 264 of file aabb.ixx.
References helios::math::aabb< T >::max(), and helios::math::aabb< T >::min().
operator*() [2/5]
template<helios::math::Numeric T> vec3< T > helios::math::operator* (const T n, const vec3< T > & v) constexpr export noexcept
Multiplies a scalar value by a 3D vector.
Template Parameters
T The numeric type of the vector components.
Parameters
n The scalar value to multiply the vector by.
v The vec3<T> vector to be multiplied.
Returns
A new vec3<T> instance representing the result of the scalar multiplication.
Definition at line 296 of file vec3.ixx.
operator*() [3/5]
template<helios::math::Numeric T> vec2< T > helios::math::operator* (const vec2< T > & v, const T n) constexpr export noexcept
Multiplies a 2D vector by a scalar value.
Template Parameters
T The numeric type of the vector components.
Parameters
v The vec2<T> vector to be multiplied.
n The scalar vector to multiplay the vector by.
Returns
a new vec2<T> instance representing the result of the scalar multiplication.
Definition at line 168 of file vec2.ixx.
operator*() [4/5]
template<helios::math::Numeric T> vec3< T > helios::math::operator* (const vec3< T > & v, const T n) constexpr export noexcept
Multiplies a 3D vector by a scalar value.
Template Parameters
T The numeric type of the vector components.
Parameters
v The vec3<T> vector to be multiplied.
n The scalar value to multiply the vector by.
Returns
a new vec3<T> instance representing the result of the scalar multiplication.
Definition at line 263 of file vec3.ixx.
operator*() [5/5]
template<helios::math::Numeric T> vec3< T > helios::math::operator* (const vec3< T > & v1, const vec3< T > & v2) constexpr export noexcept
Multiplies two vectors componentwise.
Template Parameters
T The numeric type of the vector components.
Parameters
v1 The left-hand vec3<T> vector to be multiplied.
v2 The right-hand vec3<T> vector to be multiplied.
Returns
A new vec3<T> instance representing the result of the componentwise multiplication of the two vectors.
Definition at line 311 of file vec3.ixx.
operator+() [1/2]
template<typename T> helios::math::aabb< T > helios::math::operator+ (const helios::math::aabb< T > aabb, const helios::math::vec3< T > v) nodiscard constexpr export noexcept
Adds a translation vector to an AABB.
This operator overload allows the addition of a translation vector to an axis-aligned bounding box (AABB), resulting in a new translated AABB.
Template Parameters
T The numeric type of the vector components (e.g., `float` or `double`).
Parameters
aabb The AABB to be translated.
v The translation vector to apply.
Returns
A new AABB translated by the given vector.
Definition at line 246 of file aabb.ixx.
References helios::math::aabb< T >::translate().
operator+() [2/2]
template<helios::math::Numeric T> vec3< T > helios::math::operator+ (const vec3< T > & v1, const vec3< T > & v2) constexpr export noexcept
Calculates the componentwise sum of the two vectors.
Template Parameters
T The numeric type of the vector components.
Parameters
v1 The left-hand vec3<T> vector to be added.
v2 The right-hand vec3<T> vector to be added.
Returns
A new vec3<T> instance representing the sum of the two vectors.
Definition at line 326 of file vec3.ixx.
operator-()
template<helios::math::Numeric T> vec3< T > helios::math::operator- (const vec3< T > & v1, const vec3< T > & v2) constexpr export noexcept
Computes the difference between two vectors (vector subtraction).
Template Parameters
T The numeric type of the vector components.
Parameters
v1 The first vec3<T> vector.
v2 The second vec3<T> vector.
Returns
A new vec3<T> instance representing the difference between v1 and v2.
Definition at line 374 of file vec3.ixx.
operator/()
template<helios::math::Numeric T> vec3< T > helios::math::operator/ (const vec3< T > & v, T s) constexpr export noexcept
Divides a 3D vector by a scalar value.
Template Parameters
T The numeric type of the vector components.
Parameters
v The vec3<T> vector to be divided.
s The scalar divisor. Must not be zero.
Returns
A new vec3<T> instance representing the result of the scalar division.
Precondition
s != 0 (asserted in debug builds).
Definition at line 279 of file vec3.ixx.
operator|()
TransformType helios::math::operator| (TransformType a, TransformType b) inline export
Combines two Inherit flags using bitwise OR.
Parameters
a The first inheritance flag.
b The second inheritance flag.
Returns
The combined inheritance mask.
Definition at line 83 of file TransformType.ixx.
perspective()
mat4f helios::math::perspective (float fovY, float aspect, float zNear, float zFar) export noexcept
Computes the 4x4 perspective projection matrix based on the specified field of view, aspect ratio, and near and far clipping planes.
This method returns a matrix suitable for projecting 3D points onto a 2D screen from the perspective of a camera. The perspective transformation maps 3D points inside the specified viewing frustum to normalized device coordinates, which are then clipped and transformed to screen space.
Parameters
fovY Field of view in the Y direction, specified in radians.
aspect The aspect ratio of the view, defined as width divided by height.
zNear The distance to the near clipping plane. Must be greater than zero.
zFar The distance to the far clipping plane. Must be greater than zNear.
Returns
A 4x4 matrix representing the perspective projection transformation.
See also
https://thorsten.suckow-homberg.de/docs/articles/computer-graphics/from-camera-to-clip-space-derivation-of-the-projection-matrices
Referenced by helios::scene::Camera::update().
radians()
float helios::math::radians (const float angle) constexpr export noexcept
Converts an angle from degrees to radians.
Parameters
angle The angle value in degrees.
Returns
The converted angle value in radians.
Definition at line 30 of file utils.ixx.
Referenced by degrees(), helios::ext::imgui::widgets::CameraWidget::draw(), and rotate().
rotate()
mat4f helios::math::rotate (const mat4f & model, float radians, const vec3f & axis) export noexcept
Creates an affine rotation matrix R' = M * R by "baking" the rotation part into the model matrix. Any operation R' * v will make sure that v is rotated around the local origin, then transformed into world space.
Parameters
model
radians
axis
Returns
References radians().
scale() [1/2]
mat4f helios::math::scale (const mat4f & model, const float scale_by) constexpr export noexcept
Creates an affine transformation matrix S' = M * S by "baking" the scaling part into the model matrix. Any operation S' * v will make sure that v is scaled in local space, then transformed into world space.
Parameters
model
scale_by
Returns
Definition at line 73 of file model.ixx.
scale() [2/2]
mat4f helios::math::scale (const mat4f & model, const vec3f & v) constexpr export noexcept
Creates an affine transformation matrix S' = M * S by ""baking" the scaling part into the model matrix. Any operation S' * v will make sure that v is scaled in local space, then transformed into world space.
Parameters
model
v
Returns
Definition at line 53 of file model.ixx.
transformTypeMatch()
bool helios::math::transformTypeMatch (TransformType mask, TransformType flag) inline export
Checks if a specific inheritance flag is set in a mask.
Parameters
mask The inheritance mask to check against.
flag The specific flag to test for.
Returns
`true` if the flag is present in the mask, `false` otherwise.
Example usage: ```cpp using namespace helios::math;
TransformType mode = TransformType::Translation | TransformType::Rotation;
if (transformTypeMatch(mode, TransformType::Translation)) { // Apply parent translation... } ```
Definition at line 107 of file TransformType.ixx.
Referenced by helios::math::mat4< float >::decompose().
translate()
mat4f helios::math::translate (const mat4f & model, const vec3f & v) constexpr export noexcept
Creates an affine transformation matrix M' = M * T by "baking" the translation part into the model matrix. Any operation M' * v will make sure that v is translated in local space, then transformed into world space.
Parameters
model
v
Returns
Definition at line 35 of file model.ixx.
value_ptr() [1/3]
template<helios::math::Numeric T> const T * helios::math::value_ptr (const mat4< T > & m) export noexcept
Returns a const pointer to the first element of the matrix's components.
Useful for APIs that expect a pointer to matrix data, like OpenGL.
Template Parameters
T The numeric type of the matrix components.
Parameters
m A reference to the `mat4<T>` matrix.
Returns
A const pointer to the element at [0, 0].
Definition at line 468 of file mat4.ixx.
Referenced by helios::math::mat4< float >::operator==(), and helios::math::mat4< float >::same().
value_ptr() [2/3]
template<helios::math::Numeric T> const T * helios::math::value_ptr (const vec4< T > & m) export noexcept
Returns a const pointer to the first element of the vector's components.
Useful for APIs that expect a pointer to vector data, like OpenGL
Parameters
m A reference to the `vec4<T>` vector.
Template Parameters
T The numeric type of the vector components.
Definition at line 142 of file vec4.ixx.
value_ptr() [3/3]
template<helios::math::Numeric T> T * helios::math::value_ptr (mat4< T > & m) export noexcept
Returns a pointer to the first element of the matrix's components.
Useful for APIs that expect a pointer to matrix data, like OpenGL.
Template Parameters
T The numeric type of the matrix components.
Parameters
m A reference to the `mat4<T>` matrix.
Returns
A pointer to the element at [0, 0].
Definition at line 485 of file mat4.ixx.
Variable Documentation
EPSILON_LENGTH
float helios::math::EPSILON_LENGTH = 1e-6f constexpr export
A small epsilon value used for length-based comparisons.
This constant represents the minimum threshold value for length comparisons to account for numerical precision errors in floating-point calculations. It is often used to avoid treating very small values as significant, effectively filtering out noise in computations that involve vector-lengths.
Definition at line 22 of file utils.ixx.
Referenced by helios::engine::game::components::physics::Move2DComponent::move(), helios::engine::game::components::physics::Move2DComponent::speedRatio(), helios::engine::game::components::gameplay::ShootComponent::update(), and helios::engine::game::components::input::TwinStickInputComponent::update().