helios: helios::math::vec4< T > Struct Template Reference
helios::math::vec4< T > Struct Template Reference export
module helios.math.types
Represents a 4-dimensional vector of the generic type <T>.
Public Member Functions
constexpr vec4 () noexcept
Creates a new vec4 with its values initialized to (0, 0, 0, 0).
constexpr vec4 (const T x, const T y, const T z, const T w) noexcept
Constructs a new vec4 with the specified x, y, z, w components.
constexpr vec4 (const vec3< T > &vec, const T w) noexcept
Constructs a new vec4 from the vec3 vector and the w value.
constexpr vec4 (const vec3< T > &vec) noexcept
Constructs a new vec4 from the vec3 vector and sets w to 1.
constexpr vec4< T > withW (T w) const noexcept
Creates a new vec4 with the same x, y, z components but a modified w component.
constexpr const T & operator[] (const size_t i) const noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
constexpr T & operator[] (const size_t i) noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
vec3< T > toVec3 () const noexcept
Converts this 4D vector to a 3D vector.
Detailed Description
template<helios::math::Numeric T>
struct helios::math::vec4< T >
Represents a 4-dimensional vector of the generic type <T>.
The `vec4` struct provides a lightweight and efficient way to handle 4D vector mathematics for the numeric types float, int, double. For convenient access, the shorthands `vec4f`, `vec4d` and `vec4i` are available.
Template Parameters
T The numeric type of the vector components.
Definition at line 33 of file vec4.ixx.
Constructor & Destructor Documentation
vec4() [1/4]
template<helios::math::Numeric T> helios::math::vec4< T >::vec4 () inline constexpr export noexcept
Creates a new vec4 with its values initialized to (0, 0, 0, 0).
Definition at line 46 of file vec4.ixx.
Referenced by toVec3().
vec4() [2/4]
template<helios::math::Numeric T> helios::math::vec4< T >::vec4 (const T x, const T y, const T z, const T w) inline constexpr export noexcept
Constructs a new vec4 with the specified x, y, z, w components.
Parameters
x The value for the x component.
y The value for the y component.
z The value for the z component.
w The value for the w component.
Definition at line 57 of file vec4.ixx.
vec4() [3/4]
template<helios::math::Numeric T> helios::math::vec4< T >::vec4 (const vec3< T > & vec, const T w) inline constexpr export noexcept
Constructs a new vec4 from the vec3 vector and the w value.
Parameters
vec The vec3<T> vector.
w The value for the w component.
Definition at line 66 of file vec4.ixx.
vec4() [4/4]
template<helios::math::Numeric T> helios::math::vec4< T >::vec4 (const vec3< T > & vec) inline explicit constexpr export noexcept
Constructs a new vec4 from the vec3 vector and sets w to 1.
Parameters
vec The vec3<T> vector.
Definition at line 74 of file vec4.ixx.
Member Function Documentation
operator[]() [1/2]
template<helios::math::Numeric T> const T & helios::math::vec4< T >::operator[] (const size_t i) const inline constexpr export noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
Parameters
i The index to query
Returns
A const ref to the requested component.
Definition at line 98 of file vec4.ixx.
operator[]() [2/2]
template<helios::math::Numeric T> T & helios::math::vec4< T >::operator[] (const size_t i) inline constexpr export noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
Parameters
i The index to query
Returns
A ref to the requested component.
Definition at line 112 of file vec4.ixx.
toVec3()
template<helios::math::Numeric T> vec3< T > helios::math::vec4< T >::toVec3 () const inline nodiscard export noexcept
Converts this 4D vector to a 3D vector.
Extracts the x, y, z components from this vec4, discarding the w component. This is useful when converting from homogeneous coordinates back to 3D space.
Returns
A new vec3<T> instance with components (x, y, z).
Definition at line 130 of file vec4.ixx.
References toVec3(), and vec4().
Referenced by toVec3().
withW()
template<helios::math::Numeric T> vec4< T > helios::math::vec4< T >::withW (T w) const inline nodiscard constexpr export noexcept
Creates a new vec4 with the same x, y, z components but a modified w component.
This method returns a new vec4 instance where the x, y, and z components remain unchanged, and the w component is set to the specified value.
Parameters
w The new value for the w component.
Returns
A new vec4<T> instance with the updated w component.
Definition at line 86 of file vec4.ixx.
The documentation for this struct was generated from the following files:
include/helios/math/types/vec3.ixx
include/helios/math/types/vec4.ixx