helios: helios::math::vec3< T > Struct Template Reference
helios::math::vec3< T > Struct Template Reference export
module helios.math.types
Represents a 3-dimensional vector of the generic type <T>.
Public Member Functions
constexpr vec3 () noexcept
Creates a new vec3 with its values initialized to (0, 0, 0).
constexpr vec3 (const T x, const T y, const T z) noexcept
Constructs a new vec3 with the specified x, y, z components.
constexpr vec3 (const T v) noexcept
Constructs a new vec3 with the specified value as the x,y,z components.
constexpr vec3 (const helios::math::vec2< T > v) noexcept
Constructs a new vec3 with x,y components initialized to those of the vec2 and vec3 set to 0.
constexpr vec3 (const helios::math::vec2< T > v, T f) noexcept
Constructs a new vec3 with x,y components initialized to those of the vec2 and the z component set to the specified value.
constexpr const T & operator[] (const size_t i) const noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
constexpr T & operator[] (const size_t i) noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
FloatingPointType< T > length () const noexcept
Computes the Euclidean norm (magnitude) of this vector and returns it.
vec3< T > cross (const helios::math::vec3< T > &v2) const noexcept
Computes the cross product of this vector and v2.
T dot (const helios::math::vec3< T > &v2) const noexcept
Computes the dot product of this vector and v2.
vec4< T > toVec4 () const noexcept
Converts this 3D vector to a 4D homogeneous vector.
vec4< T > toVec4 (T w) const noexcept
Converts this 3D vector to a 4D homogeneous vector.
vec3< FloatingPointType< T > > normalize () const noexcept
Returns a normalized version of this vector.
constexpr bool operator== (const vec3< T > &rgt) const
Strictly compares the elements of this vector with the elements of the rgt vector.
constexpr bool same (const vec3< T > &rgt, T epsilon=0.0001) const
Compares this vector's elements with the rgt vector considering an epsilon value. Returns true if for all elements the equation |a-b| <= epsilon holds.
constexpr helios::math::vec3< T > flipY () const noexcept
Returns a new vector with the y-component negated.
constexpr helios::math::vec3< T > withY (T y) const noexcept
Returns a new vector with the y-component replaced by the given value.
constexpr helios::math::vec3< T > flipX () const noexcept
Returns a new vector with the x-component negated.
constexpr helios::math::vec3< T > withX (T x) const noexcept
Returns a new vector with the x-component replaced by the given value.
Detailed Description
template<helios::math::Numeric T>
struct helios::math::vec3< T >
Represents a 3-dimensional vector of the generic type <T>.
The `vec3` struct provides a lightweight and efficient way to handle 3D vector mathematics for the numeric types float, int, double. For convenient access, the shorthands `vec3f`, `vec3d` and `vec3i` are available.
Template Parameters
T The numeric type of the vector components.
Definition at line 32 of file vec3.ixx.
Constructor & Destructor Documentation
vec3() [1/5]
template<helios::math::Numeric T> helios::math::vec3< T >::vec3 () inline constexpr export noexcept
Creates a new vec3 with its values initialized to (0, 0, 0).
Definition at line 46 of file vec3.ixx.
Referenced by cross(), dot(), and normalize().
vec3() [2/5]
template<helios::math::Numeric T> helios::math::vec3< T >::vec3 (const T x, const T y, const T z) inline constexpr export noexcept
Constructs a new vec3 with the specified x, y, z components.
Parameters
x The value for the x component.
y The value for the y component.
z The value for the z component.
Definition at line 57 of file vec3.ixx.
vec3() [3/5]
template<helios::math::Numeric T> helios::math::vec3< T >::vec3 (const T v) inline explicit constexpr export noexcept
Constructs a new vec3 with the specified value as the x,y,z components.
Parameters
v The value for the components.
Definition at line 66 of file vec3.ixx.
vec3() [4/5]
template<helios::math::Numeric T> helios::math::vec3< T >::vec3 (const helios::math::vec2< T > v) inline explicit constexpr export noexcept
Constructs a new vec3 with x,y components initialized to those of the vec2 and vec3 set to 0.
Parameters
v The vec2 to use for the x,y components.
Definition at line 75 of file vec3.ixx.
vec3() [5/5]
template<helios::math::Numeric T> helios::math::vec3< T >::vec3 (const helios::math::vec2< T > v, T f) inline explicit constexpr export noexcept
Constructs a new vec3 with x,y components initialized to those of the vec2 and the z component set to the specified value.
Parameters
v The vec2 to use for the x,y components.
f The value for the z component.
Definition at line 84 of file vec3.ixx.
Member Function Documentation
cross()
template<helios::math::Numeric T> vec3< T > helios::math::vec3< T >::cross (const helios::math::vec3< T > & v2) const inline nodiscard export noexcept
Computes the cross product of this vector and v2.
Parameters
v2 The second vec3<T> vector.
Returns
The cross product as a value of type vec3<T>.
Definition at line 379 of file vec3.ixx.
References vec3().
dot()
template<helios::math::Numeric T> T helios::math::vec3< T >::dot (const helios::math::vec3< T > & v2) const inline nodiscard export noexcept
Computes the dot product of this vector and v2.
Parameters
v2 The second vec3<T> vector.
Returns
The dot product as a value of type T.
Definition at line 398 of file vec3.ixx.
References vec3().
flipX()
template<helios::math::Numeric T> helios::math::vec3< T > helios::math::vec3< T >::flipX () const inline constexpr export noexcept
Returns a new vector with the x-component negated.
Returns
A new vec3<T> with (-x, y, z).
Definition at line 236 of file vec3.ixx.
flipY()
template<helios::math::Numeric T> helios::math::vec3< T > helios::math::vec3< T >::flipY () const inline constexpr export noexcept
Returns a new vector with the y-component negated.
Returns
A new vec3<T> with (x, -y, z).
Definition at line 217 of file vec3.ixx.
length()
template<helios::math::Numeric T> FloatingPointType< T > helios::math::vec3< T >::length () const inline export noexcept
Computes the Euclidean norm (magnitude) of this vector and returns it.
Returns
The norm (magnitude) of this vector as a value of type FloatingPointType<T>.
Definition at line 119 of file vec3.ixx.
Referenced by helios::ext::imgui::widgets::CameraWidget::draw(), and normalize().
normalize()
template<helios::math::Numeric T> vec3< FloatingPointType< T > > helios::math::vec3< T >::normalize () const inline nodiscard export noexcept
Returns a normalized version of this vector.
Returns
A new vec3<FloatingPointType<T>> instance representing the normalized vector.
Definition at line 404 of file vec3.ixx.
References length(), and vec3().
operator==()
template<helios::math::Numeric T> bool helios::math::vec3< T >::operator== (const vec3< T > & rgt) const inline constexpr export
Strictly compares the elements of this vector with the elements of the rgt vector.
Parameters
rgt The right vector to compare for equal values.
Returns
True if all elements are equal (==), false otherwise.
Definition at line 184 of file vec3.ixx.
operator[]() [1/2]
template<helios::math::Numeric T> const T & helios::math::vec3< T >::operator[] (const size_t i) const inline constexpr export noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
Parameters
i The index to query
Returns
A const ref to the requested component.
Definition at line 94 of file vec3.ixx.
operator[]() [2/2]
template<helios::math::Numeric T> T & helios::math::vec3< T >::operator[] (const size_t i) inline constexpr export noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
Parameters
i The index to query
Returns
A const ref to the requested component.
Definition at line 108 of file vec3.ixx.
same()
template<helios::math::Numeric T> bool helios::math::vec3< T >::same (const vec3< T > & rgt, T epsilon = 0.0001) const inline constexpr export
Compares this vector's elements with the rgt vector considering an epsilon value. Returns true if for all elements the equation |a-b| <= epsilon holds.
Parameters
rgt The other vector to compare with this vector for equality.
epsilon The epsilon value to use for comparison. If omitted, the default epsilon (0.0001) is used.
Returns
True if the elements of the vectors are considered equal, otherwise false.
See also
https://realtimecollisiondetection.net/blog/?p=89
Todo
account for abs (values close to zero) and rel (larger values), move epsilon to global constant?
Definition at line 206 of file vec3.ixx.
toVec4() [1/2]
template<helios::math::Numeric T> vec4< T > helios::math::vec3< T >::toVec4 () const inline nodiscard export noexcept
Converts this 3D vector to a 4D homogeneous vector.
Creates a vec4 with the x, y, z components from this vector and sets the w component to 0, representing a direction in homogeneous coordinates.
Returns
A new vec4<T> instance with components (x, y, z, 0).
Definition at line 388 of file vec3.ixx.
toVec4() [2/2]
template<helios::math::Numeric T> vec4< T > helios::math::vec3< T >::toVec4 (T w) const inline nodiscard export noexcept
Converts this 3D vector to a 4D homogeneous vector.
Creates a vec4 with the x, y, z components from this vector and sets the w component accordingly, representing a direction in homogeneous coordinates.
Parameters
w The value of the w component.
Returns
A new vec4<T> instance with components (x, y, z, w).
Definition at line 393 of file vec3.ixx.
withX()
template<helios::math::Numeric T> helios::math::vec3< T > helios::math::vec3< T >::withX (T x) const inline constexpr export noexcept
Returns a new vector with the x-component replaced by the given value.
Parameters
x The new x value.
Returns
A new vec3<T> with (x, y, z).
Definition at line 246 of file vec3.ixx.
withY()
template<helios::math::Numeric T> helios::math::vec3< T > helios::math::vec3< T >::withY (T y) const inline constexpr export noexcept
Returns a new vector with the y-component replaced by the given value.
Parameters
y The new y value.
Returns
A new vec3<T> with (x, y, z).
Definition at line 227 of file vec3.ixx.
The documentation for this struct was generated from the following files:
include/helios/math/types/vec2.ixx
include/helios/math/types/vec3.ixx