helios: helios::engine::game::UpdateContext Struct Reference
helios::engine::game::UpdateContext Struct Reference export
module helios.engine.game.UpdateContext
Context passed to Updatable components during per-frame updates.
Public Member Functions
UpdateContext (helios::engine::game::CommandBuffer *commandBuffer, helios::engine::game::GameWorld *gameWorld)
Constructs an UpdateContext with required dependencies.
float deltaTime () const noexcept
Returns the time elapsed since the last frame, in seconds.
UpdateContext & setDeltaTime (float dt) noexcept
Sets the time elapsed since the last frame.
const helios::engine::game::InputSnapshot * inputSnapshot () const noexcept
Returns the immutable input snapshot for this frame.
UpdateContext & setInputSnapshot (const helios::engine::game::InputSnapshot *snapshot) noexcept
Sets the input snapshot for this frame.
helios::engine::game::CommandBuffer * commandBuffer () const noexcept
Returns the command buffer for queueing commands.
helios::engine::game::GameWorld * gameWorld () const noexcept
Returns the game world for entity lookups.
Detailed Description
Context passed to Updatable components during per-frame updates.
Provides all necessary state for components to perform their update logic, including frame timing, input state, and access to the command system. All pointers are non-owning; the caller is responsible for lifetime management.
Definition at line 26 of file UpdateContext.ixx.
Constructor & Destructor Documentation
UpdateContext()
helios::engine::game::UpdateContext::UpdateContext (helios::engine::game::CommandBuffer * commandBuffer, helios::engine::game::GameWorld * gameWorld) inline export
Constructs an UpdateContext with required dependencies.
Parameters
commandBuffer Non-owning pointer to the command buffer. Must not be nullptr.
gameWorld Non-owning pointer to the game world. Must not be nullptr.
Exceptions
std::invalid_argument if either commandBuffer or gameWorld are nullptr
Definition at line 59 of file UpdateContext.ixx.
References commandBuffer(), and gameWorld().
Referenced by setDeltaTime(), and setInputSnapshot().
Member Function Documentation
commandBuffer()
helios::engine::game::CommandBuffer * helios::engine::game::UpdateContext::commandBuffer () const inline nodiscard export noexcept
Returns the command buffer for queueing commands.
Returns
Non-owning pointer. Guaranteed non-null after construction.
Definition at line 117 of file UpdateContext.ixx.
Referenced by UpdateContext().
deltaTime()
float helios::engine::game::UpdateContext::deltaTime () const inline nodiscard export noexcept
Returns the time elapsed since the last frame, in seconds.
Definition at line 73 of file UpdateContext.ixx.
gameWorld()
helios::engine::game::GameWorld * helios::engine::game::UpdateContext::gameWorld () const inline nodiscard export noexcept
Returns the game world for entity lookups.
Returns
Non-owning pointer. Guaranteed non-null after construction.
Definition at line 126 of file UpdateContext.ixx.
Referenced by UpdateContext().
inputSnapshot()
const helios::engine::game::InputSnapshot * helios::engine::game::UpdateContext::inputSnapshot () const inline nodiscard export noexcept
Returns the immutable input snapshot for this frame.
Returns
Non-owning pointer. May be nullptr if no input is available.
Definition at line 95 of file UpdateContext.ixx.
setDeltaTime()
UpdateContext & helios::engine::game::UpdateContext::setDeltaTime (float dt) inline export noexcept
Sets the time elapsed since the last frame.
Parameters
dt Delta time in seconds. Must be non-negative.
Returns
A reference to this UpdateContext instance.
Definition at line 84 of file UpdateContext.ixx.
References UpdateContext().
setInputSnapshot()
UpdateContext & helios::engine::game::UpdateContext::setInputSnapshot (const helios::engine::game::InputSnapshot * snapshot) inline export noexcept
Sets the input snapshot for this frame.
Parameters
snapshot Non-owning pointer to the input snapshot.
Returns
A reference to this UpdateContext instance.
Definition at line 106 of file UpdateContext.ixx.
References UpdateContext().
The documentation for this struct was generated from the following file:
include/helios/engine/game/UpdateContext.ixx