helios: helios::rendering::asset::shape::basic::Circle Struct Reference
helios::rendering::asset::shape::basic::Circle Struct Reference export
module helios.rendering.asset.shape.basic.Circle
Basic Circle Shape (2D, in XY plane).
Public Member Functions
Circle ()
Creates a default circle (radius 1.0, 64 segments).
Circle (float radius, unsigned int segments)
Creates a circle with a specific radius and segment count.
helios::rendering::model::config::PrimitiveType primitiveType () const noexcept override
Returns the intended PrimitiveType for this Shape.
Public Member Functions inherited from helios::rendering::asset::shape::Shape
virtual ~Shape ()=default
Shape (std::vector< Vertex > vertices, std::vector< unsigned int > indices)
Creates a new shape from the given vertices and indices. The data is copied into immutable shared vectors.
Additional Inherited Members
Public Attributes inherited from helios::rendering::asset::shape::Shape
std::shared_ptr< const std::vector< Vertex > > vertices = {}
Shared pointer to an immutable vector of vertices for this shape.
std::shared_ptr< const std::vector< unsigned int > > indices = {}
Shared pointer to an immutable vector of indices for this shape.
Detailed Description
Basic Circle Shape (2D, in XY plane).
Generates a 2D circle mesh, centered at the origin on the XY plane (Z=0). The normals point in the positive Z direction. The indices are arranged as a Triangle Fan (for GL_TRIANGLES).
Definition at line 29 of file Circle.ixx.
Constructor & Destructor Documentation
Circle() [1/2]
helios::rendering::asset::shape::basic::Circle::Circle () inline export
Creates a default circle (radius 1.0, 64 segments).
Definition at line 94 of file Circle.ixx.
References Circle().
Referenced by Circle().
Circle() [2/2]
helios::rendering::asset::shape::basic::Circle::Circle (float radius, unsigned int segments) inline explicit export
Creates a circle with a specific radius and segment count.
Parameters
radius The radius of the circle (from center to circumference).
segments The number of triangle segments that make up the circle. (More segments = smoother circle).
Definition at line 103 of file Circle.ixx.
References helios::rendering::asset::shape::Shape::Shape().
Member Function Documentation
primitiveType()
helios::rendering::model::config::PrimitiveType helios::rendering::asset::shape::basic::Circle::primitiveType () const inline nodiscard override export virtual noexcept
Returns the intended PrimitiveType for this Shape.
This method returns the intended PrimitiveType for the Shape represented by this instance. This information can be used to properly set up the MeshConfig wrapping this Shape.
Returns
The intended PrimitiveType of this Shape.
Implements helios::rendering::asset::shape::Shape.
Definition at line 109 of file Circle.ixx.
References helios::rendering::model::config::Triangles.
The documentation for this struct was generated from the following file:
include/helios/rendering/asset/shape/basic/Circle.ixx