helios: helios::scene::SnapshotItem Struct Reference
helios::scene::SnapshotItem Struct Reference export
module helios.scene.SnapshotItem
Structure for representing a snapshot item of a renderable's object state at a specific point in time.
Public Member Functions
SnapshotItem (const SnapshotItem &)=delete
Prevent copying.
SnapshotItem & operator= (const SnapshotItem &)=delete
SnapshotItem (SnapshotItem &&) noexcept=default
Provide custom move constructor.
SnapshotItem (std::weak_ptr< const helios::rendering::Renderable > renderable, const helios::math::mat4f &worldMatrix)
Constructs a new SnapshotItem with the specified renderable and the worldMatrix.
std::weak_ptr< const helios::rendering::Renderable > renderable () const noexcept
Returns a weak_ptr to the Renderable of this SnapshotItem. Use `.lock()` on the returned weak_ptr to obtain a shared_ptr for the Renderable, if it still exists. If the Renderable does not exist, the SnapshotItem should be ignored for further processing.
const helios::math::mat4f & worldMatrix () const noexcept
Returns a const ref to the worldMatrix of this SnapshotItem. The world transformation matrix is a copy from the world transformation matrix created with this SnapshotItem.
Detailed Description
Structure for representing a snapshot item of a renderable's object state at a specific point in time.
The structure bundles a weak pointer to a Renderable and a pre-calculated worldMatrix, serving as a lightweight DTO to be used with a `Snapshot`.
A SnapshotItem captures the essential information to render an item without the need to traverse the entire Scene Graph during the rendering phase. The worldMatrix is a copy of the SceneNode's worldMatrix at the time of this creation, ensuring that its value remains constant, even if the transformation of the SceneNode should change during rendering.
Note that for the Renderable a weak pointer is stored to allow for checking its existence in the render pass. While internal properties of the Renderable might change while this SnapshotItem is processed, the worldMatrix is immutable and reflects the transformation state at the moment the Snapshot was taken.
Thus, as a precondition, we assume that no changes to the Renderable are made while the Renderable "exists" as a weak ptr in a particular Snapshot of a scene that would lead to invalidating its rendering. We rely on the state information available within the Renderable as a reflection of its state when the Snapshot was taken.
Todo
we're intentionally preferring stability over performance by using weak_ptr instead of raw pointers. This leaves room for (performance) improvements in later iterations. The Renderable as a weak pointer can later on be further implemented into a pure DTO, storing only scalar values that get send directly to the underlying rendering backend (e.g. vaos, vbos etc.).
Definition at line 48 of file SnapshotItem.ixx.
Constructor & Destructor Documentation
SnapshotItem() [1/3]
helios::scene::SnapshotItem::SnapshotItem (const SnapshotItem &) export delete
Prevent copying.
References SnapshotItem().
Referenced by operator=(), SnapshotItem(), SnapshotItem(), and SnapshotItem().
SnapshotItem() [2/3]
helios::scene::SnapshotItem::SnapshotItem (SnapshotItem &&) export default noexcept
Provide custom move constructor.
See also
https://en.cppreference.com/w/cpp/language/move_constructor.html
References SnapshotItem().
SnapshotItem() [3/3]
helios::scene::SnapshotItem::SnapshotItem (std::weak_ptr< const helios::rendering::Renderable > renderable, const helios::math::mat4f & worldMatrix) export
Constructs a new SnapshotItem with the specified renderable and the worldMatrix.
Parameters
renderable A weak_ptr to the Renderable.
worldMatrix A const ref to the world transformation matrix, which gets copied.
References renderable(), SnapshotItem(), and worldMatrix().
Member Function Documentation
operator=()
SnapshotItem & helios::scene::SnapshotItem::operator= (const SnapshotItem &) export delete
References SnapshotItem().
renderable()
std::weak_ptr< const helios::rendering::Renderable > helios::scene::SnapshotItem::renderable () const nodiscard export noexcept
Returns a weak_ptr to the Renderable of this SnapshotItem. Use `.lock()` on the returned weak_ptr to obtain a shared_ptr for the Renderable, if it still exists. If the Renderable does not exist, the SnapshotItem should be ignored for further processing.
Returns
A weak_ptr to the Renderable of this SnapshotItem.
References renderable().
Referenced by renderable(), and SnapshotItem().
worldMatrix()
const helios::math::mat4f & helios::scene::SnapshotItem::worldMatrix () const nodiscard export noexcept
Returns a const ref to the worldMatrix of this SnapshotItem. The world transformation matrix is a copy from the world transformation matrix created with this SnapshotItem.
Returns
The const ref to the world matrix of this SnapshotItem.
References worldMatrix().
Referenced by SnapshotItem(), and worldMatrix().
The documentation for this struct was generated from the following file:
include/helios/scene/SnapshotItem.ixx