helios: helios::rendering::asset::shape::Shape Struct Reference
helios::rendering::asset::shape::Shape Struct Reference abstract export
module helios.rendering.asset.shape.Shape
Struct representing geometric primitives and indices for various shapes. provides immutable, shared access to vertices and indices of the represented geometric shape.
Public Member Functions
virtual ~Shape ()=default
Shape (std::vector< Vertex > vertices, std::vector< unsigned int > indices)
Creates a new shape from the given vertices and indices. The data is copied into immutable shared vectors.
virtual helios::rendering::model::config::PrimitiveType primitiveType () const noexcept=0
Returns the intended PrimitiveType for this Shape.
Public Attributes
std::shared_ptr< const std::vector< Vertex > > vertices = {}
Shared pointer to an immutable vector of vertices for this shape.
std::shared_ptr< const std::vector< unsigned int > > indices = {}
Shared pointer to an immutable vector of indices for this shape.
Detailed Description
Struct representing geometric primitives and indices for various shapes. provides immutable, shared access to vertices and indices of the represented geometric shape.
Definition at line 24 of file Shape.ixx.
Constructor & Destructor Documentation
~Shape()
virtual helios::rendering::asset::shape::Shape::~Shape () export virtual default
Shape()
helios::rendering::asset::shape::Shape::Shape (std::vector< Vertex > vertices, std::vector< unsigned int > indices) inline export
Creates a new shape from the given vertices and indices. The data is copied into immutable shared vectors.
Parameters
vertices A vector of vertices representing the shape's geometry
indices A vector of unsigned integers representing the shape's indices.
Definition at line 45 of file Shape.ixx.
References indices, and vertices.
Referenced by helios::rendering::asset::shape::basic::Circle::Circle(), helios::rendering::asset::shape::basic::Cube::Cube(), helios::rendering::asset::shape::basic::Line::Line(), helios::rendering::asset::shape::basic::Rectangle::Rectangle(), and helios::rendering::asset::shape::basic::Triangle::Triangle().
Member Function Documentation
primitiveType()
virtual helios::rendering::model::config::PrimitiveType helios::rendering::asset::shape::Shape::primitiveType () const nodiscard export pure virtual noexcept
Returns the intended PrimitiveType for this Shape.
This method returns the intended PrimitiveType for the Shape represented by this instance. This information can be used to properly set up the MeshConfig wrapping this Shape.
Returns
The intended PrimitiveType of this Shape.
Implemented in helios::rendering::asset::shape::basic::Circle, helios::rendering::asset::shape::basic::Cube, helios::rendering::asset::shape::basic::Grid, helios::rendering::asset::shape::basic::Line, helios::rendering::asset::shape::basic::Rectangle, and helios::rendering::asset::shape::basic::Triangle.
The documentation for this struct was generated from the following file:
include/helios/rendering/asset/shape/Shape.ixx